### ISSUE TITLE
Invalid sequence positions, line 1162

### ISSUE THREAD

**Issue by skoren** [tseemann/prokka#102]
When running on a SOAPdenovo assembly, one of the returned positions starts at base 0, causing an error in the trunc function. This happens in both Prokka 1.7 and 1.11. I've posted the input file here:
ftp://ftp.cbcb.umd.edu/pub/data/sergek/prokka_bug.asm.contig.bz2

and the command I ran was:
prokka --fast --outdir soapdenovo.31.prokka --prefix soapdenovo.31 --force soapdenovo.31.asm.contig

I was able to work around the error by checking if the location is valid at the beginning of the loop.

```
   if (! $f->location->valid_Location) {
      next;
   }
```

**Comment by tseemann** [comment]
@skoren - that is one awful assembly... 400,000 contigs with N50 174bp ... are you sure it isn't just clipped reads? :-) 

(If this is a metagenome you can use the ```--metagenome``` option to help with gene prediction)

The bad feature seems to be a (pseudo) tRNA from Aragorn that I am not handling properly:
```1   tRNA-???                        [0,39]      39      (taaa)```

I've committed a fix for this now.

Thank you Sergey for taking the time to file this issue!
