### ISSUE TITLE
prokka-uniprot_to_fasta_db

### ISSUE THREAD

**Issue by chandni177** [tseemann/prokka#103]
Hi again,
Almost all of my queries have been solved here, so here's a few more!

I am trying to run prokka-uniprot_to_fasta_db but getting an error.
![screen shot 2015-04-14 at 1 38 58 pm](https://cloud.githubusercontent.com/assets/9219400/7144472/72c1db26-e2ab-11e4-858c-141dacf31335.png)

Secondly, I would like to add the NCBI non-redundant database to the Prokka db. Is the best place in the Genus or the Kingdom directories? I tried adding the nr database under the kingdom directory and upon running --listdb, here's what I get (because of the different parts the nr files are in)
![screen shot 2015-04-14 at 1 41 40 pm](https://cloud.githubusercontent.com/assets/9219400/7144541/e3c98346-e2ab-11e4-8001-f2e255ca8f2c.png)

How can I deal with these issues? 

Thanks a lot in advance!
Chandni

**Comment by aleimba** [comment]
hey,

1. You need to install the Swissknife Perl modules (http://swissknife.sourceforge.net/) for `prokka-uniprot_to_fasta_db` (namely `SWISS::Entry` and `SWISS::KW` as indicated at the beginning of the script).

2. I think Prokka isn't prepared for that yet (see #90 and #91).

HTH,
Andreas

**Comment by chandni177** [comment]
Hi Andreas,

Thanks a lot for the quick reply!
I installed the Swissknife Perl modules and it works great now.

Yes I did check those issues, but wondered if they had a workaround now.

Just as a confirmation, if I have a database that I would like to make a part of the Kindgom directories, how exactly should I use the prokka-uniprot_to_fasta_db command?

Thanks once again,
Chandni

**Comment by aleimba** [comment]
`prokka-uniprot_to_fasta_db` works only for databases you got from Uniprot (ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/). If you want to update these run, e.g.:
```bash
wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_sprot_bacteria.dat.gz
zcat uniprot_sprot_bacteria.dat.gz > uniprot_sprot_bacteria.dat
prokka-uniprot_to_fasta_db --verbose uniprot_sprot_bacteria.dat > sprot
mv ~/bin/prokka/db/kingdom/Bacteria
```
You have to move the update into one of the subdirectories of *kingdom* (Archaea, Bacteria, Mitochondria, or  Viruses).

If you want to include your own multi-fasta input databases (https://github.com/tseemann/prokka#fasta-database-format) you'll have to use `prokka-genbank_to_fasta_db` and `prokka` with option **--proteins**. These of course can also be multi-genome inputs. To create a multi-fasta input from reference genomes you can use `extractfeat` from EMBOSS (http://emboss.sourceforge.net/apps/release/6.6/emboss/apps/extractfeat.html) or one of mine (https://github.com/aleimba/bac-genomics-scripts/tree/master/cds_extractor).

Hope that's what you were looking for.

**Comment by chandni177** [comment]
Yes, that's what I wanted to confirm.
Thank you for all the help !

Chandni

**Comment by tseemann** [comment]
I have just updated the 'sprot' databases in git:
https://github.com/tseemann/prokka/commit/dd12d9c028088b5049b57429705a8eca228597a5

**Comment by aleimba** [comment]
Thank you, Torsten!

**Comment by chandni177** [comment]
Hello,

Just checking again to see if it is possible to use Prokka to annotate a genome with the NCBI nr database.
If so, where can I add it in the db directory? (Kingdom/Genus)

Thank you,
Chandni

**Comment by tseemann** [comment]
@chandni177 I don't think using `nr` is a good idea - it is full of mistakes. You could add it as a Genus database - it might work.
