### ISSUE TITLE
use only cosen proteins

### ISSUE THREAD

**Issue by tallnuttphone** [tseemann/prokka#104]
please add swtich to use only the chosen user protein database

**Comment by tseemann** [comment]
This is quite tricky for me to implement with the current design of Prokka.

Do you have a good "use-case" for such an option?

**Comment by tseemann** [comment]
I think you should just make a copy of the prokka script, rename it my "prokka.whatever" and modify the `@database` array to do what you want.  You can make as many prokka.XXX scripts as you want and it will all still work without losing the classic script, as long as they are in the same folder as prokka.
