### ISSUE TITLE
Pass options to aragorn

### ISSUE THREAD

**Issue by sjackman** [tseemann/prokka#107]
I'd like to pass the `-i` option to aragorn to search for tRNA genes with introns. I'm annotating plant organelles.

**Comment by sjackman** [comment]
I tried adding `-i` to [`aragorn_opt`](https://github.com/tseemann/prokka/blob/master/bin/prokka#L62), but the resulting tRNA with introns get filtered out by Prokka because they're [longer than 500 bp](https://github.com/tseemann/prokka/blob/master/bin/prokka#L484-L487).
```perl
my $aragorn_opt = '-i';
```
```
[15:05:46] tRNA/tmRNA c[883351,883869] is too big (>500bp) - skipping.
```

**Comment by tseemann** [comment]
The problem here is that Prokka doesn't support any spliced features.  So even if we found them, I wouldn't be able to annotate them as ```join(A..B,C..D)```.

**Comment by sjackman** [comment]
Right. Of course.
