### ISSUE TITLE
Aragorn circular vs linear

### ISSUE THREAD

**Issue by sjackman** [tseemann/prokka#108]
Aragorn has an option to specify whether the sequence topology is circular or linear. The default is circular. Should prokka set the topology to linear if the assembled contigs don't represent a single complete circular sequence? This probably doesn't matter much in practice.

```
    -c            Assume that each sequence has a circular
                  topology. Search wraps around each end.
                  Default setting.
    -l            Assume that each sequence has a linear
                  topology. Search does not wrap.
```

**Comment by sjackman** [comment]
Is this code due to working around the circular topology feature of aragorn?
https://github.com/tseemann/prokka/blob/master/bin/prokka#L475-L483
```
    # bug fix for aragorn when revcom trna ends at start of contig!
  #  if (defined $revcom and $start > $end) { 
  #    msg("Activating kludge for Aragorn bug for tRNA end at contig start");
  #    $start = 1;
  #  }
    if ($start > $end) {
      msg("tRNA $x[2] has start($start) > end ($end) - skipping.");
      next;
    }
```

**Comment by tseemann** [comment]
Thanks for the pointer!
