### ISSUE TITLE
crispr sequences

### ISSUE THREAD

**Issue by rasmusmarvig** [tseemann/prokka#109]
Hi,

I think that Prokka is a great program and I have been using it a lot lately. However, I think that prokka have problems handling crispr sequences.

I have run prokka with the following settings:
prokka --compliant --centre=GM --cpus 16  --genus Pseudomonas --species aeruginosa --usegenus --locustag PA_

All my genes have locus tags starting with "PA_", EXCEPT genes that are crispr sequences. 
These start with ">gnl|GM|PA_".

Question 1: Why is it so that these genes start with ">gnl|GM|PA_"?

Furthermore, for the crispr genes prokka outputs two genes with the same name but different sequences. For example:
grep PA_178_contig000091 ../annotation/annotation_178/178.ffn 
>gnl|GM|PA_178_contig000091
>gnl|GM|PA_178_contig000091

Question 2: Why does prokka give the same name to different genes?

Thanks for your help.

**Comment by tseemann** [comment]
@rasmusmarvig Thank you for letting me know of your problem with Prokka.

1. CRISPR features are annotated as /rpt_family and do not go into the .ffn file.

2. The /gene tag does not have to be unique. Sometimes you get paralogs. Latest versions of Prokka ass _1 and _2 suffix to duplicates now.

I think you might be using an old version of Prokka. What does ```prokka --version``` say?

**Comment by tseemann** [comment]
No further response, closing issue.
