### ISSUE TITLE
Also add mRNA and exon features with --addgenes 

### ISSUE THREAD

**Issue by sjackman** [tseemann/prokka#110]
The typical hierarchy of a coding GFF3 gene is
gene -> mRNA -> exon and CDS

See [The Canonical Gene](http://www.sequenceontology.org/gff3.shtml)

**Comment by sjackman** [comment]
See also "Single exon genes" under "Pathological Cases" where it says that the exon feature is optional for single exon genes. It is not however recommended to omit the mRNA feature.
> It is not recommended to parent the CDS directly onto the gene
So, I feel the `--addgenes` option should include the `gene`, `mRNA` and `CDS` features by default.

**Comment by sjackman** [comment]
As a workaround, the following sed script adds the missing `mRNA` features.

```sh
	gsed -E '/\tCDS\t/{ \
			s/CDS/mRNA/;p; \
			s/mRNA/CDS/;s/Parent=[^;]*;//;s/ID=/Parent=/;}'
```

**Comment by tseemann** [comment]
I'm not against the idea in principle, in practice it is *not* convention in Bacterial tools to have mRNA, and certainly not exon. It should be more common with transcriptomics now to have mRNA, but gene is even harder as difficult to figure out the promoters etc.

NCBI only uses the gene + CDS model:

```
NC_007790.1     RefSeq  gene    1       996     .       +       .       ID=gene0;Name=SAUSA300_pUSA010001;Dbxref=GeneID:3912719;gbkey=Gene;locus_tag=SAUSA300_pUSA010001
NC_007790.1     RefSeq  CDS     1       996     .       +       0       ID=cds0;Name=YP_492679.1;Parent=gene0;Note=identified by match to protein family HMM PF01446;Dbxref=Genbank:YP_492679.1,GeneID:3912719;gbkey=CDS;product=replication protein;protein_id=YP_492679.1;transl_table=11
```

I guess I could add a ```--addmrna``` option. I don't want to break backward compatibility with ``--addgenes```.

**Comment by sjackman** [comment]
I'd find `--addmrna` helpful.

**Comment by tseemann** [comment]
Ok, i've included an `--addmrna` option now!

**Comment by sjackman** [comment]
Thanks, Torsten!
