### ISSUE TITLE
Long contig names result in invalid GenBank files

### ISSUE THREAD

**Issue by dparks1134** [tseemann/prokka#114]
Long contig names can cause the <code>LOCUS</code> field of a GenBank file to be invalid. For example, the following should read "B2-1_qcreads.qc.1_(paired)_contig_1092 13565 bp", but there is not space between the 2 and 1.

LOCUS       B2-1_qcreads.qc.1_(paired)_contig_109213565 bp   DNA linear
13-MAY-2015
DEFINITION  Genus species strain strain.
ACCESSION   
VERSION
KEYWORDS    .
SOURCE      Genus species
  ORGANISM  Genus species
            Unclassified.
COMMENT     Annotated using prokka 1.10 from http://www.vicbioinformatics.com.
FEATURES             Location/Qualifiers
     source          1..13565
                     /organism="Genus species"
                     /mol_type="genomic DNA"
                     /strain="strain"

**Comment by tseemann** [comment]
Prokka 1.11 has a $MAXCONTIGIDLEN variable which should prevent this happening.

You are still using 1.10 - the latest is here: http://www.vicbioinformatics.com/software.prokka.shtml
