### ISSUE TITLE
Is 20130422 the only GNU Parallel version working with Prokka?

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/prokka#115]
Hi Torsten,

the documentation on http://www.vicbioinformatics.com/software.prokka.shtml specifies "20130422" as the GNU Parallel version required to run Prokka. Is this still the case, or can other versions be used? There is an issue with Roary where Parallel is the problem, and this may be version dependent. Any thoughts?

**Comment by tseemann** [comment]
That is a *minimum* version needed (as some behavious was changed by the author).

I just checked my server and it uses 20150122 without any problem.

Are you facing this old problem?  https://github.com/tseemann/prokka/issues/41

**Comment by dutchscientist** [comment]
I think that in a previous iteration the manual said it had to be that version? My query actually is independent from Prokka, it had to do with the Roary program from Andrew Page, one of the error messages suggested the GNU Parallels version had something to do with it.

 

Anyway, glad to see there is flexibility, Prokka runs well on my machines now so no need to change it. Query can be be closed :-)

**Comment by tseemann** [comment]
OK - my documentation may be out of date, but Prokka checks for MINVER and MAXVER allowed for all the software when you run it, and Parallel only has MINVER.

**Comment by dutchscientist** [comment]
Thanks :)
