### ISSUE TITLE
Does prokka skip 'N's?

### ISSUE THREAD

**Issue by kwongj** [tseemann/prokka#116]
I have a sequence around 100k bp in length, but buffered at both ends with 'N's' so the total length of the sequence is 2.8 Mbp. Prokka gets stuck "searching for CRISPR repeats", and though it still finishes, takes >10x as long as annotating a 2.8 Mbp sequence with no Ns.

**Comment by tseemann** [comment]
It's "minced" which is the problem. I've filed it upstream: https://github.com/ctSkennerton/minced/issues/8

**Comment by tseemann** [comment]
I have updated the bundled minced and the homebrew one https://github.com/Homebrew/homebrew-science/pull/3066 but you need Java 1.8 due to https://github.com/ctSkennerton/minced/issues/12
