### ISSUE TITLE
Method of identifying dependency version numbers can't deal with colorized grep output

### ISSUE THREAD

**Issue by nmcnulty** [tseemann/prokka#117]
When you define the GETVER command for each prokka dependency, you often rely on grep to match a particular string (containing the software version number) from the program's introductory output. For users like me who use colorized grep by default (i.e., have a line something like "export GREP_OPTIONS='--color=always'" in their bash profile), this creates a difficult-to-diagnose problem: the string returned by grep will contain additional control characters not present in the original text that wreak havoc on the subsequent REGEX statements. As a result, users who use colorized grep by default will get cryptic errors when it comes time to check the version number for a given dependency (usually the version number will be undefined because the REGEX failed due to the control characters).

To avoid this kind of problem, consider tweaking the GETVER definitions to include grep's "--color=never" option. Could save folks who default to colorized grep output a fair bit of head scratching.

**Comment by tseemann** [comment]
@nmcnulty Nathan - thanks for letting me know about this!  I can imagine it was a tricky one to diagnose. I solved it by deleting the GREP_OPTIONS variable from the Perl script. This won't affect the user's shell.
Ultimately I will replace it with pure Perl. Thanks again!
