### ISSUE TITLE
Contig ID Minimum Length

### ISSUE THREAD

**Issue by danielfortin86** [tseemann/prokka#118]
I frequently generate contigs with names longer than 20 characters long. When running these through prokka, prokka complains that these contig names must have names shorter than 20 characters long. I can of course rename these contigs and have a separate file allowing mapping back to the original names, but can this limitation be fixed?

**Comment by tseemann** [comment]
You can change the $MAXCONTIGIDLEN variable at the top of the bin/prokka script.

But be aware that it won't generate valid Genbank files if you do so.
