### ISSUE TITLE
Parent tag incorrectly put in .TBL file

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#119]
Email from Yu Wan:

```
1. The qualifier "Parent" in the tbl file:
>Feature scf3
3507	160	CDS
			Parent	PROKKA_00001_gene
			inference	ab initio prediction:Prodigal:2.6
			inference	similar to AA sequence:Db11.faa:SMDB11_RS22305
			locus_tag	PROKKA_00001
			product	mechanosensitive channel protein
3507	160	gene
			locus_tag	PROKKA_00001
```

**Comment by wanyuac** [comment]
Thanks Torsten for your revision. The qualifier "Parent" is not supported by GenBank anymore. Therefore, tbl2asn 24.2 reports an error about it in its discrepancy report.

**Comment by tseemann** [comment]
The Parent tag was **never** supported by Genbank. It is a GFF tag which I added but did not correctly filter out before passing to tbl2asn.

**Comment by wanyuac** [comment]
Right. Thanks!
