### ISSUE TITLE
Would Prokka add "protein_id" qualifier to the annotation?

### ISSUE THREAD

**Issue by wanyuac** [tseemann/prokka#121]
Hi Torsten

NCBI now requires every submitter to add protein_id's for all proteins (http://www.ncbi.nlm.nih.gov/genbank/genomesubmit_annotation/#protein_id). A protein_id must have the format gnl|dbname|string, where "string" is recommended to be the locus_tag.

It would be great helpful if Prokka can add protein_id's in the annotation, although we can do this using BioPython. The feature table (.tbl) should look like this:

3507	160	CDS
			locus_tag	AB868_00001
			inference	ab initio prediction:Prodigal:2.6
			inference	similar to AA sequence:Db11.faa:SMDB11_RS22305
			product	mechanosensitive channel protein
			protein_id	gnl|HoltUOM|AB868_00001 

Appendix: the email from GenBank

From: <genomes@ncbi.nlm.nih.gov>
Date: 17 June 2015 03:57:23 GMT+10
To: <kholt@unimelb.edu.au>
Subject: Inquiry Serratia marcescens subsp. marcescens AH0650_Sm1 (SUB977158 ; BioSample SAMN03769462)

Dear Kathryn Holt,

We are currently processing your WGS submission for:

SUBID         BioProject    BioSample    Organism
---------------------------------------------------
SUB977158    PRJNA286707    SAMN03769462    Serratia marcescens subsp. marcescens AH0650_Sm1

And have come across the following issues which require your attention.
...
[3] protein_id's were not included on your CDS features.  Please see
the WGS prokaryotic annotation guidelines to format your protein_id's
correctly at  http://www.ncbi.nlm.nih.gov/Genbank/genomesubmit_annotation.html 
...
Sincerely,

Linda Frisse, PhD

*******************************************************************
The GenBank Submissions Staff
Bethesda, Maryland USA
genomes@ncbi.nlm.nih.gov (replies/submission for WGS or complete genomes)
*******************************************************************

**Comment by aleimba** [comment]
Hi @wanyuac,
I've never submitted a TBL/SQN file from Prokka directly to NCBI, but I'm pretty sure Prokka includes protein_id's for all CDS features. Actually, protein_id's have been a requirement for a long time.

Have you used Prokka's option **--centre [X]** and **--compliant**?

If that doesn't help, as a workaround for you, you can use: https://github.com/aleimba/bac-genomics-scripts/tree/master/tbl2tab
Convert the TBL file to TAB-separated and back to TBL.

HTH,
Andreas

**Comment by tseemann** [comment]
@wanyuac In the email I sent you yesterday I said that Prokka already adds protein_id features for all CDS in --compliant mode in the format you said.

Are you using Prokka 1.11 or an older version?

**Comment by tseemann** [comment]
@wanyuac 
```inference similar to AA sequence:Db11.faa:SMDB11_RS22305```
will NOT be accepted by Genbank either. 

This is a result of the --proteins/--hmms options. You will need to ```grep -v Db11.faa output.tbl``` and run tbl2asn yourself again.  

I've added it as an Issue:  https://github.com/tseemann/prokka/issues/122
