### ISSUE TITLE
Don't put --proteins anno sources in /inference tag

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#122]
```inference similar to AA sequence:Db11.faa:SMDB11_RS22305```

is useful for home annotation, but not for NCBI submission.

**Comment by jbadomics** [comment]
When using --proteins (with or without --compliant) some CDS have a second inference qualifier that looks like:

     /inference="similar to AA sequence:NC_020990.faa:gi|478689038|ref|YP_007745848.1|"

However, based on a recent email from GenBank staff, NCBI wants that inference string to look like this:

     /inference="similar to AA sequence:RefSeq:YP_007746037.1"

Simply removing the second /inference qualifier seems like overkill. Can Prokka be updated to get this /inference qualifier into compliance? This is more a minor enhancement suggestion than a bug fix, though :)

NCBI *will* accept the additional /inference qualifier if formatted properly - I just had a genome accepted earlier today where that was the case

If anyone stumbles across this thread, I have a script [here](https://github.com/jbadomics/genbank_submit/blob/master/fix_inference.py) which will fix the inference strings - you have to modify the script to your needs to match the first two letters in the accession, though.

**Comment by tseemann** [comment]
@jbadomics thanks for the feedback about NCBI accepting the `/inference` tag.  I'm told that ENA just strips it - such a waste of audit trail :(

Your script / method is fine, but I'm not sure all Refseq proteins are `YP_` or that all `YP_` are in Refseq.

**Comment by tseemann** [comment]
I think handling this properly might have to wait until Prokka 2.0.

I've added new feature where `--compliant` won't use `/inference` tags for `--proteins` or `--hmms` annotations.
