### ISSUE TITLE
similarity-based prediction

### ISSUE THREAD

**Issue by haruosuz** [tseemann/prokka#123]
Could I perform similarity-based prediction in Prokka? For small viral genomes, a similarity-based gene prediction may perform better than an ab initio gene finding. 

In Prokka ChangeLog "v1.5 - 9 Sep 2012 * removed --coverage option which wasn't being used/honoured" (https://raw.githubusercontent.com/Victorian-Bioinformatics-Consortium/prokka/master/doc/ChangeLog.txt), does "coverage" indicate % query coverage (aligned sequence length coverage of a query sequence) in BLAST search?

**Comment by tseemann** [comment]
Question 1: No - sorry, Prokka wasn't designed to do protein:genome alignment based prediction.

Question 2: Yes that was what was intended, and it may come back one day.
