### ISSUE TITLE
Phase field 8 should be `.` for non-coding RNA features

### ISSUE THREAD

**Issue by sjackman** [tseemann/prokka#129]
I believe the phase field should be `.` rather than `0` for non-coding RNA features. I'm afraid that I don't have a good reference for this, other than

> Undefined fields are replaced with the "." character, as described in the original GFF spec.
…
> The phase is REQUIRED for all CDS features.

http://www.sequenceontology.org/gff3.shtml

**Comment by tseemann** [comment]
I've "solved" this by just putting phase=0 for all CDS features, and phase="." for everything else.
