### ISSUE TITLE
[bug] SignalP 4.1 adds signal sequences as separate gene in *.ffn file

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/prokka#133]
I have added SignalP (v4) to my Prokka install, and this works fine with one exception.If used for annotation, then the FFN-file contains separate entries for the signal sequence, but not a unique identifier, just the contig name. This is problematic for downstream analyses such as proteinortho5, and these entries should not be in the final FFN file?

At the moment I would not use SIgnalP because of this issue, but would like to have the option :)

**Comment by tseemann** [comment]
@dutchscientist Good pickup! I have fixed this bug now. The FFN will only have CDS, tRNA, rRNA, tmRNA and misc_RNA now.

**Comment by dutchscientist** [comment]
Hi Torsten, 

 

the new Prokka works fine (have not tested the SignalP yet), but the Minced version included crashes on Java. I put the old one back in and that works.
