### ISSUE TITLE
contig numbering interferes with large contigs 

### ISSUE THREAD

**Issue by VidJa** [tseemann/prokka#134]
I have a PacBio assembly with just a few large contigs. The contig numbering seems to interfere with in het LOCUS_TAG line if they are >1000000nt giving problems in biopython : AssertionError: Name and length collide in the LOCUS line:
I've used --centre and --compliant, running on 'master'

first contig size(8774294nt)
LOCUS       STRAC4A2_contig0000018774294 bp    DNA     linear       30-JUL-2015
...
//
LOCUS       STRAC4A2_contig000002  86441 bp    DNA     linear       30-JUL-2015
...
//
LOCUS       STRAC4A2_contig000003 150207 bp    DNA     linear       30-JUL-2015

**Comment by kwongj** [comment]
Try:
$ sed -e 's/\(contig000...\)\(\w.* bp\)/\1\t \2/g' [contigs.gbk] > corrected.gbk

**Comment by tseemann** [comment]
The latest github version uses fewer digits and gets rid of the `contig` part.

This should help.
