### ISSUE TITLE
Alternative Genetic Code

### ISSUE THREAD

**Issue by owenoutlaw** [tseemann/prokka#137]
Greetings, 

Is there a way to implement an alternative genetic code, specifically for Candidate Division SR1 and Gracilibacteria Code (transl_table=25), which use UGA for glycine? I attempted to implement the alternative code using the flag --gcode 25 but I receive error messages. Thanks a bunch!!

--------------------- WARNING ---------------------
MSG: Not a valid codon table ID [25] 
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Seq [PROKKA_00825]: Terminator codon inside CDS!
---------------------------------------------------

**Comment by tseemann** [comment]
You need to upgrade your BioPerl installation.
