### ISSUE TITLE
A problem running prokka with rnammer

### ISSUE THREAD

**Issue by JohnYu-yuzhongyi** [tseemann/prokka#138]
Hi I'm trying to run Prokka 1.11 with the rnammer option. But an error comes out when prokka is running rnammer:

[17:02:38] Running: rnammer -S bac -multi -xml test1\/rnammer\.xml test1\/PROKKA_11032015\.fna

Could not open file './85633.tsu.xml' for reading:No such file or directory
[17:02:42] Could not run command: rnammer -S bac -multi -xml test1\/rnammer\.xml test1\/PROKKA_11032015\.fna

I can't find anything online of someone having the same problem.

I think it might be because my rnammer or hmmer is not properly installed because in the manual of rnammer it says I can run a test 
perl rnammer -S bac -m lsu,ssu,tsu -gff - < example/ecoli.fsa
But when I run it, it doesn't give any result, although it doesn't give any error either.

I'm not sure what should I do to fix this issue?

Thanks!

**Comment by tseemann** [comment]
This is not really a problem with Prokka. Your `rnammer` is not working. 

Have you read this?
 https://github.com/tseemann/prokka#option-3---rnammer
