### ISSUE TITLE
--compliant and --centre arguments ignored: Contig ID too long

### ISSUE THREAD

**Issue by jvollme** [tseemann/prokka#141]
Hello,
I'm currently using prokka 1.11. When I run prokka with a recent assembly, I keep getting the error message "Contig ID must <= 20 chars long:"

I've tried using the "--compliant" argument but nothing changed. 
I've also renamed and shortened all contig fasta header to only 2 characters length, but this also did not help (and prokka seems to rename all of the contigs regardless.
The problem seems to be that prokka automatically renames the contigs into too long names. Also apparently all dsefault values of proka seem to be too long for this.

Here is the error message when I use the ``--compliant`` argument:
``Contig ID must <= 20 chars long: gnl|Prokka|PROKKA_contig000001``
here is the error message when I uste the ``--compliant`` and ``locus_tag "W"`` argument
``Contig ID must <= 20 chars long: gnl|Prokka|W_contig000001``
here is what happens when I additionally set the ``--centre "W"`` :
``Contig ID must <= 20 chars long: gnl|W|PROKKA_contig000001``
trying to set the "centre" to an empty string will automatically set it to "PROKKA":
``Contig ID must <= 20 chars long: gnl|Prokka|PROKKA_contig000001``
I can only get this partly to work by omitting the "--compliant" argument and setting "locus_tag" and "centre" to single characters (``--centre X --locus_tag X``). Only in that case will the prokka-generated string end up with EXACTLY 20 characters ("gnl|X|X_contig000001")

I did not have this problem with earlier versions of prokka.
Also it would be nice to have an option not to let Prokka rename the contigs (at least if the names are already short enough not to interfere with tbl2asn)

**Comment by aleimba** [comment]
Hi John,

this has been a longer standing issue, see e.g. #76 and #135.

If you don't care about correct GENBANKs (from tbl2asn) at all you can just increase the integer in the constant variable $MAXCONTIGIDLEN in the `bin/prokka` main script and Prokka won't quit with an error anymore.

HTH,
Andreas

**Comment by jvollme** [comment]
Thanks,
Do you also have a trick to prevent prokka from renaming the contigs?

**Comment by aleimba** [comment]
I just had a short look. I think if you don't set `--compliant` and `--centre` contig names should stay as they are. But I haven't tried it.

**Comment by jvollme** [comment]
Thanks, that was it. Somehow I kept setting at least one of those (or both). By setting none of them, everything works as I'm used to with the older Versions. So the only thing that is not working is the direct generation of NCBI-compliant genbanks which I don't really need anyway.
