### ISSUE TITLE
Adding hmms for annotation

### ISSUE THREAD

**Issue by ecastron** [tseemann/prokka#142]
Dear @tseemann 

I'd like to use the Unifam database [PMID: 25293379](http://www.ncbi.nlm.nih.gov/pubmed/25293379) to annotate my genomes in Prokka using either the -hmm or -setupdb options. The developers of Unifam provide binary compressed hmmer files as

prok.hmm.h3m
prok.hmm.h3i
prok.hmm.h3f
prok.hmm.h3p

However, I don't have a prok.hmm file and Prokka won't work with the binary files only. I searched the documentation of hmmer and unifam with no success. I couldn't find a program to do the opposite than hmmpress either.

Do you have any idea of how could I use unifam in Prokka?

Any help is appreciated,

Thanks

Eduardo

**Comment by tseemann** [comment]
Eduardo

There was a bug in Prokka which made the `--hmms` option fail if you didn't have the ASCII version of the HMM database. You don't *need* it, so I have fixed the bug. You will need to update your Prokka from github. You will have to use the parameter like this: `--hmm /path/to/proka.hmm`. It will check for the `prok.hmm.h3i` file now.

**OR**

You can produced the `prok.hmm` file using `hmmcovert -a prok.hmm > proka.hmm`

Thank you for reporting this bug!

Torsten

**Comment by ecastron** [comment]
Dear Torsten,

Thanks for your reply and for enabling Prokka to use the binary pressed files. I gave it a try and its working like a charm!.

Take care,

@ecastron
