### ISSUE TITLE
messages indicating "success" or "failure"

### ISSUE THREAD

**Issue by haruosuz** [tseemann/prokka#144]

**Comment by tseemann** [comment]
@haruosuz Can you please explain more?

**Comment by haruosuz** [comment]
Sorry, I failed to delete it.

I thought a single message like "finished successfully" better than 
msg($walltime % 2 ? "Share and enjoy!" : "Thank you, come again.”);

**Comment by tseemann** [comment]
Ok, just before the timing stats etc I wrote *Annotation completed successfully*.
