### ISSUE TITLE
tRNA, rRNA, CDS inference

### ISSUE THREAD

**Issue by haruosuz** [tseemann/prokka#147]
- tRNA
  Aragorn:1.2 identified tRNA-Ser (anticodon; CAG), which should be tRNA-Leu (http://www.ddbj.nig.ac.jp/sub/geneticcode-e.html#11).
  It would be great if we could choose tRNAscan-SE as well as Aragorn in prokka.
- rRNA
  Can prokka add "<" to indicate partial sequence of "16S ribosomal RNA" predicted by RNAmmer:1.2 as follows?
      rRNA    1..908  inference   profile:RNAmmer:1.2
              ↓
      rRNA    <1..908 inference   profile:RNAmmer:1.2
- CDS inference
  What does "PRK" stand for (database?) in the following line?
      inference   protein motif:CLUSTERS:PRK00024

**Comment by mherold1** [comment]
PRK00024 is an identifier from "Curated Prokaryotic Protein Clusters" (the CLUSTERS.hmm in prokka)
http://www.ncbi.nlm.nih.gov/books/NBK3797/

**Comment by haruosuz** [comment]
Thank you for your comments.
http://www.ncbi.nlm.nih.gov/Structure/cdd/cddsrv.cgi?uid=235446
http://www.insdc.org/documents/inference-qualifiers
Because "CLUSTERS" is not a valid database name,
inference	protein motif:CLUSTERS:PRK00024
should be
inference	protein motif:CDD:PRK00024

**Comment by mjcoyne** [comment]
What does "PRK" stand for (database?) in the following line?

PRK stands for "PRotein K(c)lusters", an Entrez database.

**Comment by ealdraed** [comment]
@haruosuz I had a look at the problem with the wrong tRNA for anticodon CAG (Ser instead of Leu, interesting find btw ;)). It seems that the amino acid map for the Genetic Code 11 is wrong. I think you can fix this by editing line 1441 of aragorn1.2.36.c and compiling it:

`Leu,Val,Ser,Met,` shoud read `Leu,Val,Leu,Met,`. I e-mailed the authors with a link to this issue.

As a workaround, you can instead edit Prokka lines 278 and 284 (v.1.11) and change `$gcode ||= 11;` to `$gcode ||= '11,CTG=Leu';`.

**Comment by tseemann** [comment]
@haruosuz In the future can you please make 1 issue for each question?
@mjcoyne thank you for helping answer questions
@ealdraed wow - great bug pickup! it is concerning this has existed for so long.

1. I have filed a request for you here: https://github.com/tseemann/prokka/issues/168

2. How does `rnammer` present partial rRNA in the output XML file? 
Prokka wasn't designed to support "fuzzy" lcoations.

3. @haruosuz The site http://www.insdc.org/documents/inference-qualifiers says those names are *recommended*. That does not mean that other names are *illegal* ?

**Comment by ealdraed** [comment]
@tseemann I forgot to mention that I got an answer from one of the authors (Dean) and a copy of the latest source code (1.2.37). It seems that @haruosuz was already in contact and they knew about the bug.

I just wanted you to know, that Aragorn was officially updated 5 days ago and this update also includes the fix:

http://mbio-serv2.mbioekol.lu.se/ARAGORN/Downloads/

Maybe a good time for a Prokka update?! ;)

**Comment by ealdraed** [comment]
@tseemann Just to follow up on this: Would you mind to update the binaries of aragorn in the repository (current version is now 1.2.38). prokka prefers an already installed version, but I guess many people might use the contained version and will get a wrong annotation.

I know, it is "just" a tRNA, but those errors propagate to the public databases. Thank you and best regards!
