### ISSUE TITLE
Too many 'hmmsearchresult' files

### ISSUE THREAD

**Issue by damonti0406** [tseemann/prokka#151]
I found an enormous list of 'hmmsearchresult' files. Apparently, the program crashed because of RNAmmer. How can I fix this? Here the last chunk of the log file. 

`[12:17:37] Found 700 tRNAs`
`[12:17:37] Predicting Ribosomal RNAs`
`[12:17:37] Running RNAmmer`
`[12:17:37] Running: rnammer -S bac -multi -xml annotation\/rnammer\.xml annotation\/PooledAssembly\.fna`
`sh: ./100000008333799858.106206.pos.fsa.hmmsearchresult: Too many links`
`sh: ./100000009082827238.113777.neg.fsa.hmmsearchresult: Too many links`
`[16:18:30] Could not run command: rnammer -S bac -multi -xml annotation\/rnammer\.xml annotation\/PooledAssembly\.fna`

`real    243m30.098s`
`user    40m41.267s`
`sys     417m18.682s`

**Comment by tseemann** [comment]
Well I have never seen that error before!

My suggestion is to not use rnammer. Install barrnap instead, and it will use that: https://github.com/tseemann/barrnap

(I am not able to debug rnammer - and it also it complicated to install as it depends on a legacy version of HMMER 2.x)

**Comment by abremges** [comment]
Happened to me a couple of times when I tried to annotate rather big metagenome assemblies. Too many files in one directory for Unix to handle (couldn't even `rm -rf *hmmsearchresult`, but had to use the `find` workaround instead).

Thus, another way to handle this is to split your input into multiple files, and run Prokka in separate directories, and then merge the results.

**Comment by tseemann** [comment]
@abremges - good tip! would work better on cluster too.

@damonti0406 - I can't really solve rnammer issues, or fundamental Unix process/shell limits.
