### ISSUE TITLE
Set the locus tag/prefix to be something unique

### ISSUE THREAD

**Issue by andrewjpage** [tseemann/prokka#156]
Set the locus tag/prefix to be something unique rather than PROKKA. 
As previously discussed, take an MD5 of the assembly, and use the first bit of it. That way if the same assembly is reannoated, the gene IDs will be the same.

**Comment by tseemann** [comment]
@andrewjpage I decided to take first 8 chars of md5sum of contigs file, and replaced numerals with letters offset from 'G' , and leave hex lettera A to F as-is.
