### ISSUE TITLE
 Could not run command: cmpress

### ISSUE THREAD

**Issue by bretonics** [tseemann/prokka#157]
`prokka --setupdb` results in cmpress: command not found. What is this?

**Comment by tseemann** [comment]
`cmpress` is part of the infernal package for finding the small RNAs with the `--rfam` option.

I include the Linux and Mac binaries in the prokka `binaries/` folder - I am not sure why it can't find them?

**Comment by bretonics** [comment]
Aha, I see. Well that directory is not sourced (even when exporting $PATH `export PATH=$PATH:$HOME/prokka-1.11/bin`)

Just symlinked those executable in `/binaries/linux/` into my `/usr/local/bin`.

I had installed **hmmer** locally previously when it failed at that point. Did not know you had included all these already under `/binaries/linux/`.

`prokka --setupdb` now works.

**Comment by tseemann** [comment]
That's strange - Prokka is meant to add those binaries folders to the end of the `PATH` when it runs so it automatically finds them.

Are you using the latest Prokka from github HEAD ?

**Comment by bretonics** [comment]
I `git clone https://github.com/tseemann/prokka.git`, which gives me version `prokka 1.12-beta`

I must admit that I originally symlinked the `bin/` content, which as originally stated, did not find cmpress when running; though I tested with `export PATH=$PATH:$HOME/prokka/bin` (yes, `prokka` is where it resides, **not** `prokka-1.11`)  and as mentioned, it wouldn't source the binaries. I don't think this would even be an issues since you are using `$FindBin::RealBin`.

Hope it helps clarify.

**Comment by rafalcode** [comment]
in the prokka executable, the setting of PATH comes at line 361 which is after some options have been detected and executed. Solution is to raise in the sequence of calls to before the option-detection.

**Comment by tseemann** [comment]
@rafalcode good point! there is a problem there. i'll make a new issue #160
