### ISSUE TITLE
SignalP fails with >10,000 sequences

### ISSUE THREAD

**Issue by embatty** [tseemann/prokka#158]
SignalP has a limit of 10,000 sequences and fails with the error message:
``# Sequence limit reached: Max 10000 sequences are allowed`` 

If you give Prokka a sequence with more than 10,000 coding sequences the SignalP step fails silently and it reports 0 signal peptides.

**Comment by tseemann** [comment]
Clearly your bacterium is too big (or fragmented).
I admit I don't run with `signalp` much these days.

What behaviour should prokka take if it finda 10,000 genes?
Should it die instead of running signalp?

**Comment by embatty** [comment]
Yes, these are really fragmented assemblies which is why they have a ridiculous number of genes... It would be neat if Prokka caught the SignalP error and gave a warning but continued the run, then I know it failed to run rather than having 0 signal peptides in my genome as a real result.

**Comment by tseemann** [comment]
@embatty I now check if no. seq > 10,000 and don't run signalp in that case. not the best solution but at least doesn't kill your job.

other option is to simply not use `--gram` option.
