### ISSUE TITLE
Visualization of Output 

### ISSUE THREAD

**Issue by samikbagchi** [tseemann/prokka#159]
Hello, 

I'm newbie in metagenomic data analysis. I have used prokka to annoate my contigs and want to see the protein abundance (.faa) and functional distribution of the genes. which will be the best visualization pipeline to use prokka output. 

Thank you.

**Comment by tseemann** [comment]
I don't know what tool to use for what you want.  You'll probably need more than just Prokka annotations to group into functional clusters. Sorry!
