### ISSUE TITLE
Prokka crash

### ISSUE THREAD

**Issue by ohthetrees** [tseemann/prokka#161]
I'm experiencing a crash. Any help would be much appreciated.

```
%prokka -v
prokka 1.12-beta
% prokka --prefix groups --cpus 0 --norrna --notrna --outdir prokka_knot --force contigs.name.fasta
[snip]
[01:36:12] Modify product: Probable glycine dehydrogenase (decarboxylating) subunit 2 => putative glycine dehydrogenase (decarboxylating) subunit 2
[01:36:12] Modify product: Probable glycine dehydrogenase (decarboxylating) subunit 1 => putative glycine dehydrogenase (decarboxylating) subunit 1
[01:36:13] Modify product: Probable peptidoglycan endopeptidase LytE => putative peptidoglycan endopeptidase LytE
[01:36:13] Modify product: Probable GTP-binding protein EngB => putative GTP-binding protein EngB
[01:36:13] Modify product: Putative heme-dependent peroxidase GK3416 => Putative heme-dependent peroxidase

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: no data for midline    0.320    0.137    0.417    0.792     4.96 
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:486
STACK: Bio::SearchIO::blast::next_result /usr/share/perl5/Bio/SearchIO/blast.pm:1923
STACK: /usr/local/prokka/bin/prokka:1005
-----------------------------------------------------------
```

`contigs.name.fasta` is 1.3GB and contains 1112903 contigs. The machine is a AWS r3.8xlarge (32cpu and 240GB ram).

**Comment by tseemann** [comment]
The error seems to be a broken BLAST report produced by `blastp`, or a bug in the `Bio::SearchIO::blast` module.

The `no data for midline` I think refers to the `|  |||| | |||` match line between query and subject in a standard BLAST report.  Given the millions of proteins we are feeding it, maybe something has gone wrong.

What version of BLAST+ are you using?

**Comment by ohthetrees** [comment]
Sorry for the slow reply.

blastp -version
blastp: 2.2.28+
Package: blast 2.2.28, build Jun  3 2013 11:17:14


best,
Cedar

**Comment by tseemann** [comment]
We're up to 2.3.0 now, but I think the issue might be an old version of Bioperl perhaps?

```
perl -MBio::Perl -e 'print "$Bio::Root::Version::VERSION\n";'
```

**Comment by tseemann** [comment]
I'll assume you solved the problem. Re-open if needed.

**Comment by carissableker** [comment]
I had a similar error when running multiple prokka tasks at the same time with the same output folder but different prefixes. The issue was that each task created/used the file `Escherichia.blast` in the output folder, and I assume this caused clobbering. 

My fix was to make separate output folders for each of my tasks and move the results over after. A real fix would be to have prokka make unique files names.

**Comment by tseemann** [comment]
@carissableker yes i don't think Prokka will like you using the same `--outdir` for different runs at the same time. Can you file this is a separate issue please? It isn't really the same problem as here.
