### ISSUE TITLE
Seq doesn't validate

### ISSUE THREAD

**Issue by alex-b-chase** [tseemann/prokka#163]
Trying to run Prokka on some isolates and had some issues with them. So, I tried analyzing another genome from here (curl -O http://athyra.idyll.org/~t/ecoli-v41.fa)  to see if that would work. Both cases result in:

>[14:44:14] Predicting coding sequences
[14:44:14] Contigs total 5843834 bp, so using single mode
[14:44:14] Running: prodigal -i ecoli0104\/ecoli0104\.fna -c -m -g 11 -p single -f sco -q
[14:44:23] Excluding CDS which overlaps existing RNA (rRNA) at gnl|CDC|PROKKA_contig000086:1149..1403 on + strand
[14:44:23] Excluding CDS which overlaps existing RNA (tRNA) at gnl|CDC|PROKKA_contig000095:88149..88394 on - strand
[14:44:25] Excluding CDS which overlaps existing RNA (tRNA) at gnl|CDC|PROKKA_contig000156:2623..2844 on - strand
[14:44:25] Excluding CDS which overlaps existing RNA (tRNA) at gnl|CDC|PROKKA_contig000167:12333..12935 on + strand
[14:44:26] Excluding CDS which overlaps existing RNA (tRNA) at gnl|CDC|PROKKA_contig000174:16167..16613 on + strand
[14:44:27] Found 5658 CDS
[14:44:27] Connecting features back to sequences
[14:44:27] Not using genus-specific database. Try --usegenus to enable it.
[14:44:27] Annotating CDS, please be patient.
[14:44:27] Will use 4 CPUs for similarity searching.

>-------------------- WARNING ---------------------
MSG: seq doesn't validate, mismatch is 1

>------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Attempting to set the sequence to [MARRIADLGHEAKLISPQFVRPFVKSNKNDFVDAEAICEAASRPSMRFVQPRTEAQQAMRALHRVRESLVSDKVKTTNQMHAFLLEFGISMPTGVAVVKRLSTVLAENELPPYLAQLLMRLHAHYIYLVGQITELEIALEQELSRDEVGQRLQTIPGIGPITASVLSSQLGGGKQYSCSRDFAASTGLVPRQYSTGGKNTLLGISKRGDKNLRRLLVQCARSFIQRIENQSGRLADWVRALLARKHSSVVCCALANKLARIAWAITTQQTVFER-codontable_id] which does not look healthy
STACK: Error::throw
STACK: Bio::Root::Root::throw /Library/Perl/5.18/Bio/Root/Root.pm:328
STACK: Bio::PrimarySeq::seq /Library/Perl/5.18/Bio/PrimarySeq.pm:268
STACK: Bio::PrimarySeq::new /Library/Perl/5.18/Bio/PrimarySeq.pm:217
STACK: Bio::Seq::new /Library/Perl/5.18/Bio/Seq.pm:498
STACK: Bio::PrimarySeqI::translate /Library/Perl/5.18/Bio/PrimarySeqI.pm:592
STACK: /Users/Chase/prokka-1.11/bin/prokka:950

Ran the following
> prokka ecoli-v41.fa --outdir ecoli0104 --prefix ecoli0104 --force --centre CDC

> prokka --version
prokka 1.11

**Comment by tseemann** [comment]
It seems one of the protein sequences it has encountered has a gap "-" at the end, and Bioperl is (rightly) complaining! It's not clear how a gap got in there.

I just ran your example file on Prokka 1.12b from github (as Prokka 1.11 is very old now) and it runs correctly. Are you able to install it? Instructions here: https://github.com/tseemann/prokka#github

**Comment by alex-b-chase** [comment]
@tseemann 

Thanks for the response. I installed the newest version and have it up and running. 

Just tried rerunning the same genome from above, and same error. Maybe it has to do with bioperl version? Not sure...

I updated Infernal and BLAST so far.

Gonna try and update that and let you know if it works or not.

**Comment by tseemann** [comment]
What does `perl -MBio::Perl -e 'print $Bio::Perl::VERSION` say?

I'm guessing 1.006924 same as me.

Can you attach the `.LOG` file ?

**Comment by alex-b-chase** [comment]
@tseemann 

Just updated BioPerl so the version is:
>perl -MBio::Perl -e 'print $Bio::Perl::VERSION'
1.006925

Just tried running the 'vanilla' code to see if we could get it to work:
> prokka ecoli-v41.fa 

SUCCESS! Must've been the outdated BioPerl version. Not sure what I had before, but didn't think it was that outdated...

Thank you for all your help! Really looking forward to using Prokka for my isolates now!

>organism: Genus species strain 
contigs: 285
bases: 5843834
repeat_region: 2
tRNA: 77
rRNA: 4
tmRNA: 1
CDS: 5658

**Comment by tseemann** [comment]
Great! Looks like I need to upgrade Bioperl too now!

**Comment by cjfields** [comment]
@tseemann yep, looks like we need another CPAN release?

**Comment by tseemann** [comment]
@cjfields Prokka has worked fine with every Bioperl release since 1.006002 and I even check for it in Prokka:  
`my $minbpver = "1.006002"; # for Bio::SearcIO::hmmer3`

The erro @alex-b-chase has occurred during the BLASTP parsing stage. But what could have happened is BLAST+ output could have changed at some point, and the Bioperl parser updated for it, but because I've usually kept things updated I never noticed that issue?

**Comment by cjfields** [comment]
@tseemann  there have been similar updates for hmmer3 as well, though there aren't any apparent changes in SearchIO::blast since 1.6.24.  Maybe a heisenbug?
