### ISSUE TITLE
Could not run command: sed

### ISSUE THREAD

**Issue by bretonics** [tseemann/prokka#164]
Referencing back to #127, I get the same error:

>[10:05:05] Could not run command: sed 's/COORDINATES: profile/COORDINATES:profile/' < annotation\/SD98\.gbf > annotation\/SD98\.gbk

It seems from the comments, it's due to the pipe character `|` in the fasta header. Will test and confirm if changes to `contigs.fasta` file headers affect outcome.

**Comment by tseemann** [comment]
Pipe characters are not allowed in identifiers in Genbank, as they are reserved for separating multiple ID sources.

**Comment by tseemann** [comment]
Resolved by #155
