### ISSUE TITLE
Linux prodigal binary does not work on older systems

### ISSUE THREAD

**Issue by ctSkennerton** [tseemann/prokka#166]
Our server uses RHEL6 and the latest pull of prokka resulted in an error when trying to determine the version of prodigal. When I try to run the binary by itself I get the following error:

```
/export/data1/sw/prokka/github/bin/../binaries/linux/prodigal: /lib64/libc.so.6: version `GLIBC_2.14' not found
```

Likely you compiled it on a newer system than my own which is causing a mismatch in GLIBC. Not sure if there is a good solution, maybe statically link the linux binaries so that they include GLIBC

**Comment by ctSkennerton** [comment]
Also the binary from the [prodigal github page](https://github.com/hyattpd/prodigal/releases/) for 2.6.3 works so could be easy fix to nab that binary

**Comment by tseemann** [comment]
@ctSkennerton 
Yes, the GLIBC problem is annoying, and compiling static binaries is nigh impossible these days.
I have upgraded the max and linux binaries to the ones you suggested.
They are 2.6.3 upgrade from 2.6.2 bundled too!
Thanks for the tip off!
