### ISSUE TITLE
Making a Core Database is useless?

### ISSUE THREAD

**Issue by bretonics** [tseemann/prokka#170]
So we can add a new database by making our own, at least to my understanding [here] (https://github.com/tseemann/prokka#making-a-core-databases), yet how does that help when we are limited to the default [hard-coded options] (https://github.com/tseemann/prokka/blob/master/bin/prokka#L271)? 

Maybe I am not understanding what you meant, but I gathered I could download any [Uniprot database] (ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/) and make a new core database using `prokka-uniprot_to_fasta_db` and adding it as a new kingdom in `/opt/prokka/db/kingdom/`. That's also suggested in some other issues I sifted through.

Say I added a 'Fungi' directory under `/opt/prokka/db/kingdom/` and created the database files there. I know, it's not suppose to be for Eukarotic annotations, but ...I even cleaning and re-indexing the databases, even when the new 'Fungi' database is recognized by `prokka --listdb`, I can't use it with the `--kindom` option. It croaks because of the [hard-coded default options] (https://github.com/tseemann/prokka/blob/master/bin/prokka#L303).

Thanks for any clarification.

**Comment by tseemann** [comment]
Obviously Prokka was never meant to annotate Fungi due to the euky introns etc.  The ability for viruses and mitochindria is primitive and probably shouldn't be there. The hard coding could (should) be moved to a config file.

If you want to have Fungi in, just called it `Viruses` instead and then use `--kingdom virus` etc.
