### ISSUE TITLE
For loop and 'filename' is not a readable non-empty FASTA file

### ISSUE THREAD

**Issue by TreeT2** [tseemann/prokka#176]
Hi,

Not sure if this is a bug or my bad scripting...
Ive been trying to run prokka on a HPC with a PBS and I keep getting the above error, if I run the samples individually prokka will run no problem. But I have ~60 samples so would rather use a loop. 
My PBS file is as follows:

for f in /path/contigs/*.fa; do
  f=$(basename $f .fa)
  echo "Annotating"
  prokka \
    --outdir $HOME/path/prokka/$f \
    --centre XXX --prefix $f \
    --kingdom Bacteria \
    ${f}.fa
done
 
Ive removed all space and tabs from the fasta files and removed all hyphens and underscores from the filenames with no luck.  
Thanks

**Comment by ShuyiF** [comment]
> Hi,
> 
> Not sure if this is a bug or my bad scripting... Ive been trying to run prokka on a HPC with a PBS and I keep getting the above error, if I run the samples individually prokka will run no problem. But I have ~60 samples so would rather use a loop. My PBS file is as follows:
> 
> for f in /path/contigs/*.fa; do f=$(basename $f .fa) echo "Annotating" prokka --outdir $HOME/path/prokka/$f --centre XXX --prefix $f --kingdom Bacteria ${f}.fa done
> 
> Ive removed all space and tabs from the fasta files and removed all hyphens and underscores from the filenames with no luck. Thanks

Hi! I'm wondering how you solved this problem? I met the exactly same issue...Run the prokka for individual is fine but the loop just doesn't work.
