### ISSUE TITLE
.frn file

### ISSUE THREAD

**Issue by swuyts** [tseemann/prokka#178]
Dear Torsten,

I've ran Prokka for the first time last week, and it's looking good, thanks for this!

The only extra thing that I was expecting in the output was a '.frn'-file which contains all rna coding portions of the genome segments (tRNA & rRNA). Am I missing a certain option to get this created next to the others?

Thank you,
Sander

**Comment by tseemann** [comment]
@swuyts you are correct that I don't generate this file. it is the only 'traditional' genbank one i don't create. i guess i never thought anyone would need it.  

i'll add it to the TO DO list.

may i ask what your "use case" is for the file?

**Comment by swuyts** [comment]
Thanks! 

We're would like to use the file to generate quality scores as described in this paper: "Quality scores for 32,000 genomes". It uses the amount of tRNAs and rRNAs to calculate a quality metric.

**Comment by tseemann** [comment]
@swuyts I now realise the `.ffn` file *already* had what you wanted all along!

It  has all these feature types:

`m/^(CDS|rRNA|tmRNA|tRNA|misc_RNA)$/`
