### ISSUE TITLE
Error when running prokka on files within folder with a space in the name

### ISSUE THREAD

**Issue by Cyanoney** [tseemann/prokka#182]
The script starts running but ends prematurely with exception. the last line that it reports trying to run is :

[11:52:41] Searching for CRISPR repeats
/usr/local/bioinf/prokka-1.11/bin/../binaries/linux/../common/minced: line 31: cd: /home/sls_branko/phage: No such file or directory

the folder name in which the contig files are is called "sls_branko/phage sequences/", hence the previous line. 

The Exception message I get is:

MSG: [Input file prokka_T4/SRSM61_07122016.fna does not exist.] does not look like GFF3 to me

(obviously, using spaces in folder names in linux is dumb and I know better now, but it's a mistake casual users are not so unlikely to make and it takes a long time to identify the source of the error)

**Comment by tseemann** [comment]
@Cyanoney did you run Prokka from *within* the folder or provide a full path to the contigs file?

If I do either of these it works.
```
cd "folder with spaces"
prokka contigs.fa
```
or
```
prokka "/path/to/folder with spaces/contigs.fa"
```

I am using only Prokka 1.12b from github HEAD.

Can you provide the .LOG file or explain a bit more about what caused it?

**Comment by tseemann** [comment]
No response, closing.
