### ISSUE TITLE
Make 'java' a dependency

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#185]
If java not installed, it fails at the checking the `minced` step.

**Comment by asmvernon** [comment]
Hi, I have run into this issue. I have installed Java, but it still doesn't work. I am using Mac OSX 10.11.6 (El Capitan). 
error: "Could not determine version of minced - please install version 1.6 or higher" 
Is there a way of running it without minced? I do not need the CRISPR-related output.

**Comment by tseemann** [comment]
Is the `java` command in your `PATH` ?
What does `java -version` in the Terminal say?
And what does `prokka --version` say?
Did you install prokka from github head, Brew, or old tarball?

**Comment by asmvernon** [comment]
I realised it was an error with java. Thanks for getting back to me!

**Comment by shimingt** [comment]
Hello @tseemann ,

I am facing the same issue. My java is version 1.8.0_111, and my prokka version is 1.11.

I downloaded my Prokka off github. 

Could you please advice? Thanks!

**Comment by tseemann** [comment]
Please use github HEAD version. The 1.11 "release" is *very* old.
