### ISSUE TITLE
Multiple genome analysis

### ISSUE THREAD

**Issue by lucaz88** [tseemann/prokka#187]
Hi everyone,
likely it is a silly question but I just started using prokka and I was wondering... If I have to run it on several closed bacterial genomes is it better that 1) I merge all of them in one file (giving ad-hoc labels to each contig) and run them as a single fasta file in input, or 2) I just loop the execution of prokka through each single genome fasta?
Cheers,
Luca

**Comment by cjfields** [comment]
@lucaz88 I would run them individually (the runs aren't very long).  

I'm not sure whether there may be issues re: report limitations/cutoffs (e.g. # of reported hits), but you couldn't customize naming of genes, scaffolds, etc. as the tool would think it's one genome.  Not to mention you would run into problems with some settings, like anything organism-specific.

**Comment by tseemann** [comment]
@lucaz88 I agree with @cjfields - you should annotate separately. I do this all the time. I usually have them named in a consistent manner and then write a loop like this:

```
% ls *.fasta
TS1.fasta TS2.fasta TSmut,fasta TScomp.fasta TSwt.fasta

for F in *.fasta; do 
  N=$(basename $F .fasta) ; 
  prokka --locustag $N --outdir $N --prefix $N  $F ; 
done
```

**Comment by jananiravi** [comment]
quick follow-up question, @tseemann if I just ran prokka on *.fna, would it be running prokka on the concatenated master set of fasta files/proteins? thanks!

**Comment by indrawx** [comment]
Hello, @tseemann, your pipeline for annotating genomes is very useful, thank you. But can you please share with me an idea, how to annotate more than 300 genomes (I'm working remotely on supercomputer with shell scripts) in a **for** loop, so I can see the output of each one in separate folders named same as each genome? It's hard to orientate in a such huge output...
Thanks a lot in advance!
