### ISSUE TITLE
prokka :: incompatibillity with new bioperl

### ISSUE THREAD

**Issue by EricDeveaud** [tseemann/prokka#188]
hello, 

updating bioperl from 1.006923 to 1.006924 breaks prokka 

```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'barrnap --threads 8 --quiet PROKKA_08252016/PROKKA_08252016.fna  |': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /local/gensoft2/adm/perl-5.22/lib/site_perl/5.22.0/Bio/Root/Root.pm:449
STACK: Bio::Root::IO::_initialize_io /local/gensoft2/adm/perl-5.22/lib/site_perl/5.22.0/Bio/Root/IO.pm:270
STACK: Bio::Tools::GFF::new /local/gensoft2/adm/perl-5.22/lib/site_perl/5.22.0/Bio/Tools/GFF.pm:200
STACK: /mount/gensoft2/exe/prokka/1.9/bin/prokka:475
-----------------------------------------------------------
```

as far as I understood the bioperl code this is due to the default setting of the mode in open using -file in  Bio/Root/IO.pm

bioperl 1.006923 does not set any mode 
bioperl 1.006924 set default mode  "<" (open file) if none specified (which is hte case in prokka script)
thus breaks the call to barrnap.

regards

Eric

**Comment by tseemann** [comment]
@EricDeveaud you are using a 4 year old version of prokka (1.9). I believe the file opening calls were fixed. Please upgrade to github HEAD, or use `brew install prokka --HEAD`.

**Comment by EricDeveaud** [comment]
user requested for prokka 1.9 to be able to reproduce some previous analysis 

NB. we currently provide on our cluster prokka 1.9 and 1.11
