### ISSUE TITLE
'Bad end parameter' error for prokka-genbank_to_fasta_db

### ISSUE THREAD

**Issue by MattPinder** [tseemann/prokka#192]
I've been trying to generate a new database using prokka-genbank_to_fasta_db and three GenBank files, however I am continually receiving the following error message:

Will use first of (protein_id locus_tag db_xref) as FASTA ID
^MParsing: NZ_DS544873
substr outside of string at /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/PrimarySeq.pm line 434, <> line 64722.

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Bad end parameter (4647). End must be less than the total length of sequence (total=0)
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/Root/Root.pm:449
STACK: Bio::PrimarySeq::subseq /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/PrimarySeq.pm:452
STACK: Bio::PrimarySeqI::trunc /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/PrimarySeqI.pm:458
STACK: Bio::SeqFeature::Generic::seq /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/SeqFeature/Generic.pm:705
STACK: Bio::SeqFeatureI::spliced_seq /usr/local/packages/perl-5.14.4/lib/site_perl/5.14.4/Bio/SeqFeatureI.pm:496
STACK: /usr/local/packages/prokka-1.11/bin/prokka-genbank_to_fasta_db:48
-----------------------------------------------------------

Please could you suggest where I might start troubleshooting this issue?

**Comment by tseemann** [comment]
@MattPinder i downloaded the .gbk file for NZ_DS544873 and it seemed to work fine. There are various possibilities:
1. you are using 2 year old Prokka 1.11, please upgrade to git HEAD version  
2. your GBK file is corrupt or doesn't contain sequence at the end - this can happen if you download off the web and don't choose `Genbank (Full)`.
3. Bioperl is old
