### ISSUE TITLE
SignalP version error

### ISSUE THREAD

**Issue by TreeT2** [tseemann/prokka#196]
Hi All,
I have been using prokka on a HPC system for a few months now with no issue (via a pbs script). I recently installed signalP v4.1 as instructed and added the executable path to the .bashrc file. Now when I run prokka I get the following error msg:  
![image](https://cloud.githubusercontent.com/assets/20044679/19236173/fad59cb0-8eed-11e6-9dbf-6e92a3ad3bab.png)

If I run prokka locally without the pbs script it runs no problem, signalP and the version is detected. 
Not sure what the issue is.
Thanks
Lynda

**Comment by tseemann** [comment]
The command I run to check the version is:
```
"signalp -v < /dev/null 2>&1 | egrep ',|# SignalP' | sed 's/^# SignalP-//'",
```

If you run that on the head node, what does it print?

**Comment by TreeT2** [comment]
![image](https://cloud.githubusercontent.com/assets/20044679/19645088/eb63aa30-99ea-11e6-9d46-365b59030ca7.png)

**Comment by peterjc** [comment]
@TreeT2 you need to run that without the double quotes, e.g. on my server:

```bash
$ signalp -v < /dev/null 2>&1 | egrep ',|# SignalP' | sed 's/^# SignalP-//'
3.0b, Dec 2005
```

But as in your screen shot from October, this fails:

```bash
$ "signalp -v < /dev/null 2>&1 | egrep ',|# SignalP' | sed 's/^# SignalP-//'"
-bash: signalp -v < /dev/null 2>&1 | egrep ',|# SignalP' | sed 's/^# SignalP-//': No such file or directory
```

**Comment by moskalenko** [comment]
Just as a side note for signalp 4.1 the command above returns the following version, which prokka doesn't handle:

'4.1 euk predictions'

It looks like signalp now has a '-V' argument, so

signalp -V returns

signalp 4.1

which can be handled much easier with

signalp -V | awk '{print \$2}'

With the above prokka-1.12 happily verifies that signalp version '4.1' is available.

**Comment by thkuo** [comment]
Thanks @moskalenko for the suggestion. I had the same problem and just tried replacing the version-checking line in prokka 1.13:
```
signalp -v < /dev/null 2>&1 | egrep ',|# SignalP' | sed 's/^# SignalP-//'
```
with 
```
signalp -V | awk '{print \$2}'
```
It works well so far. By the way, the backslash before ```$2``` seems important.

**Comment by tseemann** [comment]
@thkuo @moskalenko does the awk version work on version 3.x of signalp though?

**Comment by stemicha** [comment]
Dear Torsten,

I updated my system to MacOS 11.0.1.

I reinstalled prokka via conda. And got a signalP version issue, which I do not understand.

Prokka error:
"Looking for 'signalp' - found /usr/local/bin/signalp
[07:51:20] Could not determine version of signalp - please install version 3.0 or higher"

going to the folder : "/usr/local/bin/signalp"
executing: "./signalp -V"
resulted in: "signalp 4.1"

Do you have any clue or workaround?

**Comment by peterjc** [comment]
See #536 from @stemicha
