### ISSUE TITLE
Could not determine version of tbl2asn

### ISSUE THREAD

**Issue by BoMatt** [tseemann/prokka#198]
Hi!

I have this problem while running Prokka.

`[09:04:42] Looking for 'tbl2asn' - found /home/mattia/bin/prokka/bin/../binaries/linux/tbl2asn
[09:04:42] Could not determine version of tbl2asn - please install version 24.3 or higher`

I downloaded Prokka from github and the tbl2asn file is correctly in the binaries/linux folder.

**Comment by ianpgm** [comment]
Experiencing the exact same problem

**Comment by TreeT2** [comment]
I had this issue. If you download the latest release from NCBI and replace tbl2asn in the prokka directory, it should work. 
ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/

**Comment by BoMatt** [comment]
Thanks you @TreeT2, now it seems to work correctly!

**Comment by tseemann** [comment]
Thanks @TreeT2 !
