### ISSUE TITLE
Blasting sprot and genus databases

### ISSUE THREAD

**Issue by MattPinder** [tseemann/prokka#199]
Apologies if I'm missing a very obvious option in the program, but is it possible to blast both the relevant sprot database and a specified genus database? I've compiled a custom Marinobacter database, but whenever I use the --genus and --usegenus options, the general Bacteria sprot database doesn't appear to be used at all. I'd like to combine the search of the two if this is possible, so any advice would be appreciated.

**Comment by tseemann** [comment]
It should use your genus database first, then uses sprot.

Do you have the `.log` file?

**Comment by MattPinder** [comment]
Upon closer inspection of the `.log` file, it appears that I was mistaken, so apologies for that; it IS using the sprot database afterwards, it just doesn't add much to the results of the Marinobacter database. The issue I'm having is that I'm getting many less named genes when I use the --usegenus option. Is there any way of getting Prokka to use sprot first, and **then** the genus database? Or would the --proteins option have such an effect?

**Comment by aleimba** [comment]
Hi @MattPinder,
trusted proteins given via **--proteins** will be used first, all CDSs not annotated by then will then be done with the other databases. This is the order in Prokka (or at least used to be):

* --protein DB
* Uniprot
* HAMAP
* CLUSTERS
* genus

Cheers,
Andreas

**Comment by MattPinder** [comment]
Apologies for the late reply.
Thank you both for suggesting the --proteins option, using this is giving me much better results.
