### ISSUE TITLE
Minimum gene length

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [tseemann/prokka#200]
Just to be sure: Prokka does NOT restrict minimal length of genes or more specific CDS' right?

(Nor does prodigal, right?)

Thx a lot!

**Comment by tseemann** [comment]
Sorry, but yes Prodigal does have a minimum predicted CDS length.
If it is too low, you will get far too many false positives.

It's hard-coded in this file: https://github.com/hyattpd/Prodigal/blob/GoogleImport/node.h
```
#define MIN_GENE 90
#define MIN_EDGE_GENE 60
```

Maybe @hyattpd will make these command line parameters eventually.

**Comment by hyattpd** [comment]
There's a good reason for the minimum gene lengths, in addition to avoiding false positives.  Prodigal allows genes on the same strand to overlap by a small amount (60bp, if I recall correctly).  Once minimum gene length falls below that overlap distance, it can create weird effects in the dynamic programming / graph traversal where you can have a gene embedded in the overlap region between two other genes (which may cause bugs/weirdness, not sure)... so I don't recommend messing with these parameters without also lowering the overlap distance.  And I wouldn't go below 60 regardless.
