### ISSUE TITLE
suggestion for prokka-cdd_to_hmm improvement

### ISSUE THREAD

**Issue by piatekmj** [tseemann/prokka#201]
I noticed that prokka-cdd_to_hmm throws a BioPerl error and dies when there is no corresponding id number for chosen database (in my case 'cd') in the fasta.tar.gz.

I had to change the code of this script in order to overcome that issue.
I simply added the following line:
`next if (! -e $faln);`
after the line 64 in your script and it got rid of this problem.

**Comment by tseemann** [comment]
Thanks for the tip @piatekmj - now fixed.
