### ISSUE TITLE
prokka-cdd_to_hmm breaks at hmmbuild

### ISSUE THREAD

**Issue by piatekmj** [tseemann/prokka#202]
I've noticed that after running prokka-cdd_to_hmm it breaks at the hmmbuild step. This is most likely an issue with hmmbuild not being able to parse the file.aln containing complex ids inside such as:

`#=GS gi|15825923|pdb|1I80|A/1-258AC unknown`

The error hmmbuild throws as part of prokka-cdd_to_hmm is below (here I'm trying to process cd database, hence the cd.aln filename):

```
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             cd.aln
# output HMM file:                  cd.hmm.ascii
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
Alignment input parse error:
   number of seqs in block did not match number annotated by #=GS lines
   while reading Stockholm file cd.aln
   at or near line 67
Created cd.hmm.ascii file - converting to cd.hmm binary format.

Error: File format problem in trying to open HMM file cd.hmm.ascii.
File exists, but appears to be empty?
```

I run hmmbuild independently of prokka and it complained in similar way.

In order to fix this issue, one has to process the file.aln (or whatever you have generated) in order to simplify the complex ids for hmmbuild. This is equally true for the lines of file.aln starting with '#=GS gi' and the alignment block ids.

Hope that helps someone.

**Comment by tseemann** [comment]
`prokka-cdd_to_hmm` was specifically for the NCBI CDD (Conserved Domain Database). 

Is that what you are running it on?

**Comment by piatekmj** [comment]
I believe yes. It's been a while since I have downloaded the CDD related files.

**Comment by tseemann** [comment]
I stopped using the CDD in Prokka after v1.11  but I see it has been updated in 2016 so I am downloading it now and will see what is going on.

**Comment by tseemann** [comment]
CDD is no longer supported at NCBI.
