### ISSUE TITLE
MSG: Seq [contigxxxx]: Terminator codon inside CDS!

### ISSUE THREAD

**Issue by blancaverag** [tseemann/prokka#203]
I am trying to annotate metagenomic contigs with prokka. For that, I have joined bacteria, archaea and virus databases and run the prokka command. The computation runs fine until:

[05:38:20] Found 71830 CDS
[05:38:20] Connecting features back to sequences
[05:38:20] Not using genus-specific database. Try --usegenus to enable it.
[05:38:20] Annotating CDS, please be patient.
[05:38:20] Will use 8 CPUs for similarity searching.

--------------------- WARNING ---------------------
MSG: Seq [contig01018]: Terminator codon inside CDS!
...

What could be wrong?

**Comment by tseemann** [comment]
@blancaverag what version of Bioperl are you using?  send me the whole .log file if possible.

**Comment by blancaverag** [comment]
Hi, 

I have BioPerl 1.007000.
The problem arises when I add the --metagenome option. Without it, it just runs perfectly.
I am attaching the log file and the screen message, as the error does not appear in the log file.
[PROKKA_11012016_log.txt](https://github.com/tseemann/prokka/files/564940/PROKKA_11012016_log.txt)
[err_file.txt](https://github.com/tseemann/prokka/files/564941/err_file.txt)

**Comment by regelkamp** [comment]
Same problem here...

[Prokka_log.txt](https://github.com/tseemann/prokka/files/589735/Prokka_log.txt)

**Comment by mherold1** [comment]
I have noticed before that prodigal sometimes predicts CDS that contain stop codons, e.g. :
```
>PROKKA_00425 hypothetical protein
MTREKGYAYNRRFCASGAGRNNNEQFSKSQQWFGQDKQHSTLNHNFNKIFSIGSGCGQTE
FFFPA*HIALAVSGNCKPDNQNNQTLPKHEKFQKIHS*VFALSDCNSTVRSRVLEYLFWS
*CKSYFLSKSSCSYQFDLAVFITISTYSYRKETKRKS
```
Maybe sequences like this trigger a warning in bioperl 1.007 while in 1.0069 this was not the case?

**Comment by alneberg** [comment]
I've seen the same as @mherold1 when ran in the --metagenome mode.
I believe in our case it's because prodigal will disregard the -g flag when the metagenome mode is used. 
Prodigal thus gives some genes from a different genetic code, and this information is lost since prokka only picks up the nucleotide sequence form prodigal.

Does that make sense?

**Comment by spock** [comment]
@alneberg  , prokka does get only start/end/strand information from prodigal for each CDS.

**Comment by alneberg** [comment]
@spock, exactly, so then if prodigal have created a gene past a regular stop codon, there will be a stop codon in the amino acid sequence when prokka translates the nucleotide sequence with the original intended genetic code.

**Comment by arielamadio** [comment]
Could this be related with the issue I've added about selenocysteine?

**Comment by maureenbug** [comment]
Hey I'm getting the same message when running on meta mode. Is there any way to get around this issue?

**Comment by maureenbug** [comment]
I'm getting the same warning, and some of my samples have ~40% of the detected genes with internal stop codons... this seems quite high to me.

**Comment by willnotburn** [comment]
2 years late to this party. I understand what @alneberg is saying. OK, but then what? How does prokka resolve this inconsistency with prodigal? Should I still use the --metagenome mode?

**Comment by tseemann** [comment]
Prokka was never intended to me used for metagenomes.

I did not know the Prodigal reported genes from different genetic codes!
That would be the source of the problem.

What exact version of prodigal are you using?
I think Homebrew and maybe Conda recently updated.

**Comment by willnotburn** [comment]
prokka log file says Prodigal version 2.6

**Comment by tseemann** [comment]
```
prodigal
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------

Usage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]
                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]
                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]
         -g:  Specify a translation table to use (default 11).
```

**Comment by willnotburn** [comment]
It is indeed PRODIGAL v2.6.3 [February, 2016]

**Comment by willnotburn** [comment]
@tseemann It is indeed PRODIGAL v2.6.3 [February, 2016]

**Comment by tseemann** [comment]
So it turns out that prodigal in metagenome mode will try translation tables 4 and 11 and see which does 'better'.    So it might choose some contigs to be in table 4, but i don't know which ones are that. So when I go to translate proteins that were done with table 4,   but I am using table 11 (from --gcode) then it might sometimes encounter stop codons.

**Comment by JinqunHuang** [comment]
@tseemann 
Hi, Torsten,
WARNING massage "Terminator codon inside CDS" would be reported if I set the "--metagenome" in Prokka 1.13.

I try different parameter combination as below, the WARNING massages still appear.

"prokka --outdir AS100-2 --prefix AS100 --addmrna --metagenome --gcode 11 contigs.fasta.500"

or

"prokka --outdir AS100-3 --prefix AS100 --kingdom Bacteria --gcode 11 contigs.fasta.500"

Once I do not set the "--metagenome", the  WARNING massages do not appear.
My datas are metagenomics datas, could you please have any advises ?

Prodigal V2.6.3
Prokka 1.13 

Thanks a lot!
JinQun

**Comment by tseemann** [comment]
@JinqunHuang ok it seems prodigal ignores genetic code in metagenome mode, because it knows it is a mixture of different things.  i can't tell what table prodigal used (?) so i don't know how to translate it correctly.

**Comment by cssulliv** [comment]
Hi, 

New user here. I just installed Prokka via conda and I too am getting the "Terminator codon inside CDS" message but only for a subset of my MAGs when I include the --metagenome flag. My question is have other folks annotated their MAGs using a default prokka run and if so did it positively or negatively affect any downstream analysis? Any suggestions on this would be helpful :)

**Comment by tseemann** [comment]
The problem is that `--metagenome` invokes a special mode of `prodigal` (the gene predictor tool) which produces predictions which do NOT match `--gcode 11`.  So you get stop codons (relative to 11) but they were predicted assuming some other code. if you have nice contigs and they are all bacterial, don't use `--metagenome`.

**Comment by Bio-Quest** [comment]
use `--forece` option will produce right *.faa file, but warnning message "Terminator codon inside CDS" still appear.
