### ISSUE TITLE
Add diamond compatibility

### ISSUE THREAD

**Issue by michoug** [tseemann/prokka#205]
Hi,
I was doing a metagenome assembly and due to its size the blast part took a few days.
I found out recently about https://github.com/bbuchfink/diamond which is a blast-like 20,000 faster.
Could it be a possibily to allow the user the possibility to use one or the other.
Best
Greg

**Comment by tseemann** [comment]
Greg @michoug 

Are you sure it was the BLAST part? 
The HMMER3 parts are the slow ones.  Diamond is faster, but not 20,000x in general, and the database is much bigger.  

How large was your metagenome (contigs, total bp) ?
I am interested in making `metaprokka` for these huge cases, better parallelism.

**Comment by michoug** [comment]
Dear Torsten @tseemann 

Sorry indeed it was the hmmer3 that was very slow.
My metagenome took a week due to the fact that it had around 150k contigs with an N50 of around 3k bp.
