### ISSUE TITLE
Add documentation on how /product descriptions get renamed without `--rawproduct`

### ISSUE THREAD

**Issue by chrisgulvik** [tseemann/prokka#208]
Just a feature enhancement request:

Could you list what makes a `/product` description get renamed when the `--rawproduct` argument is not passed to `prokka`? Perhaps at the end of this section describing the use of a custom FastA file for annotation: https://github.com/tseemann/prokka#fasta-database-format

Example renaming (without `--rawproduct`) from the log file:
[18:38:54] Modify product: type IV secretion system protein Cag5, VirD4 homolog [Type IV secretion system (VF0060)from Helicobacter pylori 26695] => hypothetical protein

**Comment by tseemann** [comment]
@chrisgulvik this problem is frustrating problem. i would have assumed Swissprot had nice clean product names but they don't. I am forced into horrible regexps to clean them up. But of course they make bad mistakes sometimes, like your example above.  There are many other such examples in the lssues here.

I was wondering if i should crowd source a google doc or similar to 'clean up' the 70,000 or so core Swissprot protein names, and fix my copy of it.

**Comment by tseemann** [comment]
I've clarified it a bit in the docs now.

```
  # check the whitelist first                                                                                              return $p if exists $GOOD_PROD{$p};
                                                                                                                           return $HYPO if $p =~ m/DUF\d|UPF\d|conserved|domain of unknown|\b[CN].term|paralog/i;
  return $HYPO if $p !~ m/[a-z]/;
  # eg. Leu/Ile/Val-binding protein homolog 3                                                                              $p =~ s/\bhomolog( \d)?\b//g;

  $p =~ s/^arCOG\d+\s+//;
  $p =~ s/\((EC|COG).*?\)//;
  $p =~ s/\s+\w+\d{4,}c?// unless $p =~ m/\bIS\d+\b/; # remove possible locus tags                                         $p =~ s/ and (inactivated|related) \w+//;
  $p =~ s/,\s*family$//;

  $p =~ s/^(potential|possible|probable|predicted|uncharacteri.ed)/putative/i;
  if ($p =~ m/(domain|family|binding|fold|like|motif|repeat)\s*$/i and $p !~ m/,/)  {                                        $p .= " protein";
  }
  return $p;
```
