### ISSUE TITLE
long CRISPR repeats

### ISSUE THREAD

**Issue by haruosuz** [tseemann/prokka#209]
"CRISPR repeats range in size from 24 to 48 base pairs.[56]" (https://en.wikipedia.org/wiki/CRISPR).
"Analysis of the current CRISPR database24 reveals that repeats range from 23- to 50-nt long and have an average length of 31 nt" (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2928866/).
For Roseovarius genome annotation using Prokka v1.11 produced long CRISPR repeats (2477 bp) as follows:

     repeat_region   61467..63943
                     /rpt_family="CRISPR"

**Comment by ctSkennerton** [comment]
CRISPR regions are composed of many repeat units that are each 23 to 50 bp. Prokka is only annotating the bounds of the CRISPR region rather than each individual repeat unit.

**Comment by tseemann** [comment]
I am using `minced` to do the prediction, author is @ctSkennerton .

I am currently only using the `-gff` option but I could use `-gffFull` and annotate the repeat units.

```
          -gff       Output summary results in gff format containing
                     only the positions of the CRISPR arrays. Default: false
          -gffFull   Output detailed results in gff format containing
                     positions of CRISPR arrays and all repeat units. Default: false
```

**Comment by tseemann** [comment]
I found this http://www.genome.jp/dbget-bin/www_bget?refseq+NC_015970

```
repeat_region   46177..46632
                     /inference="COORDINATES: alignment:crt:1.2"
                     /inference="COORDINATES: alignment:pilercr:v1.02"
                     /rpt_family="CRISPR"
                     /rpt_type=direct
                     /rpt_unit_range=46177..46204
                     /rpt_unit_seq="gggtcatccctgcgcgcgcgggagtcgg"
```

**Comment by tseemann** [comment]
I have updated Prokka to at least tell you how many repeat units there are. I will look at added repeat units in v1.13.

```
     repeat_region   2421118..2421311
                     /note="CRISPR with 4 repeat units"                                                                                      
                     /rpt_family="CRISPR"
                     /rpt_type=direct
```
