### ISSUE TITLE
Custom database

### ISSUE THREAD

**Issue by DeniRibicic** [tseemann/prokka#210]
Hi Folks,

I want to run Prokka against a custom databse "Aromadeg" (Please have a look: All sequences alligned http://aromadeg.siona.helmholtz-hzi.de/) on my assambled contigs. I am a bit puzzled here. Should this database be somehow prepared before running Prokka on it or is it ready to go. 
Usually when I run Prokka with the default databases I would use following command:

> prokka $readfile –outdir $name.prok --norrna –notrna –metagenome –cpus 8

How to specify here the custom database?

Appreciate your help,
Deni

**Comment by tseemann** [comment]
Some documentation is here: https://github.com/tseemann/prokka#databases

You can provide a custom database with `--proteins`.    Ideally this would be a prokka formatted FASTA file, or a Genbank file.  But it will accept a normal FASTA file (proteins).

Your Aromadeg database `AromaDeg_all_unaligned.fasta` looke like this:

```
>YP_004720923|Sulfobacillus_acidophilus_TPY|Non                                                                                            MDNDNPRLDTYYAELRQHHLGPLWNSIGRLMTHEPRPRAEAHLWRWSDVR
```

Unfortunatelty there is no description after the `>ID` so the `/product` would be empty in the annotation.

But if you if do this Unix command

```
cat AromaDeg_all_unaligned.fasta | sed 's/|/ /' | sed 's/|/ - /' > AromaDeg.faa
```
and then use `prokka --proteins AromoaDeg.faa` it will put the `Sulfobacillus_acidophilus_TPY -
 Non` in the annotation.

Hope this helps!
