### ISSUE TITLE
Packaged tbl2asn doesn't work??

### ISSUE THREAD

**Issue by mw55309** [tseemann/prokka#213]
Not sure if this is what you intended:

% prokka/bin/../binaries/linux/tbl2asn
-bash: prokka/bin/../binaries/linux/tbl2asn: /home/linuxbrew/.linuxbrew/lib/ld.so: bad ELF interpreter: No such file or directory

**Comment by tseemann** [comment]
Prokka will use the `tbl2asn` in your PATH over the one bundled in Prokka.

As you are using Brew, you should do `brew upgrade tbl2asn` or just `brew upgrade` to make sure your system is up to date.
