### ISSUE TITLE
Issues with checks on nhmmer ??

### ISSUE THREAD

**Issue by mw55309** [tseemann/prokka#214]
I get this when I run prokka

[10:08:04] No binary for your OS 'linux' is included. If you have one, copy it to /exports/cmvm/eddie/eb/groups/watson_grp/software/barrnap-0.7/bin/../binaries/linux/nhmmer.

But it's fine and runs:

/exports/cmvm/eddie/eb/groups/watson_grp/software/barrnap-0.7/bin/../binaries/linux/nhmmer
Incorrect number of command line arguments.
Usage: nhmmer [options] <query hmmfile|alignfile> <target seqfile>

where basic options are:
  -h : show brief help on version and usage

To see more help on available options, do /exports/cmvm/eddie/eb/groups/watson_grp/software/barrnap-0.7/bin/../binaries/linux/nhmmer -h

**Comment by tseemann** [comment]
This is really an issue for https://github.com/tseemann/barrnap

I can't deduce what is happening from the above. 

What does  `ls -lsa /exports/cmvm/eddie/eb/groups/watson_grp/software/barrnap-0.7/bin/../binaries/linux/nhmmer` say?

**Comment by tseemann** [comment]
I've upgrades Barrnap to 0.8 which should help with this issue.
