### ISSUE TITLE
Could not run command: hmmpress

### ISSUE THREAD

**Issue by haruosuz** [tseemann/prokka#217]
Following https://github.com/tseemann/prokka/blob/master/README.md#github  
Prokka was downloaded on 2017-02-21 using:  

	cd $HOME
	git clone https://github.com/tseemann/prokka.git
	ls prokka
	prokka/bin/prokka --setupdb

This printed the following messages:

	[02:03:57] Looking for 'hmmpress' - found /pub/neo/prokka/binaries/linux/hmmpress
	[02:03:57] Determined hmmpress version is 3.1
	[02:03:57] Pressing HMM database: /home/haruo/prokka/bin/../db/hmm/HAMAP.hmm
	[02:03:57] Running: hmmpress \/home\/haruo\/prokka\/bin\/\.\.\/db\/hmm\/HAMAP\.hmm
	Working...    [02:03:57] Could not run command: hmmpress \/home\/haruo\/prokka\/bin\/\.\.\/db\/hmm\/HAMAP\.hmm

**Comment by tseemann** [comment]
I can not reproduce this problem, even on an older Centos 6 system.

You seem to have 2 copies of Prokka installed and the old one is in your PATH ?

One in `/pub/neo` and one in `/home/haruo`.

I think they are conflicting. The binaries are coming from one, and the databases in another one?

**Comment by haruosuz** [comment]
Thank you. The problem was solved. BTW
https://github.com/tseemann/prokka/blob/master/README.md
##Bugs

* Submit problems or requests here: https://github.com/tseeeman/prokka/issues

should be

* Submit problems or requests here: https://github.com/tseemann/prokka/issues

**Comment by tseemann** [comment]
@haruosuz thanks for the typo - i've fixed it.
