### ISSUE TITLE
Locale Problem

### ISSUE THREAD

**Issue by jjinjin123** [tseemann/prokka#221]
Hi There,

One of our user was trying to use Prokka through his Mac with Dutch settings. When he ssh in to our system, LC_CTYPE = "UTF-8" was inherited. Therefore, when he run prokka, he get:
> > barrnap --version
> > perl: warning: Setting locale failed.
> > perl: warning: Please check that your locale settings: 
> > LANGUAGE = (unset),
> > LC_ALL = (unset), 
> > LC_CTYPE = "UTF-8", 
> > LANG = "en_US.UTF-8" 
This is because Prokka was trying to find barrnap version string, but it can't.

We suggests to set LC_ALL to "C" in the environment as the first thing to avoid this problem.
[jzhang8@merri ~]$ locale
LANG=en_AU.UTF-8
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC=en_AU.UTF-8
LC_TIME=en_AU.UTF-8
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY=en_AU.UTF-8
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER=en_AU.UTF-8
LC_NAME=en_AU.UTF-8
LC_ADDRESS=en_AU.UTF-8
LC_TELEPHONE=en_AU.UTF-8
LC_MEASUREMENT=en_AU.UTF-8
LC_IDENTIFICATION=en_AU.UTF-8
LC_ALL=

"LC_ALL" set to "C"
[jzhang8@merri ~]$ LC_ALL=C locale
LANG=en_AU.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

Regards

Jin Zhang

**Comment by chrissamuel** [comment]
To elaborate a little more, the user reported a problem with Prokka where it claimed a new enough version wasn't installed.  When we saw the output it  said:

[11:32:30] Looking for 'barrnap' - found /usr/local/easybuild/software/Barrnap/0.6/bin/barrnap
Use of uninitialized value in concatenation (.) or string at /usr/local/easybuild/software/Prokka/1.11-faster112-Java-1.8.0_60/bin/prokka line 192.
[11:32:30] Determined barrnap version is Use of uninitialized value in numeric lt (<) at
/usr/local/easybuild/software/Prokka/1.11-faster112-Java-1.8.0_60/bin/prokka line 193.
*[11:32:30] Prokka needs barrnap 0.4 or higher. Please upgrade and try again.*

So the locale errors confuse Prokka when trying to parse the version string.

If Prokka were to set LC_ALL=C in the environment first it would eliminate this issue and ensure that collation, etc, is deterministic and not modified by the users selecte locale.

All the best,
Chris

**Comment by tseemann** [comment]
@chrissamuel ok - i see what you are saying now - thank you for making the effort to explain it :)
yes, i should launch it from within prokka using `LC_ALL=C barrnap ..`, you are right.
thank you!

**Comment by tseemann** [comment]
Thanks for submitting it here @jjinjin123 !
