### ISSUE TITLE
.CSV output of all features suitable for Excel

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#223]
ie. `gff2biologist.pl`

**Comment by aleimba** [comment]
Hi @tseemann,

I wrote [`tbl2tab`](https://github.com/aleimba/bac-genomics-scripts/tree/master/tbl2tab) for this purpose, i.e. to be able to manually change the annotation in a spreadsheet software. But, would be nicer directly out of `prokka` or GFF3.

**Comment by tseemann** [comment]
I now output a `.tsv` file.  It can be converted to `.csv` or `.xls` by other tools.
