### ISSUE TITLE
Prokka needs minced 2.0 or higher. Please upgrade and try again. 

### ISSUE THREAD

**Issue by rajmandage** [tseemann/prokka#225]
I have installed PROKKA version 1.12 on linux system but getting following error.

[12:31:18] Determined minced version is 

Use of uninitialized value in numeric lt (<) at ./prokka line 201.

[12:31:18] Prokka needs minced 2.0 or higher. Please upgrade and try again. 

How should I update minced to 2.0 ?

Raj

**Comment by suryasaha** [comment]
It is a separate but quick install. You can get mincED from https://github.com/ctSkennerton/minced and build it. You will need to install java in case you don't have it already. Please add it to your $PATH. See http://www.troubleshooters.com/linux/prepostpath.htm in case you have not done that before.

**Comment by tseemann** [comment]
@rajmandage you have an older version of minced installed which doesn't report a version.

If you just remove the OLD one, it will automatically use the new one bundled in Prokka.

Or, you can upgrade using the info @suryasaha generously provided.

**Comment by keyfm** [comment]
Hi,
I just installed a new version of prokka (v1.13.3) today in my conda base environment using:
`conda install -c conda-forge -c bioconda prokka`

Initiating the following command:
` prokka --force --cpus 8 --proteins /scratch/users/fkey/staphAD/annotations/ref_set1/GCF_9gbk_merged.gbk --mincontiglen 500 --outdir 4-annotation/subject_8 --prefix prokka_out 3-spades/subject_8/contigs.fasta`

Leads to the following `minced` error:
`...
[13:53:19] Looking for 'minced' - found /scratch/users/fkey/tools/miniconda3/bin/minced
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: minced has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
[13:53:19] Could not determine version of minced - please install version 2.0 or higher
`

An update through:
`conda update minced` did not solve the bug.

You mention above to just remove the old version, in order for prokka to use the bundled version. How do I remove specifically the outdated `minced` version in my conda environment without affecting the prokka bundled version?

Thx!

**Comment by tseemann** [comment]
I think the problem is the Java version being used.
Does `minced -h` work?
What does `java -version` say?

**Comment by keyfm** [comment]
Thx for your reply Torsten.

`minced -h` leads to an error
`Error: A JNI error has occurred, please check your installation and try again ... `

The java command returns the following:
`openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)`

**Comment by jdalsdurf** [comment]
@keyfm I am getting same errors with:
minced -h

waiting to see a fix.

**Comment by keyfm** [comment]
@jdalsdurf I just fixed my problem by following the advice found in the following [thread](https://github.com/bioconda/bioconda-recipes/issues/10277)

Which suggests to setup an individual prokka environment using the following command:
`conda create -n prokka-test prokka=1.13 minced=0.3.0 parallel=20180522`

Probably not the most elegant but certainly a working solution.

**Comment by ralsallaq** [comment]
I have the same problem with minced and this is what worked for me thanks @keyfm for the hint.
conda install prokka=1.13 minced=0.3.0 parallel=20180522 -n prokka -c conda-forge -c bioconda -c defaults
specifying multiple channels was particularly important.

**Comment by Buuntu** [comment]
Same problem with 1.14.  `conda install prokka=1.14 minced=0.3.0 parallel=20180522` works for me though

**Comment by tseemann** [comment]
Ok, I created a new blank VM with Ubuntu 18 and installed miniconda3.
I set up bioconda as per https://bioconda.github.io/user/install.html


```
% cat $HOME/.condarc
channels:
  - conda-forge
  - bioconda
  - defaults

% conda update --all

% conda create -n prokka-1.14.0 prokka

% conda activate prokka-1.14.0

% conda list | egrep 'java|jdk|minced|parallel|blast'
blast                     2.9.0           pl526h979a64d_3    bioconda
minced                    0.4.0                         1    bioconda
openjdk                   11.0.1            h516909a_1016    conda-forge
parallel                  20190722                      0    conda-forge
prokka                    1.14.0                  pl526_0    bioconda

% prokka --version
prokka 1.14.0

% minced --version
minced 0.4.0

```

**Comment by tseemann** [comment]
I think many of the problems with conda relate to
1. having the wrong channel order
2. trying to install in the base environment with other tools

**Comment by tseemann** [comment]
Conda + prokka + minced should be resolved now.

**Comment by mmcguffi** [comment]
I had this problem, both with Conda and Homebrew on a Mac (Catalina) -- after many other failed attempts at solving this, I eventually fixed the problem by simply downloading a newer version of the Java JDK: https://www.oracle.com/java/technologies/javase-downloads.html

My computer automatically selects the most recent version of Java via this method, so after installation everything completely worked. Hope this helps someone in the future!
