### ISSUE TITLE
Assigning GOs

### ISSUE THREAD

**Issue by DeniRibicic** [tseemann/prokka#227]
Hi there,

I was wondering what would be the best way to assign GO terms to PROKKA output?
Is it a valid approach to take the PROKKA ec annotations and just match it against ec2GO list?

Deni

**Comment by tseemann** [comment]
@DeniRibicic  I am looking to add GO support to Prokka 1.13.   You could use  ec2GO but you would miss GO terms for non-enzymes.   Prokka uses uniprot as a first step, and uniprot has all the GO terms - i just need to add support for it.

**Comment by Perugolate** [comment]
GO support missed the 1.13 boat?

**Comment by tseemann** [comment]
No it didn't! 

See https://github.com/tseemann/prokka/releases/tag/v1.13

`Updated sprot databases and added COG terms where availabe (WORK IN PROGRESS)`

There are COGs in the Genbank/GFF files.

**Comment by mmcguffi** [comment]
I see GO terms were planned for 1.14, but it appears they didn't make their way in I believe?
