### ISSUE TITLE
Pfam output difference compared to prokka 1.11

### ISSUE THREAD

**Issue by JordyCoolen** [tseemann/prokka#230]
I noticed that some of the CDS have different annotations compared to prokka 1.11
It seems that it is not using the Pfam motif data. Is there a reason for this because I can't find
any in the change log?

Example:

In prokka version 1.11 output in gff is:
ID=B14053431A_01325;inference=ab initio prediction:Prodigal:2.6,protein motif:Pfam:PF02734.11;locus_tag=B14053431A_01325;product=DAK2 domain protein

In prokka version 1.12 output in gff is:
ID=B14053431A_01325;inference=ab initio prediction:Prodigal:2.6;locus_tag=B14053431A_01325;product=hypothetical protein

Thanks in advance.

Jordy

**Comment by tseemann** [comment]
@JordyCoolen That is a Pfam accession. Prokka no longer comes bundled with Pfam HMM database. That is why it is not being annotated anymore.

You can download and index Pfam yourself, and pass it via `--hmms`
OR
You can format it as required by https://github.com/tseemann/prokka#fasta-database-format
and put it in the `db/hmms/` folder and run `prokka --setupdb`.
