### ISSUE TITLE
Cannot run the cmscam --clanin

### ISSUE THREAD

**Issue by YangZituo** [tseemann/prokka#232]
Hello,
When i run the cmscan code from the Userguide, I find out some problems,
[ns_phd06@tll-rv1 binaries]$ cmscan --rfam --cut_ga --nohmmonly --tblout mrum-genome.tblout --fmt 2 --clanin /data/GenhuaLab/zituo/infernal-1.1.2-linux-intel-gcc/testsuite/Rfam.12.1.clanin /data/GenhuaLab/zituo/infernal-1.1.2-linux-intel-gcc/Rfam.cm  /data/GenhuaLab/zituo/miRNA-collapser/sm6h_1.collapsed.fastq > /data/GenhuaLab/zituo/miRNA-collapser/sm6h_1.collapsed.cmscan

Error: unable to find model RyeB listed in /data/GenhuaLab/zituo/infernal-1.1.2-linux-intel-gcc/testsuite/Rfam.12.1.clanin in SSI inde

May anyone help me? Thanks a lot!! 
@tseemann

**Comment by deepaksen1996** [comment]
you have to change your directory to "/data/GenhuaLab/zituo/infernal-1.1.2-linux-intel-gcc" then try to run that code

**Comment by tseemann** [comment]
@YangZituo this is a forum for Prokka, not for Infernal. Please see http://eddylab.org/infernal/
