### ISSUE TITLE
Crispr arrays disappeared from .ffn

### ISSUE THREAD

**Issue by asetGem** [tseemann/prokka#233]
In the previous version, if a "repeat_region" feature was found, it appeared in the tbl file, and its sequence was also in the .ffn file (with a header equal to the genome name instead of PROKKA_xxxxx for other loci types).

Now, it still appears in the tbl file (havng even more details on how many repeats etc.), but its sequence does not appear anymore in the .ffn file.

Is it by choice, or is it a bug?

Thank you

**Comment by tseemann** [comment]
IIRC this was a deliberate change, I considered that having the CRISPR regions in the .ffn file was a bug.  

There are various tools like `seqret` and `readseq` and `gt` which can take a .gff or .gbk and extract out what you need.

Sorry!
