### ISSUE TITLE
File .err: why all my features have inconsistent gene locations

### ISSUE THREAD

**Issue by esthercamilo** [tseemann/prokka#234]
I am not sure if here is the best place to put this question because it is conceptual (and not an issue about the program). I am using PROKKA with the following set of arguments:

`$ prokka myorganism.fa --cdsrnaolap ON --rfam 1 --rawproduct`

While my gbk and gff seems okay, I obtain an error file of 1.2Mb saying that all my features have inconsistent gene locations and "DiscRep_SUB:FEATURE_LOCATION_CONFLICT::Coding region xref gene does not exist". 

I thought that may be because my genome is new the IDs are not recognized. Is that right?

**Comment by tseemann** [comment]
I don't really understand `tbl2asn` errors anymore. NCBI keep "changing the rules". I will be removing it from the next release of Prokka.

PS. The syntax `--cdsrnaolap ON` is incorrect, just use `--cdsrnaolap`
