### ISSUE TITLE
Bulk annotation in prokka?

### ISSUE THREAD

**Issue by mmaesaar** [tseemann/prokka#237]
Is it possible to annotate many sequences with one command in prokka for ROARY input (with unique tag)?

Thanks

**Comment by dutchscientist** [comment]
Just make a script. I do that in Excel with just the variables changed, and then use Notepad++ to take the tabs out.

**Comment by mmrec** [comment]
Perhaps you have some examples to post here?

**Comment by dutchscientist** [comment]
In Notepad++, set as Unix/OSX file (Settings>Preferences >New Document)

#!/bin/bash
prokka --prefix Ec001 --locustag Ec001 --increment 10 --cpus 3 --usegenus --centre XXX --compliant --mincontiglen 200 --genus Escherichia --species coli --strain 001 --outdir ecoli_prokka --force --addgenes Ecoli001.fna
prokka --prefix Ec002 --locustag Ec002 --increment 10 --cpus 3 --usegenus --centre XXX --compliant --mincontiglen 200 --genus Escherichia --species coli --strain 002 --outdir ecoli_prokka --force --addgenes Ecoli002.fna
prokka --prefix Ec003 --locustag Ec003 --increment 10 --cpus 3 --usegenus --centre XXX --compliant --mincontiglen 200 --genus Escherichia --species coli --strain 003 --outdir ecoli_prokka --force --addgenes Ecoli003.fna

Save as prokka.script

Copy to Linux machine, from command line:
chmod +x prokka.script
./prokka.script

**Comment by aleimba** [comment]
Hi @mmrec @dutchscientist,

hope it's ok if I chime in here. You can also use a bash for loop one-liner, since all your files should have unique names:
```bash
for file in *.fna; do tag=${file%.fna}; prokka --prefix "$tag" --locustag "$tag" --increment 10 --cpus 3 --usegenus --centre XXX --compliant --mincontiglen 200 --genus Escherichia --species coli --strain "$tag" --outdir 2017-06-12_"$tag"_prokka --force --addgenes --gcode 11 "$file"; done
```

`${file%.fna}` is a neat trick in bash, a parameter expansion: http://www.tuxarena.com/2014/11/bash-10-examples-of-parameter-expansion/

If this one-liner is too complicated just copy it into a script (as described by @dutchscientist) and introduce a newline for each ';'. Of course, you could then make it more usable by e.g. passing the input file directory to the script as an argument, but that's up to you.

Cheers

**Comment by dutchscientist** [comment]
Ah, that goes way beyond my amateur status! Thanks :)

**Comment by aleimba** [comment]
whatever works :wink: and you're welcome!

**Comment by dutchscientist** [comment]
That should give @mmrec enough options? I am going to try @aleimba 's trick, that may be a lot easier to teach new users than my cumbersome spreadsheet :+1:

**Comment by mmrec** [comment]
Thanks a lot - will try both options!

**Comment by tseemann** [comment]
Thank you @aleimba @dutchscientist for helping @mmaesaar :)

**Comment by EddieGenius** [comment]
How do I annotate multiple .fasta using prokka?
