### ISSUE TITLE
Prokka annotation missed some sequences?

### ISSUE THREAD

**Issue by JennyLind** [tseemann/prokka#239]
Hey all,

I used Prokka to annotate some genomes. 
When I looked at the output .ffn file not all sequences were annotated. There were pieces of some contigs still annotated with the contigNr. But there are genes annotated that belong to this contig. 
The genes that are annotated are properly number so no number is missing due to this. 
But I was wondering why this happens?

Thanks in advance!

**Comment by tseemann** [comment]
I am not sure what you mean by "not annotated".   Do you mean you know there is a gene there but Prokka does not find it? Or do you mean there is something inconsistent between different output files of Prokka?

**Comment by JennyLind** [comment]
I do not know if there is a gene, but I do not know either why a sequence is outputted with the contig name?
Is it then because there is no gene in that piece of the contig?

**Comment by ealdraed** [comment]
Hello @JennyLind,

let us start by first asking you, what version you were running and what the command was that you used to invoke prokka. Then maybe also give us an example of such a contig (name).

The \*.ffn contains the (annotated) ORFs in nucleic acid alphabet (as opposed to \*.ffa which is amino acid alphabet). The actual contigs are in \*.fna/\*.fsa.

**Comment by JennyLind** [comment]
@ealdraed  I am using Prokka 1.11. And the used command was, i used a loop for multiple fna files:
for i in *.fna; do prokka --cpus $(nproc) --kingdom Bacteria --outdir Prokka --force --prefix ${i%.fna} $i; done

And the contig names are "accn|AVAQ01000001", "accn|AVAQ01000002", etc

I also uploaded a screenshot of a part of the ffn output.

![prokkaoutput_ffn](https://user-images.githubusercontent.com/29659593/27531858-6a1ab862-5a5e-11e7-9309-2c9cc2550fb3.png)

**Comment by ealdraed** [comment]
Thank you for the further information. The problem you are experiencing is related to #155 and was fixed in this [commit](https://github.com/tseemann/prokka/commit/dbf9c74f4636ee2ea584b4b5fc8f011ad3c03ff8).

What happens is, that tbl2asn silently fails and the further commands that rely on its output cannot proceed. You should have a look at your *.log files and see, that prokka actually did not complete properly.

I highly recommend that you upgrade to v. 1.12!

**Comment by JennyLind** [comment]
Thanks!! I already updated to 1.12 and saw that the problem did not occur anymore.

**Comment by tseemann** [comment]
@ealdraed - thank you for helping answer @JennyLind question, appreciated!

yes, Prokka 1.12 has **many** bug fixes over 2 years, and no one should be using 1.11 anymore.
