### ISSUE TITLE
How does Prokka predict hypothetical proteins?

### ISSUE THREAD

**Issue by b-tierney** [tseemann/prokka#240]
Forgive me if this is a simple question, but how does Prokka go about deciding to call something a hypothetical protein? I had assumed it simply looked for start and stop codons + a certain length of sequence, but now I'm seeing a number of sequences with stop codons inside them, so this probably isn't the case. 

In any case, is there any setting that would allow me to search simply based on start/stop sites? Thanks so much.

**Comment by mherold1** [comment]
Prokka uses prodigal to predict coding sequences: https://github.com/hyattpd/prodigal/wiki/introduction
The issue with the stop-condons within the protein sequences has been mentioned before: #203

**Comment by tseemann** [comment]
Thank you @mherold1 for answering the question.   

What version of Prokka are you using?    
Can you send the log file or the FASTA file and settings you used?

**Comment by dutchscientist** [comment]
Are you looking at Mycoplasma's or other bacteria which may use a different translation table?

**Comment by b-tierney** [comment]
I'm so sorry about the slow response!! Thank you so much for getting back to me, the mherold1's answer cleared this up for me. I'm not looking at any Myco's or otherwise unusual microbes, but that's a great point. Thanks again everybody, and apologies for not closing this out sooner.

**Comment by willnotburn** [comment]
Does prokka successfully navigate what sounds like prodigal's shortcomings? How does it resolve the stop codon inside CDS issue https://github.com/tseemann/prokka/issues/203 referenced by @mherold1

**Comment by Guanguan8** [comment]
@dutchscientist ，I'm looking at Mycoplasma's，How to solve it？
Thanks.

**Comment by dutchscientist** [comment]
For Mycoplasma you need to define the translation table. Mycoplasma uses translation table 4.

The switch in the Prokka command line is --gcode 4
