### ISSUE TITLE
Prokka manual not located in /docs/ folder

### ISSUE THREAD

**Issue by transcript** [tseemann/prokka#242]
When running the simple command "prokka --docs" to pull up the manual, it fails, as the manual is not located in the docs/ folder.

Seems to be an easy enough fix; re-add the manual to this folder, or change the "--docs" command.

**Comment by tseemann** [comment]
Nice find!  Even I'd forgotten about that `--docs` command. That was before Prokka was in github. I can now convery from markdown to plaintext with pandoc so  so `--docs` works again.

Thanks for the report!
