### ISSUE TITLE
stop tbl2asn?

### ISSUE THREAD

**Issue by b-tierney** [tseemann/prokka#246]
Hi again,
I know I just closed issue, but I came up with another question. I'm running prokka in parallel in the cloud and not using the results of tbl2asn – it's the longest step in the process, though; is there any easy way to comment it out from your code? Figured I'd ask before spending a lot of time trying to grok it myself.
Thanks,
Braden

**Comment by jklynch** [comment]
I recently removed the tbl2asn step from some analyses because it was taking a very long time. The input files were large so I guess that's fair, but it would be helpful to me as well if there were an easy way to disable the tbl2asn step. I put a do-nothing script called 'tbl2asn' earlier in my PATH than prokka which is a terrible hack an results in an error, but otherwise does the job.
Thanks!

**Comment by tseemann** [comment]
@b-tierney it's unusual to take that long, unless you have 1000s of contigs, like a metagenome. Is that the case?

@jklynch your "hack" is perfectly acceptable :)

As for `tbl2asn` I hate it and I am trying to replace it with other code, or perhaps just stop providing `.gbk` output files.

**Comment by b-tierney** [comment]
Hi,
Yep, working with lots of metagenomic data.

Will try what @jklynch recommended. Much thanks for the advice! 

Really appreciate your guys' responses.

**Comment by jklynch** [comment]
Hello,
I forked prokka to add a command line argument '--notbl2asn' that will bypass tbl2asn. This is much better than my previous method but still not great. Maybe it will work for you, too @b-tierney. It's at https://github.com/hurwitzlab/prokka.

**Comment by b-tierney** [comment]
Thank you @jklynch, apologies for missing this. Really appreciate the help, it'll come in handy.

**Comment by alexgraehl** [comment]
The "--no-tbl2asn" idea is an amazing one!

I would love to see that integrated into main-line prokka!

I am SO annoyed by the tbl2asn message: "This copy of tbl2asn is more than a year old.  Please download the current version."—why would anyone ever write a program like that, I wonder? The fact that it exits with a non-zero exit code and breaks any error handling you might have in a pipeline is just insult to injury.

**Comment by alexgraehl** [comment]
In the meantime, one hack to avoid using tbl2asn is to make your "tbl2asn" this file:

#!/bin/bash
echo "tbl2asn 99.99" # fake version number so PROKKA detects a version number

If you don't put the 'echo' part in there, then prokka will say "hey, this isn't a valid version of tbl2asn!"
