### ISSUE TITLE
prokka prodigal different gene prediction  

### ISSUE THREAD

**Issue by luciagrami** [tseemann/prokka#251]
Hello, 

I would like to know why there are differences between the number of genes predicted with prodigal and those predicted with prodigal when using prokka.
Is there a step where genes with certain characteristics are removed?

Thanks!

**Comment by tseemann** [comment]
If you look at the main `prokka` script you can see it uses various options that may be different to yours:

```
my $prodigal_mode = ($totalbp >= 100000 && !$metagenome) ? 'single' : 'meta';
my $cmd = "prodigal -i \Q$outdir/$prefix.fna\E -c -m -g $gcode -p $prodigal_mode -f sco -q";
```

Also, some CDS are removed if they overlap tRNA or rRNA features.
