### ISSUE TITLE
PROKKA_mmddyyyy.tsv contains different number of tabs

### ISSUE THREAD

**Issue by Kirk3gaard** [tseemann/prokka#260]
Running Prokka (v1.12) I discovered that the header of PROKKA_mmddyyyy.tsv  contains five elements (locus_tag	ftype	gene	EC_number	product), but not all rows contain five elements or even enough tabs (\t) to make it a proper table. 

For a gene classified as "hypothetical protein" there are only two tabs, but for rows with full info there are four e.g.:

locus_tag	ftype	gene	EC_number	product
MHLIDFIL_00001	CDS	mog	2.7.7.75	Molybdopterin adenylyltransferase
MHLIDFIL_00002	CDS	hypothetical protein

I know this is a minor thing but it just stroke me as a bit odd. Thank you very much for a great tool.

**Comment by Kirk3gaard** [comment]
A small addition to the tsv could be a column with gene size to allow comparison of CDS size to the reference gene length. Especially relevant with assemblies produced from data that includes many in/del errors.

**Comment by tseemann** [comment]
@Kirk3gaard this was reported in https://github.com/tseemann/prokka/issues/250 and is fixed in the git version. If you do a `git clone` and use that instead of the 1.12 tar.gz file it will be fixed.

Can you file the other suggestion as a separate issue? Thanks.
