### ISSUE TITLE
[feature suggestion] Choose which files Prokka generates

### ISSUE THREAD

**Issue by dutchscientist** [tseemann/prokka#263]
I use Prokka primarily to generate rapid, consistent annotations for downstream investigations, not so much for Genbank submissions or public release of the files. That means that I have no need for several of the files generated by Prokka.

In my case I only keep:
- faa, ffn, fna, gff, gbk and txt

Log and err are useful for troubleshooting.

However, I have no need for:
- sqn, tbl, tsv, fsa
so I delete these afterwards.

Very low priority of course, but it would be nice to be able to shave off some time per genome if those files are not generated? Or are they intermediates in generating other files? I don't know enough of the process.

I could think of "profiles" like you use in the manual (I like "crazy person"!)?

**Comment by tseemann** [comment]
tbl, fsa, sqn are by-products of the GBK file.
tsv does not take any computation time, relatively.

in my pipelines i just wrap prokka and delete those files afterwards, in the shell script etc.

i am not making any major changes to prokka 1.x at this stage i'm afraid.

**Comment by dutchscientist** [comment]
No worries, just a thought :-)
