### ISSUE TITLE
Failure to install prokka

### ISSUE THREAD

**Issue by JustinaMoon** [tseemann/prokka#265]
Hello,

I am trying to install prokka on my Mac High Sierra 10.13.1
and having some trouble while following the installation instruction.

It says
> dylid: Library not loaded
> Reason: image not found
[16:19:45] Could not determine version of makeblastdb - please install version 2.2 or higher

I have tried the installation using Homebrew as well
but I keep failing with this error:
> Error: Could not create /usr/local/Cellar
> Check you have permission to write to /usr/local

I've already tried these but none of them are working with the error "Operation not permitted":
> $ sudo chown -R $USER /usr/local
> $ sudo chown -R $(whoami) /usr/local
> $ sudo chmod g+w /usr/local
> $ sudo chgrp staff /usr/local

Can anyone help this error please?
Thanks.

**Comment by JustinaMoon** [comment]
Somehow I tried
> $ sudo chown -R $(whoami) $(brew --prefix)/*

And it seemed to work because after that I tried again brew install and got this:
> ==> Installing prokka from homebrew/science
> minced: Java 1.8 is required to install this formula.
> JavaRequirement unsatisfied!
> 
> You can install with Homebrew-Cask:
>   brew cask install java
> 
> You can download from:
>   https://www.oracle.com/technetwork/java/javase/downloads/index.html
> Error: An unsatisfied requirement failed this build.

So, I installed Java
> 🍺  java was successfully installed!

However even after the java installation, I still get the same error saying java installation required if I try brew install.

**Comment by tseemann** [comment]
Is your `$(brew --prefix)/bin` folder the first thing in your `PATH` ?

`echo $PATH`

**Comment by JustinaMoon** [comment]
Here is:
> $ echo $PATH
> /usr/local/bin:/bin:/usr/X11R6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

And brew doctor said:
> $ brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: Python is installed at /Library/Frameworks/Python.framework
> 
> Homebrew only supports building against the System-provided Python or a
> brewed Python. In particular, Pythons installed to /Library can interfere
> with other software installs.
> 
> Warning: You have MacPorts or Fink installed:
>   /opt/local/bin/port
> 
> This can cause trouble. You don't have to uninstall them, but you may want to
> temporarily move them out of the way, e.g.
> 
>   sudo mv /opt/local ~/macports

So I tried
> $ sudo mv /opt/local ~/macports

But nothing happens and still the same error saying java installation

**Comment by JustinaMoon** [comment]
I reinstalled java8 with my friend's help and it seemed to make some progress.

`$ brew install prokka --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (caskroom/cask, caskroom/versions, homebrew/core).
==> Deleted Formulae
bchunk

==> Installing prokka from homebrew/science
==> Installing dependencies for homebrew/science/prokka: blast, infernal, minced, parallel, prodigal, tbl2asn
==> Installing homebrew/science/prokka dependency: blast
==> Downloading https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-src.tar.gz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/master/blast/blast-make-fix2.5.0.diff
######################################################################## 100.0%
==> Patching
==> Applying blast-make-fix2.5.0.diff
missing header for unified diff at line 3 of patch
patching file c++/src/build-system/Makefile.in.top
==> ./configure --prefix=/usr/local/Cellar/blast/2.6.0_2 --libdir=/usr/local/Cellar/blast/2.6.0_2/libexec --without-debug --with-mt --without-boost --without-mysql --without-freetype --without-gnutls --with-pcre=/usr/local/opt/pcre --without-hdf5 --with-dll --without-static --withou
==> make


==> make install
==> Caveats
Using the option "--with-static" will create static binaries instead of
dynamic. The NCBI Blast static installation is approximately 7 times larger
than the dynamic.

Static binaries should be used for speed if the executable requires fast
startup time, such as if another program is frequently restarting the blast
executables.
==> Summary
🍺  /usr/local/Cellar/blast/2.6.0_2: 176 files, 76MB, built in 10 minutes 59 seconds
==> Installing homebrew/science/prokka dependency: infernal
==> Downloading http://eddylab.org/software/infernal/infernal-1.1.2.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/infernal/1.1.2
==> make
==> make install
🍺  /usr/local/Cellar/infernal/1.1.2: 25 files, 17.5MB, built in 1 minute 7 seconds
==> Installing homebrew/science/prokka dependency: minced
==> Downloading https://github.com/ctSkennerton/minced/archive/0.2.0.tar.gz
==> Downloading from https://codeload.github.com/ctSkennerton/minced/tar.gz/0.2.0
######################################################################## 100.0%
==> make
🍺  /usr/local/Cellar/minced/0.2.0: 9 files, 1.6MB, built in 7 seconds
==> Installing homebrew/science/prokka dependency: parallel
==> Downloading https://homebrew.bintray.com/bottles/parallel-20171022.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring parallel-20171022.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/parallel/20171022: 61 files, 3MB
==> Installing homebrew/science/prokka dependency: prodigal
==> Downloading https://github.com/hyattpd/Prodigal/archive/v2.6.3.tar.gz
==> Downloading from https://codeload.github.com/hyattpd/Prodigal/tar.gz/v2.6.3
######################################################################## 100.0%
==> make
🍺  /usr/local/Cellar/prodigal/2.6.3: 7 files, 26.8MB, built in 8 seconds
==> Installing homebrew/science/prokka dependency: tbl2asn
==> Downloading https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/mac.tbl2asn.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 429d63ee3c36d1f2f6322c62c6089d5ee8a8b089e5cc9373e298e017bcbbb9ec
Actual: 35632173046c3b43104ec7c9652006f71ffbbbb2959d53919ad85b0bf3060581
Archive: /Users/user/Library/Caches/Homebrew/tbl2asn-25.3.gz
To retry an incomplete download, remove the file above.
`

Of course I tried to remove the file but still it gives the same error "SHA256 mismatch"

**Comment by tseemann** [comment]
@JustinaMoon can you do `brew install brewsci/bio/tbl2asn` then try and reinstall everything?
Also, do `brew tap brewsci/bio`
