### ISSUE TITLE
Prokka without gene-prediction?

### ISSUE THREAD

**Issue by moritzbuck** [tseemann/prokka#268]
Hi!
I was just wondering if there is an option of running prokka without gene-predcition. I basically have already predicted genes, and would just like prokka's really nice annotations for them. 
your I have looked but found nothing... maybe I just missed it ... Anyhow, just asking before I start hacking away on your perl script!

regards,

Moritz

**Comment by tseemann** [comment]
@moritzbuck no, prokka isn't that modular unfortunately.  I believe you might want something like RATT  (from Sanger Pathogens) or i recall something being in Anvio for this maybe http://merenlab.org/software/anvio/

**Comment by moritzbuck** [comment]
Thanks! Not of actuality anymore but might have to come back to this one day!
