### ISSUE TITLE
timeframe for migrating prokka to Homebrew/core

### ISSUE THREAD

**Issue by EpiBlake** [tseemann/prokka#274]
Hello, with the depreciation of Homebrew/science do you have a timeframe for getting Prokka migrated to Homebrew/core? Thanks!

**Comment by tseemann** [comment]
Prokka is heading to `brewsci/homebrew-bio` most likely.

https://github.com/brewsci/homebrew-bio/

The Perl dependencies are causing issues, we are working on it.
