### ISSUE TITLE
Using pan-genome (or something alike) with --proteins? 

### ISSUE THREAD

**Issue by apredeus** [tseemann/prokka#277]
I was experimenting with using curated annotations as a reference for Prokka, and was curious what happens if you have several proteins with different IDs that all perfectly match the identified CDS? My idea was to take several well-annotated genomes and annotate the most genes, and with maximum accuracy in terms of name assignment (using something like majority-vote). 

On a separate note, I've generated a file with each sequence name looking like this: 

> \>STM_1234 ~~~thrA~~~some info here

and Prokka still refuses to use thrA as a "Name" for the feature. At the same time, it works with a regular genbank file. What is the exact format it's expecting? What am I missing here?

**Comment by tseemann** [comment]
@apredeus  Your idea is sound, and what we do here.   Your format looks fine.
```
>SeqID EC_number~~~gene~~~product
```
https://github.com/tseemann/prokka/blob/master/README.md#fasta-database-format

Are you using this via `--proteins` ?
Looking at the code, it might need to have an file extension that Bioperl understands as being 'fasta' as that is how it guesses the format. Try ensuring your DB files ends with `.fasta` and see if that helps.

Prokka is 'dumb'.  It searches different databases in the order of (--proteins, --genus, in built SPROT, then the HAMAP HMM etc).  If it matches your one exacrtly in proteins it should annotate it as such.
ASSUMING that Prodigal actually finds the gene that is.

**Comment by apredeus** [comment]
Thank you. Yes, I am using it with `--proteins`. I was confused by the fact that if "product" field is "hypothetical conserved protein", then "gene" field is ignored, even if it is present in the annotation. I've used it to add locus tags from other annotations - e.g. STM tags from Salmonella, which could be much more useful, then no name at all.

As for the order - thank you, that's what I have thought. What was my concern is that "gene names" appear to be a tremendous mess in a prokaryotic world (to which I am fairly new). Apparently if something is called "X" in NCBI annotation there's really no guarantees that's what it would be called in bunch of other annotations. So I was trying to find a way to mitigate this.

**Comment by tseemann** [comment]
I think `hypothetical conserved protein` is not a valid product in Genbank, so Prokka will convert it to `hypothetical protein` which will erase any `/gene` tag.

You can use `--rawproduct` to avoid this (I think).
