### ISSUE TITLE
No .gbk file produced after prokka

### ISSUE THREAD

**Issue by Anuravi123** [tseemann/prokka#279]
Hello,

I have been using Prokka for a while but now suddenly, I do not get any .gbk files but all other files are there. Could you please help me with this. 

Also, if there anyway I can convert the existing files to .gbk?

Thanks!

Anu

**Comment by ytanizaw** [comment]
Same thing happened to me recently. It is most likely because tbl2asn program expired. It only works within 1 year after the release.
Pleas check the log file.

Download the latest tbl2asn from the NCBI website and replace the old one, which is located in the binaries folder of prokka.

Yasu

**Comment by Anuravi123** [comment]
yes it worked! thanks!
