### ISSUE TITLE
option --rawproduct

### ISSUE THREAD

**Issue by PavlaDe** [tseemann/prokka#280]
I ran Prokka twice once with and once without the --rawproduct option. Unfortunately I get the same output. I would need any COG or EC Identifiers for my downstream analysis. Prokka finds all coding regions and tRNA or tmRNA and my log file confirms that the annotation finished successfully. 
This is the command I ran: 
prokka --outdir Prokka_FL_2 --prefix FL_Annot_2 --metagenome FL_contigs.fa --rawproduct

Thank your for any advice.

**Comment by tseemann** [comment]
You are using the default database, which is the small `sprot` database.  If there is an `/EC_number` it will be in the GBK and GFF outputs.  It will never be in the FASTA output. As for COGS, they are not in the database.

All `--rawproduct` doesn't try to 'clean up' the `/product` line, but EC and COG are not in that.  It's mainly for when you provide or make your own database.
