### ISSUE TITLE
Where to find latest tbl2asn (2018)?

### ISSUE THREAD

**Issue by burgsdorf** [tseemann/prokka#281]
The ftp link (ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/) contains versions out of date. Do you have any solution? Thanks!

**Comment by andersgs** [comment]
Hi.

According to `ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/DOCUMENTATION/VERSIONS` the latest version of `tbl2asn` is 25.6.

I just checked the Linux64 bit and the Mac OS version on the site `ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/` are 25.6. These were added on 14 December 2017.

Are you looking for a different version?
