### ISSUE TITLE
sudden Bioperl error after over 24hours running on the cluster

### ISSUE THREAD

**Issue by willnotburn** [tseemann/prokka#282]
Hello!

PROKKA seems to have been running for over a day, and has detected a bunch of things, but there's a warning at the end of the log file. What's that all about?

Prokka for a megahit assembly `final.contigs.fa`

```
grep -o '^[^ ]\+' final.contigs.fa > final.contigs.grep.fa

prokka --metagenome --cpus 20 final.contigs.grep.fa 2>_prokka.log
```

Error message at the end of _prokka.log
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: start is undefined
STACK: Error::throw
STACK: Bio::Root::Root::throw /opt/software/Bioperl/1.6.901--GCC-4.4.5/share/perl5/Bio/Root/Root.pm:472
STACK: Bio::RangeI::overlaps /opt/software/Bioperl/1.6.901--GCC-4.4.5/share/perl5/Bio/RangeI.pm:229
STACK: /opt/software/prokka/1.7--GCC-4.4.5/bin/prokka:547
```
Paul

**Comment by tseemann** [comment]
Sounds like a bioperl bug.  You are on an old version, it has been on 1.7 for a while now. Maybe your HPC can upgrade it?

I would suggest breaking up your huge metagenome .fasta file into smaller chunks and running them in parallel on your HPC. Just make sure there is a mix of big and large contigs in each chunk to help Prodigal find genes.    There won't be any real loss in results if you do this.

Sorry I can't help any more than that.
