### ISSUE TITLE
unable to test or invoke prokka 

### ISSUE THREAD

**Issue by mistaRam** [tseemann/prokka#286]
When running on Ubuntu and Mac OS X High Sierra termini, I cannot invoke 'prokka' from the command line. When typing 'prokka' I am greeted with: 

No command 'prokka' found, did you mean:
Command 'propka' from package 'pdb2pqr' (universe) 
prokka: command not found

Is there a way to resolve this?

**Comment by tseemann** [comment]
How did you install it?
Did you add the prokka folder to your `PATH` ?
Can you change into the prokka folder and run `./bin/prokka` ?

**Comment by vmevada102** [comment]
I am also having same probelm while installing and running prokka in  Ubuntu 16. 

I had install the prokka github clone. 
Please help me to run this in my ubuntu based pc.

**Comment by tseemann** [comment]
Did you follow all the steps here:

https://github.com/tseemann/prokka#installation

If so, what error did you get?

**Comment by vmevada102** [comment]
Yes its working in local pc. But as i am trying to running this in Galaxy server. it shows error like tbl2asn is old one. 

I had tried to replace with newver version. but same error generated

**Comment by bell-samantha** [comment]
I am having the same issue. I installed with the steps from the GitHub page. I can run ./bin/prokka from the prokka folder and see the options, but when I type 'prokka' or 'prokka --help', etc, there is this same error: No command 'prokka' found, did you mean:
 Command 'propka' from package 'pdb2pqr' (universe)
prokka: command not found

**Comment by tseemann** [comment]
@vmevada102 prokka in galaxy is nothing to do with me. are you using the latest galaxy with the new Conda based installation system?   @slugger70

**Comment by tseemann** [comment]
@bell-samantha you will need to add the prokka "bin" folder to your PATH. Read https://kb.iu.edu/d/acar

Or install using Brew or Conda.

**Comment by asimbepari** [comment]
Could you please help?
I am also unable to run prokka.
I followed the following steps:
sudo apt-get install libdatetime-perl libxml-simple-perl libdigest-md5-perl git default-jre bioperl
sudo cpan Bio::Perl
git clone https://github.com/tseemann/prokka.git $HOME/prokka
$HOME/prokka/bin/prokka --setupdb

I am attaching a screenshot.
![prokka-does-not-run](https://user-images.githubusercontent.com/57698038/116809644-d8f3d280-ab60-11eb-860e-1ea2e8eb7c3a.png)
