### ISSUE TITLE
no tsv file

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tseemann/prokka#288]
I used the Prokka 1.12-beta and following command, but there is no tsv file generated, the others are normal, I have no idea about it, anybody can give me a help, thanks in advance

prokka --prefix 17D0587439 --locustag 17D0587439 --addgenes --addmrna --plasmid Plasmid --gcode 11 --outdir 17D0587439 my.scaftig

**Comment by em9** [comment]
I have had the same exact issue.  All other files are normal, but no .tsv file generated

**Comment by tseemann** [comment]
That feature is part of Prokka 1.12  which has been out for 1 year:

https://github.com/tseemann/prokka/releases

You need to upgrade from the Beta version.
