### ISSUE TITLE
Differing thresholds

### ISSUE THREAD

**Issue by russianconcussion** [tseemann/prokka#299]
Hi,

Is there a way to set different thresholds for each layer of the annotation process, such as an e-value threshold of 1e-5 for the HMM search and a lower e-value threshold of 1e-30 for the BLAST search?

**Comment by tseemann** [comment]
There is not a way from the command line, no.
Prokka 2.x will make customising databases much simpler, including cutoffs.

But you can replace the `%e` in the lines below in the `bin/prokka` script:

```
my $BLASTPCMD = "blastp -query - -db %d -evalue %e -num_threads 1 -num_descriptions 1 -num_alignments 1 -seg no";
my $HMMER3CMD = "hmmscan --noali --notextw --acc -E %e --cpu 1 %d /dev/stdin";
```

**Comment by russianconcussion** [comment]
Thank you!
