### ISSUE TITLE
command --outdir not found

### ISSUE THREAD

**Issue by bv2810** [tseemann/prokka#302]
hi,

when trying to run Prokka for the first time it resulted in two error messages: the first being "can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: ... and here it shows some directories.)" I checked and XML is installed and placed in one of the directories.
The second being "--compilation aborted at line 27" and --outdir: command not found.
Any idea how I can solve this?

Thanks in advance

**Comment by tseemann** [comment]
How did you install Prokka?

Are you using version 1.13 ?

The XML simple included with Prokka does not work. You'll need to install it via CPAN or install the RPM or Debian package in the instructions.

**Comment by bv2810** [comment]
I tried installing it via the command line, like it is explained in the installation instructions. Sadly this didn't go as planned so I downloaden it manually. I also installed the XML simple via cpan.
But installing prokka manually might not have been the best idea since typing "prokka" in the command line or the --setupdb step both show No command 'prokka' found

**Comment by tseemann** [comment]
You will need to learn about the `PATH` and its meaning in Unix.

Perhaps this is a good starting point: https://kb.iu.edu/d/acar
