### ISSUE TITLE
Empty .fna

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [tseemann/prokka#306]
Hello,
I am encountering a weird issue, where the .fna file is empty. It is empty at the end of  the whole process, but more importantly it seems to be empty before starting aragorn. From the log aragorn run in less than a second for 452898954 bp. Also, running aragorn myself on, for instance .fna outputed by prodigal takes way more times and flag some genes.
Here are the logs [prokka.log](https://github.com/tseemann/prokka/files/2006015/prokka.log)
Hence a lot of error message ensue with no result at the end. 
Any idea?
Thanks

**Comment by tseemann** [comment]
```
 Wrote 1,415,152 contigs totalling 452,898,954 bp.
```
Do you have enough RAM on your computer?
Most of these tools were not designed for 500 Mbp metagenomes with 1.5 million contigs!
I would filter out all your small contigs < 500 bp say and see if that works.
You can also split the fasta into 10 smaller ones and run each one separately then join at the end.

**Comment by Sebastien-Raguideau** [comment]
Hello,
Yes, I do, we have a whole lot of ram ~ 3 T.  We have 2 such server setup in the same way and yielding the same "bug". I tried with a virtual machine and it works. So technically I can still make prokka work on my dataset, but still I would like to understand what is happening and ultimately having it working on the servers.

**Comment by tseemann** [comment]
If it works on a VM but not on your cluster, then there is not much i can do.  Most clusters require you to tell the job scheduler how much RAM you will be using, maybe that is too low.

**Comment by Sebastien-Raguideau** [comment]
Hello,
Pretty sure it is not a ram issue. It is not cluster with a job scheduler, it is a big server with 3T ram and 192 core. I am still a bit annoyed at not understanding why it is not working. But I suppose that as long as I can make it work one way or another, it is okay. 
Thanks for the answers.
