### ISSUE TITLE
tbl2asn dependency

### ISSUE THREAD

**Issue by AlnMetTyr** [tseemann/prokka#307]
Hi
I'm trying to use Prokka for annotating bacterial genomes. In installing PROKKA I keep having issues with the tbl2asn dependency.
If I install on a linux server as a conda environment and run I get the error that tbl2asn cannot run
[16:38:31] Running: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z annotation\/PROKKA_05242018\.err -i annotation\/PROKKA_05242018\.fsa 2> /dev/null
[16:38:40] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.12 from https://github.com/tseemann/prokka' -Z annotation\/PROKKA_05242018\.err -i 626annotationf\/PROKKA_05242018\.fsa 2> /dev/null

I have also tried to install on MAC terminal using the homebrew packaging software and all seems to install fine until I get this at the tbl2asn installation:
==> Installing brewsci/bio/prokka dependency: tbl2asn
==> Downloading https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_progra
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c79416ff5fea23baf4ac10ff1a67f7f6e099980a45ac878f649821ba7b68788b
Actual: 652fe613c276ac5c7998bf3752c422ea6ac54fd79a31868cda3085e93285206f
Archive: /Users/AlnMetTyr/Library/Caches/Homebrew/tbl2asn-25.6.gz
To retry an incomplete download, remove the file above.

Im not sure if theres a way to rectify this or if this will have any implications on my annotations? I'd like to be able to run on my home mac but currently this is seeming like a problem!
Thanks!

**Comment by tseemann** [comment]
it appears NCBI have changed the binaries on their website, but not changed the version.

They have also updated the libidn from .so.11 to .so.12 which can not be provided by Linuxbrew.

I feel they do this only to punish me and other Prokka users.

Currently your only option is to download the binary yourself and see if you put it in your PATH somewhere:
https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/

**Comment by AlnMetTyr** [comment]
thank you! I resolved this issue using bio-conda by:
wget -O tbl2asn.gz ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz
gunzip tbl2asn.gz
chmod +x tbl2asn
cp tbl2asn ./home/usr/conda-envs/prokka/bin/tbl2asn

Seems to now be working perfectly

**Comment by kevinxchan** [comment]
I ran into this issue on macOS with homebrew, so here's a (temporary) workaround similar to @AlnMetTyr 
```
wget -O tbl2asn.gz ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/mac.tbl2asn.gz
gunzip tbl2asn.gz && chmod +x tbl2asn
mkdir -p /usr/local/Cellar/tbl2asn/25.6/bin/ && mv tbl2asn /usr/local/Cellar/tbl2asn/25.6/bin/

mkdir -p /usr/local/opt/tbl2asn
ln -s /usr/local/opt/tbl2asn/ ../Cellar/tbl2asn/25.6/
brew install prokka
```
Now check if the installation was successful with `prokka --help`.
