### ISSUE TITLE
MSG: Can't build a GFF object with the unknown version 3

### ISSUE THREAD

**Issue by huoww07** [tseemann/prokka#309]
I used to be able to run prokka with no problem but recently this error message keeps popping up:
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Can't build a GFF object with the unknown version 3
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/wenwen/Work/cgview_comparison_tool/lib/bioperl-1.2.3/Bio/Root/Root.pm:342
STACK: Bio::Tools::GFF::new /home/wenwen/Work/cgview_comparison_tool/lib/bioperl-1.2.3/Bio/Tools/GFF.pm:115
STACK: /home/wenwen/Work/prokka-master/bin/prokka:675
-----------------------------------------------------------
I wonder how to solve this.

**Comment by tseemann** [comment]
Your bioperl is over 10 years old!

You need to upgrade to the required 1.6 or higher.

**Comment by lskatz** [comment]
I suggest a line in prokka, something like

```
if($Bio::Root::Version::VERSION < 1.006){
  die "ERROR: you need BioPerl version 1.006 or above. Please install the latest version.  See docs.bioperl.org for more details"
}
```

(maybe I should do this for myself too)

**Comment by huoww07** [comment]
Ooops...  you are right. It seems that the prokka is using bioperl from another location, I deleted it and now it's working fine! Thank you Seemann!!!

**Comment by tseemann** [comment]
@lskatz I already do have that ... but this must be a very old version of Prokka too!

@huoww07 please upgrade to 1.13 if you can!
