### ISSUE TITLE
failure to install install/run PROKKA

### ISSUE THREAD

**Issue by leonzayas** [tseemann/prokka#310]
Hi, I have spent the last few days trying to install and run PROKKA ( which I had successfully run in the past month) 

When I try to run it:

[root@bio-server-2 bin]# prokka -h
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /opt/anaconda3/bin/../perl5 /opt/anaconda3/lib/perl5/site_perl/5.18.2/x86_64-linux /opt/anaconda3/lib/perl5/site_perl/5.18.2 /opt/anaconda3/lib/perl5/5.18.2/x86_64-linux /opt/anaconda3/lib/perl5/5.18.2 .) at /opt/anaconda3/bin/prokka line 32.
BEGIN failed--compilation aborted at /opt/anaconda3/bin/prokka line 32.

then I looked 

[root@bio-server-2 bin]# cpanm -i Bio::Root::Version
Bio::Root::Version is up to date. (1.007002)

and I have tried re-installing BioPerl again

[root@bio-server-2 rleonzayas]# cpanm Bio::Perl
--> Working on Bio::Perl
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... OK
Configuring BioPerl-1.007002 ... OK
Building and testing BioPerl-1.007002 ... 
OK
Successfully installed BioPerl-1.007002
1 distribution installed

But I got the same error...

then I tired re-installing Bio::Root::Version

[root@bio-server-2 rleonzayas]# cpan install Bio::Root::Version
...
...
Files=325, Tests=19072, 48 wallclock secs ( 1.30 usr  0.37 sys + 42.38 cusr  5.38 csys = 49.43 CPU)
Result: FAIL
Failed 12/325 test programs. 19/19072 subtests failed.
  CJFIELDS/BioPerl-1.007002.tar.gz
  ./Build test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports CJFIELDS/BioPerl-1.007002.tar.gz
Running Build install
  make test had returned bad status, won't install without force

so I forced it ...
[root@bio-server-2 bin]# cpan --force install Bio::Root::Version
 ...
...
Result: PASS
  XSAWYERX/Storable-3.11.tar.gz
  /usr/bin/make test -- OK
Running make install
"/opt/anaconda3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Storable.bs blib/arch/auto/Storable/Storable.bs 644
Manifying 2 pod documents
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /opt/anaconda3/lib/perl5/site_perl/5.18.2/x86_64-linux/auto/Storable/Storable.so
Installing /opt/anaconda3/lib/perl5/site_perl/5.18.2/x86_64-linux/Storable/Limit.pm
Appending installation info to /opt/anaconda3/lib/perl5/5.18.2/x86_64-linux/perllocal.pod
  XSAWYERX/Storable-3.11.tar.gz
  /usr/bin/make install  -- OK

This is driving me insane, I'm probably doing something simple so wrong, please help!

**Comment by tseemann** [comment]
You seem to have anaconda in your PATH ?

Why not just `conda install -c bioconda -c conda-forge prokka` ?

Also, you seem to be force installing things as `root` user. You may have done damage to your Perl system which I will be unable to fix.

**Comment by leonzayas** [comment]
Thank you for your reply, originally that was my first option, well bc its the simplest, but it did not work either.. although when I tried again this time I got a different error message when trying to use conda 

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.4                |           py35_0         630 KB  conda-forge
    certifi-2018.4.16          |           py35_0         142 KB  conda-forge
    samtools-1.7               |                0         1.0 MB  bioconda
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following NEW packages will be INSTALLED:

    gettext:         0.19.8.1-0        conda-forge
    libiconv:        1.15-0            conda-forge

The following packages will be UPDATED:

    blast:           2.6.0-boost1.64_2 bioconda    --> 2.7.1-boost1.64_1 bioconda   
    ca-certificates: 2018.03.07-0                  --> 2018.4.16-0       conda-forge
    certifi:         2018.4.16-py35_0              --> 2018.4.16-py35_0  conda-forge
    conda:           4.5.4-py35_0                  --> 4.5.4-py35_0      conda-forge
    openssl:         1.0.2o-h20670df_0             --> 1.0.2o-0          conda-forge
    prokka:          1.13-0            bioconda    --> 1.13-1            bioconda   

The following packages will be DOWNGRADED:

    glib:            2.56.1-h000015b_0             --> 2.53.5-0          conda-forge
    gnutls:          3.5.17-0          conda-forge --> 3.5.15-0          conda-forge
    samtools:        1.7-1             bioconda    --> 1.7-0             bioconda   
    tbl2asn:         25.6-1            bioconda    --> 25.6-0            bioconda   
    zlib:            1.2.11-ha838bed_2             --> 1.2.8-3           conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.5.4          |  630 KB | ##########################################################7                    |  75% 
certifi-2018.4.16    |  142 KB | ###########################################################5                   |  76% 
samtools-1.7         |  1.0 MB | ##########################################################6                    |  75% 

ValueError('n (-0.0031737494109769226) cannot be negative',)
ValueError('n (-0.014070617664036944) cannot be negative',)
ValueError('n (-0.0019144567430953163) cannot be negative',)



Also, I realize that the force install was a desperate move. but I tried all the things that I thought of before it, and I could not solve it (next time I will get over my fear of posting here sooner ^_^). Could we try trouble shooting as if Perl is still working? If not I could re-compile the Perl system and try again

thank you again

**Comment by leonzayas** [comment]
oh, I ran conda install -c bioconda -c conda-forge prokka again and no error this time - weird

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.4.16          |           py35_0         142 KB  conda-forge
    conda-4.5.4                |           py35_0         630 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         772 KB

The following NEW packages will be INSTALLED:

    gettext:         0.19.8.1-0        conda-forge
    libiconv:        1.15-0            conda-forge

The following packages will be UPDATED:

    blast:           2.6.0-boost1.64_2 bioconda    --> 2.7.1-boost1.64_1 bioconda   
    ca-certificates: 2018.03.07-0                  --> 2018.4.16-0       conda-forge
    certifi:         2018.4.16-py35_0              --> 2018.4.16-py35_0  conda-forge
    conda:           4.5.4-py35_0                  --> 4.5.4-py35_0      conda-forge
    openssl:         1.0.2o-h20670df_0             --> 1.0.2o-0          conda-forge
    prokka:          1.13-0            bioconda    --> 1.13-1            bioconda   

The following packages will be DOWNGRADED:

    glib:            2.56.1-h000015b_0             --> 2.53.5-0          conda-forge
    gnutls:          3.5.17-0          conda-forge --> 3.5.15-0          conda-forge
    samtools:        1.7-1             bioconda    --> 1.7-0             bioconda   
    tbl2asn:         25.6-1            bioconda    --> 25.6-0            bioconda   
    zlib:            1.2.11-ha838bed_2             --> 1.2.8-3           conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2018.4.16    |  142 KB | ############################################################################## | 100% 
conda-4.5.4          |  630 KB | ############################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done

but error is the same:

[root@bio-server-2 rleonzayas]# prokka -h
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /opt/anaconda3/bin/../perl5 /opt/anaconda3/lib/perl5/site_perl/5.18.2/x86_64-linux /opt/anaconda3/lib/perl5/site_perl/5.18.2 /opt/anaconda3/lib/perl5/5.18.2/x86_64-linux /opt/anaconda3/lib/perl5/5.18.2 .) at /opt/anaconda3/bin/prokka line 32.
BEGIN failed--compilation aborted at /opt/anaconda3/bin/prokka line 32.

**Comment by tseemann** [comment]
I think you need to delete your whole conda installation and start from scratch.
I suspect the perl folders have been corrupted.
Do you have `/opt/anaconda3/bin` as the *first* entry in your PATH ?
Sorry, but I can't help any further. 
I think if you start clean, it will work in conda or brew.

**Comment by LakshmanTejaG** [comment]
run conda install perl=5.22.0 or export the path of perl 5.22 to .bashrc
