### ISSUE TITLE
parallel runs of split contigs creates duplicate gene_id

### ISSUE THREAD

**Issue by willnotburn** [tseemann/prokka#311]
Annotation of my entire assembly times out using max resources allowed on my cluster (single node). To circumvent this, I manually split the assembly, which was simply a `FASTA` collection of contigs, into many (86) parts and annotated each part separately. But now I am having trouble merging the results.

**Problem:** in each of the 86 output file sets, `gene_id` starts with `PROKKA_00001`, whereas each feature needs to have a unique identifier.

**Rough solution:** I can create `gene_id` manually. Contig headers were preserved, and some contigs have multiple CDS features. The manual `gene_id` could be in the format `[contig_number]_[contig_feature_number]` (e.g. `k141_100290_1`) and be unique for the entire assembly.

BUT I only have enough coding skills to do that for the `gff` files. Replacing `PROKKA_?????` with the new unique IDs in all output files in all 86 output folders is above my ability.

**Is there a way to assign `gene_id` based on contig numbers from the start?** Maybe PROKKA has `gene_id` naming options I'm simply not aware of.

**Comment by tseemann** [comment]
Just give each run a different `--locustag` prefix?

I think you must be using an older version of Prokka too, because current versions dynamically choose a unique `--locustag` based on a md5hash of the `contigs.fa` input file.
