### ISSUE TITLE
define prokka database from env or via parameter

### ISSUE THREAD

**Issue by kneubert** [tseemann/prokka#312]
Can you include the option to read the path of the prokka database either from an environmental variable or via a parameter?
for example instead of 
`my $DBDIR = "$FindBin::RealBin/../db";`
using
`my $DBDIR = $ENV{'PROKKA_DB'};`

I wrap Prokka into a KNIME node to build a _de novo_ assembly workflow (https://www.knime.com/). Therefore I want to enable the user to utilize his own database as input.

**Comment by tseemann** [comment]
@kneubert this is a good idea. i will implement soon.

**Comment by tseemann** [comment]
Prokka now has a `--dbdir` option.  It defaults to `$PROKKA_DBDIR` if set, or uses the `db/` folder relative to the installation folder as per previous versions.

Thanks for the idea.
