### ISSUE TITLE
Clarification regarding new locus tags

### ISSUE THREAD

**Issue by lfaller** [tseemann/prokka#313]
Hi all,

I recently upgraded from v1.11 to v1.13 and now the locus tags are different. The default used to be "PROKKA_07280" but now I find things like "BFHOMGCE_07280"

In the release notes for v1.12, I saw the following: 

"Better default unique locus_tag based on contig MD5"

Is "BFHOMGCE" part of an md5 hash describing the contig?

Thanks for clarifying!
~Lina

**Comment by tseemann** [comment]
Lina,

You can get the old behaviour simply by using `--locustag PROKKA` if you want.

But yes, we had problems where prople were annotations 1000s of genomes without setting `--locustag` or `--prefix` and then getting lots of conflicts. Also, when reannotating a new assembly of the same genome, the locus tags would also clash.

So, yes I do an MD5 hash of the *whole* contigs file, and use the first 8 hex digits to index to A-Z to get an 8 character unique locus tag for that contig file. If you re-annotate the exact same contigs file, you will get tge same locus tags.

I will leave this issue open to remind me to add this to the documentation.

Thanks for the question!

**Comment by lfaller** [comment]
Thanks for the clarification and your explanation for how you derive the MD5 hash!

**Comment by tseemann** [comment]
The key code is below. It seems I do G=0, H=1, .... ?=15 

```
  open my $fh, '<', $fname;
  my $md5 = Digest::MD5->new;
  $md5->addfile($fh);
  my $cs = $md5->hexdigest;
  close $fh;
  my $lt = '';
  for my $i (0 .. 7) {
    my $c = uc(substr($cs,$i,1));
    $c = chr( ord('F') + 1 + $c ) if $c =~ m/^\d$/;
    $lt .= $c;
  }
  msg("Setting --locustag ${lt} from MD5 $cs");
  return $lt;
```
