### ISSUE TITLE
 Could not run command: cmpress

### ISSUE THREAD

**Issue by zhibaosuo** [tseemann/prokka#314]
Error: File existence/permissions problem in trying to open CM file /usr/bin/../db/cm/Viruses.
CM file /usr/bin/../db/cm/Viruses not found (nor an .i1m binary of it)

[10:28:04] Could not run command: cmpress \/usr\/bin\/\.\.\/db\/cm\/Viruses

How to solve this problem?

**Comment by tseemann** [comment]
I need more information.
What version of Prokka?
How did you install it?
Please attach the `xxxxxx.log` file.

**Comment by zhibaosuo** [comment]
[wk@bogon bin]$ prokka -h
Option h is ambiguous (help, hmms)
Name:
  Prokka 1.12 by Torsten Seemann <torsten.seemann@gmail.com>

**Comment by zhibaosuo** [comment]
I install it followed the readme file

**Comment by tseemann** [comment]
That is not enough information for me to help, sorry.
I think you need to install the infernal package to get cmpress that works.
There are 3 methods to install.  Please use bioconda or brew.

**Comment by H440775h** [comment]
faced the sane problem, how did you you solved it
