### ISSUE TITLE
PROKKA detects fewer than half the features, compared with Prodigal alone

### ISSUE THREAD

**Issue by willnotburn** [tseemann/prokka#315]
I ran `PROKKA` and `Prodigal` (in an independent run) to detect CDS. The resulting `gff` file generated by `PROKKA` contains fewer than half the features than the `gff` file from `Prodigal`. I also manually checked out some contigs to confirm fewer features detected by `PROKKA`. The `PROKKA` log shows it used the same version of `Prodigal` I ran independently.

`PROKKA`: 5313886 CDS detected
`Prodigal`: 12330889 CDS detected

I am probably not understanding enough of under-the-hood of `PROKKA`. Does it impose additional quality filters to the ones default in `Prodigal`? Also (may be important): while I ran `Prodigal` on the entire assembly, `PROKKA` would take too long, so I split up the assembly into about 80 smaller parts, ran `PROKKA` on each split part separately, and then concatenated the results.

**Comment by tseemann** [comment]
Thank you @spock for the excellent answer.

Prodigal in Prokka is using different options to you.   Try `--metagenome` option.

```
  --metagenome       Improve gene predictions for highly fragmented genomes (default OFF)
```

**Comment by felipelira** [comment]
So, considering that PROKKA has the line:

#my $cmd = "prodigal -i \Q$outdir/$prefix.fna\E -c -m -g $gcode -p $prodigal_mode -f sco -q";

Change it just removing '-c' should give the same number of genes in comparison with the PRODIGAL output?

**Comment by tseemann** [comment]
I guess so, yes. Assuming same version of prodigal and same -g, -m, -p modes.

**Comment by thierryjanssens** [comment]
The --metagenome option does not result in the same behaviour as leaving out -c in the standalone prodigal version (tested with --kingdom Viruses).
Is there an option to include this as a new feature in the next version of prokka? This would be instrumental in the annotation of scaffold from a fragmented metagenome.
