### ISSUE TITLE
COG for custom genus database

### ISSUE THREAD

**Issue by vbonnici** [tseemann/prokka#316]
When I run an analysis with the default databases, several COGs are found.
However, when I build a custom genus db, using gbk files downloaded via NCBI, few COGs are found.
I think it depends on the fact that NCBI gbk files are poor of COG annotations, but how can I add or embed the information?

**Comment by tseemann** [comment]
NCBI files don't have any COGs as far as I know. The default database works from Uniprot, which does have them.

The next Prokka 1.15 will come with the option of a much larger database, including COGs.

Sorry I can't give you better news!
