### ISSUE TITLE
Prokka keep on stop at tbl2asn step

### ISSUE THREAD

**Issue by Juanli81** [tseemann/prokka#318]
Hi All,

I use Prokka to annotate my metagenome assembly, and it keeps stopping at the tbl2asn step, I tried to split the file into smaller ones, like 400 Mb, the problem still goes on.
Could anyone help me with this, I drop my log file here, with prokka 1.11.
[metat0-1.log](https://github.com/tseemann/prokka/files/2150859/metat0-1.log)
 Many thanks

Best regards
Juanli

**Comment by tseemann** [comment]
400 Mbp is still probably too big for poor old `tbl2asn`.

If you don't care about .gbk output (you still get .gff) you can just comment out the lines in prokka as discussed here: https://github.com/tseemann/prokka/issues/317

Prokka was just not designed for metagenomes - i am planning a new suitable version.

**Comment by Juanli81** [comment]
Thanks!
Is this means other files such as faa, are still can be used for protein and pathway analysis?
