### ISSUE TITLE
Annotated genes truncated/duplicated

### ISSUE THREAD

**Issue by csm1209** [tseemann/prokka#321]
Good day,

We're still investigating if this is being caused by an assembly or annotation issue, but I thought I would put this up to see if you knew anything about it. Throughout the entire genome, annotated genes seem to be truncated and are assigned multiple times. Here is one example:

![tsvccha3](https://user-images.githubusercontent.com/40922540/43003173-89425b6e-8bf9-11e8-9fa4-020d1b06dbb6.png)

When I BLAST aligned a few genes that were adjacent to each other here, I noticed that they aligned in succession with portions of a larger gene in a closely related species. This makes me think the annotation is mistakenly reading stop codons within the gene and truncating/splitting it up into separate genes.

Since this is my first time with genome annotation I'm not even sure if this is normal and if I'm meant to manually clean up the annotation myself. I'd like to know if this is like anything you've seen before and if you could possibly point me towards any solutions. If not, thanks anyway.

Carl

**Comment by tseemann** [comment]
Annotation is only a 'best guess'.  The gene predictor will not break up an ORF unless there has been a frameshift.  

What data was used for assembly?
If it involved Pacbio or Nanopore then these are likely homopolymer false frameshifts.

What software?

**Comment by csm1209** [comment]
Yes I did use Nanopore and Canu for assembly, and currently investigating it as an assembly error (not Prokka). You could be right that homopolymer false frameshifts are creating false stop codons and that's one of the things I'm looking into. So I don't think it's an issue with your software but thanks for pointing me in the right direction.

**Comment by tseemann** [comment]
You're welcome. I'm keen to make Prokka more robust in the face of modern homopolymer ridden assemblies.

**Comment by jotes35** [comment]
@csm1209 Did you resolve your issue? 

I have a similar issue with gene duplicates . My reads are oxford nanopore. And I need your advice on this . Thanks
