### ISSUE TITLE
problems about paokka

### ISSUE THREAD

**Issue by quliping** [tseemann/prokka#322]
error report details:
Time::Piece object version 1.12 does not match bootstrap parameter 1.20_01 at /usr/lib/perl5/5.10.0/x86_64-linux-thread-multi/DynaLoader.pm line 226.
Compilation failed in require at /home-fn/users/nsfn114_WH/software/source/Prokka/prokka-1.13/bin/prokka line 25.
BEGIN failed--compilation aborted at /home-fn/users/nsfn114_WH/software/source/Prokka/prokka-1.13/bin/prokka line 25.
Actually, my perl version is 5.26.2 and Time::Piece version is 1.3. The fact is that I installed it for the local user (instead of system wide, because the default version on the server is too old and I can't change the perl version on the server). But  now I think this software can only use the default perl version on the server instead of the new version that I installed for myself. Here is my perl path:
/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2
and the Time::Piece module path (the version is 1.3204):
/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib
you can see all real paths are different from these in the error report.
I don't know if I'm clear about my problems.

**Comment by tseemann** [comment]
Your Perl installation is broken.  You might need to put your perl installation into your `$PERL5PATH`.
You should also use Prokka 1.13 which I think does not need `Time::Piece` anymore.

**Comment by ggautreau** [comment]
I have the same issue after downloading prokka here: https://github.com/tseemann/prokka/archive/v1.13.tar.gz

Time::Piece object version 1.30 does not match bootstrap parameter 1.20_01 at /usr/lib64/perl5/DynaLoader.pm line 223.
Compilation failed in require at prokka-1.13/bin/prokka line 25.
BEGIN failed--compilation aborted at prokka-1.13/bin/prokka line 25.

**Comment by quliping** [comment]
I know how to solve the problem now. You have to find a file named 'accessibility.properties', then you should open it and add a '#' before 'assistive_technologies=org.GNOME.Accessibility.AtkWrapper'. I don't know why, but it does work.

**Comment by tseemann** [comment]
WIll try and remove Time::Piece - see https://github.com/tseemann/prokka/issues/293

**Comment by rafaeltiveron** [comment]
@quliping, where is this file "accessibility.properties"? It is still in v1.13.
