### ISSUE TITLE
Question regarding rRNA

### ISSUE THREAD

**Issue by lfaller** [tseemann/prokka#325]
Hi all,

I am looking into comparing assemblies from ONT and Pacbio data. For the pacbio assemblies, prokka v1.13 predicted rRNA sequences but it didn't report any rRNA sequences from the ONT assemblies. The assemblies were generated from the same source material so now I am wondering, is there a reason why prokka would not have annotated them? Or is Pacbio better at recovering rRNA sequences?

Thanks for any insight you might have!
~Lina

**Comment by lfaller** [comment]
I should note that prokka simply didn't mention rRNA in the *txt file that summarizes the run. So my assumption is that if prokka doesn't mention a certain genomic feature that this means it didn't find one (i.e. "rRNA: 0"). Is my assumption correct here?

**Comment by tseemann** [comment]
The pacbio assembly will be near perfect, only suffering from occasional 1bp indels in homopolymer regions.

An ONT assembly will be full of errors and missing bits of DNA.  If the rRNA operon has too many errors than it will not be found by `barrnap` most likely.

Can you find the conserved rRNA regions (between the V regions) manually with BLAST or similar?
