### ISSUE TITLE
Stop addition of 'score' qualifier when CRISPR is identified in --complaint mode

### ISSUE THREAD

**Issue by ammaraziz** [tseemann/prokka#328]
Hi Torsten,

Thank you for making `Prokka`. I am using it to annotate my genomes for submission to NCBI. I ran into a small issue with the addition of `score` qualifer when CRISPR features are added. This is problematic because when running `tbl2asn` it will throw an error:

> ERROR: Unknown qualifier 'score', relative line 10847

The annotation looks like this:
>12	189	repeat_region
rpt_family	CRISPR
score	3

The tbl2asn command I used:

    tbl2asn -V vb -M n -a r10k -y 'Annotated using prokka 1.12-beta from https://github.com/tseemann/prokka' -t X.sbt -i Y.fsa -Z error.tmp

Prokka command used:
    
    prokka --compliant --proteins Z.fa --outdir X --locustag NTHI --genus Haemophilus --species influenzae --strain Y --prefix Y --gram neg --cpus 4 Y.fasta

**Comment by tseemann** [comment]
@ammaraziz I notice you are using an old version of prokka

Can you upgrade to 1.13 please?

**Comment by ammaraziz** [comment]
Thanks @tseemann, I didn't realise there was a new version. I've upgraded to 1.13, the issue is actually now worse, `score` is being added to rRNAs and the addition of addition of `dbxref` field is also an issue. 

>NCBI/ENA have made it very hard to submit genomes from Prokka annotations.
Yoy are better off submitting contigs and ticking "yes" to "annotated with PGAAP". 

I have noticed this as well unfortunately :( I might have to go this route if I can't sort out the issues.

Thanks for your help.

**Comment by tseemann** [comment]
Do not feel bad for using PGAAP. It's a good annotator! You just can't run it locally. I don't bother to get my own annotations into NCBI anymore, they have made it too hard. And they go and re-annotate it with PGAAP anyway before putting it into RefSeq so everything is consistent.

Can you tell me what species you are annotating, so I can reproduce the error on a similar genome in genbank?

**Comment by ammaraziz** [comment]
Hi Torsten,

Sorry for the late reply. I would love to use PGAP to make my life easier but I've nearly finished writing the manuscript and at this point, it's easier to continue down this path. I think I've finally formatted the file to meet NCBI requirements. So it's still possible to use Prokka annotations for submission. 

I am annotating _Haemophilus influenzae_, I have attached the `.aa` file (below) used if it makes things easier. Otherwise this is the reference genome used for all analysis: https://www.ncbi.nlm.nih.gov/nuccore/CP000057 

Also, I've found another minor bug: Prokka 1.13 outputs `dbxref` but this should be `db_xref`.

Thanks again
[NTHI_86-028NP_proteins.txt](https://github.com/tseemann/prokka/files/2334273/NTHI_86-028NP_proteins.txt)

**Comment by tseemann** [comment]
`it's easier to continue down this path`  --- you may change your mind once you submit!

**Comment by tseemann** [comment]
Thank you the dbxref bug, i've patched it for 1.13.1

**Comment by tseemann** [comment]
@ammaraziz when i annotate that genome with Prokka 1.13 it does not find any CRISPR sites.
```
Searching for CRISPR repeats
Found 0 CRISPRs
```

**Comment by ammaraziz** [comment]
Hi @tseemann,

Ooops, that's the ref genome I provide prokka to use first (i.e. to the `--proteins` option). Try this one:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/818/925/GCA_000818925.1_ASM81892v1

After upgrading to 1.13, `score` is no longer being produced in the `.tbl` for CRISPRs. But it's being produced for ribosomal RNA:

```
395812	395703	rRNA
			locus_tag	NTHI_00371
			product	5S ribosomal RNA
			score	5.1e-10
```

Just tested this with prokka 1.13, the above file and with `--protein NTHI_86-028NP_proteins.txt` flag.

Here is the `.tbl` file if it makes things easier:
[tbl_GCA_000818925.txt](https://github.com/tseemann/prokka/files/2338768/tbl_GCA_000818925.txt)

Thanks again!
