### ISSUE TITLE
What verion of Prodigal is used?

### ISSUE THREAD

**Issue by landml** [tseemann/prokka#329]
I would like to use genetic code 25 which is part of the most current Prodigal. What version of Prodigal is PROKKA using?

**Comment by sarahhigh** [comment]
2.6.3

**Comment by landml** [comment]
Thanks.

**Comment by tseemann** [comment]
It sepends on how you installed it of course.
But mine says
```
prodigal -v

Prodigal V2.6.3: February, 2016
```
