### ISSUE TITLE
Prokka stuck at finding Parallel

### ISSUE THREAD

**Issue by kshitij1990** [tseemann/prokka#330]
Hi, 

I have been trying to use PROKKA for annotation a genome, but it seems prokka is stuck at the parallel. 

Earlier it never used to do this, but after migrating to the new machine and installing prokka it is not working. 

Here is the snapshot of the run. 
![prokka_parallel_stuck](https://user-images.githubusercontent.com/16733386/44570147-67f49e00-a7af-11e8-9d4e-b36e0bce5410.PNG)

**Comment by tseemann** [comment]
What does `parallel --version` say ?
