### ISSUE TITLE
Prokka error: Can't find required 'java' in your $PATH

### ISSUE THREAD

**Issue by libertinerosessanchez** [tseemann/prokka#331]
I ran my spades contigs.fasta using prokka 1.12 and gave me this error:

Determined hmmscan version is 3.1
Can't find required 'java' in your $PATH

Please help how to resolve this issue.

![screen shot 2018-08-29 at 3 33 26 pm](https://user-images.githubusercontent.com/38885037/44772667-09f5fb00-aba1-11e8-863c-32724cff8765.png)

![screen shot 2018-08-29 at 3 34 11 pm](https://user-images.githubusercontent.com/38885037/44772646-02365680-aba1-11e8-98ba-d2b6a3554775.png)

**Comment by tseemann** [comment]
Is Java in your PATH?
Did you load the java module?

```
module avail |& grep -i java
```

```
java -version
```

PS. please upgrade to Prokka 1.13

**Comment by libertinerosessanchez** [comment]
Good afternoon,

Thank you for the immediate response. We really appreciate it. I am running
through our slurm university server. And I am using my mac. How will I know
the java version (University Genetics server or my mac)?

Thank you.

*Libertine Rose S. Sanchez, M.Sc.*
Ph.D. Biology Candidate
Institute of Biology
College of Science
University of the Philippines
Diliman Quezon City 1101
+63 9209203397

**Comment by libertinerosessanchez** [comment]
Good afternoon,

Thank you for the immediate response. We really appreciate it. I am running through our slurm university server. And I am using my mac. How will I know the java version (University Genetics server or my mac)? I will also request for our Bioinformatics core to upgrade in version 1.13
Thank you.

**Comment by libertinerosessanchez** [comment]
I found our java version sir.
It's the module jre that i should have loaded as well

Thank you very much. It's working right now.

**Comment by tseemann** [comment]
That's good news!

**Comment by libertinerosessanchez** [comment]
Prokka v.1.13 has been running smoothly but I think it get stucked/ hung already for 16 hours:
This is the last thing in the log file/ prokka.error
Running: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.13 from https://github.com/tseemann/prokka' -Z PA3prokka\/PA3\.err -i PA3prokka\/PA3\.fsa 2> /dev/null

I encountered this last week that's why we updated the version from 1.12 to a.13. ALL output files are generated except gbk and asn

Please help

**Comment by tseemann** [comment]
`tbl2asn` is the command that makes the gbk and asn files.

Does `tbl2asn -` print anything.

How many contigs do you have?
If this is a metagenome with 1 million it might not every finish, or take 2 weeks.

**Comment by libertinerosessanchez** [comment]
Good morning Mr. Tseemann,
I really appreciate your reply. Yes this is a metagenome. What do you suggest can I do with this?
