### ISSUE TITLE
Remove date from name of output files.

### ISSUE THREAD

**Issue by DolapoA** [tseemann/prokka#334]
Is there a way to, not have the date in the output filename, thereby allowing the filename to be the name of the sample. It seems I can't designate a name of my choosing for results.

[12:39:02] Contig ID must <= 20 chars long: gnl|s|sample_name_contig000001
[12:39:02] Please rename your contigs or use --centre XXX to generate clean contig names.

Is there no way for Prokka to work around the '<= 20 chars long'?

**Comment by tseemann** [comment]
1. Use the --prefix option?

2. Don't use --compliant option?

**Comment by DolapoA** [comment]
The date is removed, but I'm still advised to rename my contigs. And it can only produce an .fna file and a .log file.

**Comment by tseemann** [comment]
Sounds like Prokka isn't running correctly if you only get those two files. You'll need to file a separate issue for that problem and include the log file.
