### ISSUE TITLE
Twice as many annotations as expected

### ISSUE THREAD

**Issue by laurafisch9** [tseemann/prokka#339]
An assembled genome with about 2,000,000 bp was annotated with prokka. If one gene is ~1,000 bp, then it would be expected to return 2,000 genes. Yet my .faa file has ~4,000 genes in them. 
It looks like in the .gff file has a gene call using prokka and prodigal. There for the genes may have been called twice and this would make sense why there are twice as many genes in the .gff file. 
The picture below shows the prodigal and the prokka gene call for the same position in the genome and the same locus tag as well. 

![screen shot 2018-09-20 at 7 36 35 pm](https://user-images.githubusercontent.com/38894262/45852368-79c55480-bd0d-11e8-8bcc-4f86105a1865.png)

I am wondering why then does the .faa file (sample below) has ~4,000 genes when I was only expecting to see 2,000.

![screen shot 2018-09-20 at 7 36 54 pm](https://user-images.githubusercontent.com/38894262/45852370-7b8f1800-bd0d-11e8-8174-2e41fa0ff52d.png)

**Comment by andersgs** [comment]
Hi @laurafisch9 note that your first table you have two entries per annotation: a gene and a CDS. I assume you are working with a bacteria, which often have gene and CDS that completely overlap, but it may include other regions (3' and 5' UTR, etc). In more thorough annotations, this might also include mRNA, etc. Check out the description of GFF3 format: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

Can you confirm that there indeed ~4000 entries in your FAA file. Could you run `grep -c '>' *faa`.

What is the bug? Are you positive you have a good assembly, and the data come from a pure culture?

**Comment by laurafisch9** [comment]
I have not heard of Kraken or Genenious. Thank you for the suggestions I will look into all of them.

**Comment by tseemann** [comment]
If your assembly is poor or you have a number of contigs close to the number of expected genes, then most genes will be broken and will appear as two partial genes, making it look like you have twice as many genes.

**Comment by laurafisch9** [comment]
@andersgs Do you know how to go about finding the the mean length of the predicted proteins?
