### ISSUE TITLE
Upcoming BioPerl releases

### ISSUE THREAD

**Issue by cjfields** [tseemann/prokka#342]
Hi @tseemann we're working on splitting out a lot of legacy code for BioPerl for the next several 1.7.x releases to make it a bit easier to maintain.  We're happy to help distributions migrate where possible.  

I think it would be easy enough to address by specifying (beyond the stripped-down core) which particular modules Prokka might need.  Would this be primarily addressed in the documentation, or would you have other sources that need updates?

**Comment by tseemann** [comment]
The main issue will be that Bioconda and Brew will need to change, because `bioperl` will be insufficient. It could be addressed by them making their `bioperl` just install **all** the subrepos?

**Comment by cjfields** [comment]
Yes that would make sense.  The intent is that Bundle-BioPerl will end up replacing the traditional `sudo cpan Bio::Perl` as it will contain all the split-out distributions, with the long-term possibility that one could install a stripped-down version of bioperl w/o the dependency hell.

**Comment by tseemann** [comment]
Yep, the packagers could just replace the current "all in one" packages with a Bundle-Bioperl version, and it should be transparent to all the packages dependent on it.

They could then later make sub-packages for the new bioperl components and make them deps of the master package. This would provide a smooth transition over the medium term.

Personally I primarily use `Bio::SeqIO`.

heads up to 
* bioconda @bgruening @druvus
* brewsci @sjackman
