### ISSUE TITLE
gff file missing fields

### ISSUE THREAD

**Issue by allebiotech** [tseemann/prokka#344]
Dear @tseemann,
I've a bacterial genome assembled with Spades (using Illumina 2x150 paired end reads). The annotation of the scaffolds.fasta generates a .gff file with missing fields (e.g the gene features).
iI've run prokka using the --centre X --compliant trying to solve the issue but it didn't work.

This is how it looks like the .gff file:

##gff-version 3
##sequence-region gnl|X|ECLOKCIF_1 1 656092
##sequence-region gnl|X|ECLOKCIF_2 1 422202
##sequence-region gnl|X|ECLOKCIF_3 1 324975
##sequence-region gnl|X|ECLOKCIF_4 1 322055

This is what i got in the .err file:

Discrepancy Report Results

Summary
DISC_SOURCE_QUALS_ASNDISC:strain (all present, all same)
DISC_SOURCE_QUALS_ASNDISC:taxname (all present, all same)
DISC_FEATURE_COUNT:gene: 2347 present
DISC_FEATURE_COUNT:CDS: 2267 present
DISC_FEATURE_COUNT:tRNA: 75 present
DISC_FEATURE_COUNT:rRNA: 4 present
DISC_FEATURE_COUNT:tmRNA: 1 present
DISC_COUNT_NUCLEOTIDES:1324 nucleotide Bioseqs are present
OVERLAPPING_GENES:503 genes overlap another gene on the same strand.
OVERLAPPING_CDS:6 coding regions overlap another coding region with a similar or identical name.
SUSPECT_PRODUCT_NAMES:8 product_names contain suspect phrase or characters
	May contain database identifier more appropriate in note; remove from product name
		3 features Three or more numbers together
		1 features Contains underscore
	Use short product name instead of descriptive phrase
		1 features Contains 2 or more brackets or parentheses but not starts with '1-(5-phosphoribosyl)-5-'
		2 features Is longer than 100 characters
	use protein instead of gene as appropriate
		1 features contains 'genes'
NO_ANNOTATION:1283 bioseqs have no features
DISC_QUALITY_SCORES:Quality scores are missing on all sequences.
FATAL: DISC_SUSPECT_RRNA_PRODUCTS:1 rRNA product names contain suspect phrase
TEST_BAD_GENE_NAME:3 genes contain suspect phrase or characters
ONCALLER_COMMENT_PRESENT:1324 comment descriptors were found (all same)
SHORT_PROT_SEQUENCES:62 protein sequences are shorter than 50 aa.
MISSING_GENOMEASSEMBLY_COMMENTS:1324 bioseqs are missing GenomeAssembly structured comments
MOLTYPE_NOT_MRNA:1324 molecule types are not set as mRNA.
TECHNIQUE_NOT_TSA:1324 technique are not set as TSA
MISSING_STRUCTURED_COMMENT:1324 sequences do not include structured comments.
MISSING_PROJECT:3591 sequences do not include project.
FATAL: RRNA_NAME_CONFLICTS:1 rRNA product names are not standard. Correct the names to the standard format, eg "16S ribosomal RNA"
DISC_INCONSISTENT_MOLINFO_TECH:Molinfo Technique Report (some missing, all same)
DISC_GAPS:1 sequences contain gaps

I don't know how to fix this.

Thanks in advance!

allebiotech

**Comment by tseemann** [comment]
Does the corresponding genbank file have the `/gene` attribute in the CDS features?

**Comment by allebiotech** [comment]
@tseemann, thanks for the prompt reply!
This is what I see:

     gene            1083..1940
                     /locus_tag="ECLOKCIF_00005"
     CDS             1083..1940
                     /locus_tag="ECLOKCIF_00005"
                     /inference="ab initio prediction:Prodigal:2.6"
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /protein_id="X:ECLOKCIF_00005"
                     /translation="MRETNVDFAQDTTTDDDDLRVKFFFEVLNDSGIPALYKQHRSIQ
                     PVIKKHIAYLKEHQELLVLTVVYVAPMREWLETQIEMGDWADTQYAVRDFFDGLNGLF
                     LQDVVTVSENDERIHYTAELQALITGILAHEPDELAYSGDDGNVPEYDDAIHDFMTDL
                     VNRDELTPEGLETAQAIISMVLDELAVKTHASLPAITPDMLGQVLRQKFQTFDLFGLD
                     GFEFVDDIVIEFARWAAAQDLMPKANVLKWGKAIETVQFDRYAYALIADAANKLEMVE
                     IGQDMPAIY"

Thanks!

**Comment by tseemann** [comment]
So when you say "gene" do you mean the four letter code for a gene?
eg. `dnaA` for `DNA replication initiation protein` etc?

They can only be assigned if they exist in the sequence database used for annotation. Also, most genes do not have a gene code.

**Comment by allebiotech** [comment]
Hi @tseemann,
I understand what you said but the gff3 file format should not contain 9 columns?

**Comment by tseemann** [comment]
Yes - GFF3 has 9 columns for the _feature_ lines.
See: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

The rows with `##` at the start are header lines, and are _separate_ to the 9 column lines, and separate to the FASTA sequence appended.

The `.err` file has nothing to do with the `.gff` file.

**Comment by allebiotech** [comment]
OK, thanks!

**Comment by thierryjanssens** [comment]
I am using prokka version 1.13.7, but still I am getting the long contig name warning, despite gff is the output format.
I prefer not to use --centre X --compliant, since I want to keep the possibility for parsing the output with output from other analyses.

**Comment by tseemann** [comment]
I won't be able to change this behaviour in the short term.

I would rename all the contigs, and then name them back afterwards in the GFF file.
