### ISSUE TITLE
Is it possible to annotate genes directly?

### ISSUE THREAD

**Issue by surh** [tseemann/prokka#346]
I have assembled bacterial genomes where I have already predicted genes. Is it possible to provide prokka with just a fasta file of nucleotide or aminoacid sequences and have it annotate them?

**Comment by tseemann** [comment]
No, it is not easy to do that, sorry. I think _Anvio_ might be able to do it though.

One thing you _could_ try is to join all your CDS (nucletoide genes) with a sequence like this:
`NNNNNCATTCCATTCATTAATTAATTAATGAATGAATGNNNNN`
It contains stop codons in all 6 frames.
and then run Prokka on that psuedomolecule.

**Comment by b-tierney** [comment]
Hey @tseemann How do you think the solution you recommended here would scale? I have a database of about 1 billion predicted ORF's I need to annotate that I've already run through prodigal (wasn't my choice, had to do it for another piece of software in the pipeline). Running all genomes individually would likely be cost prohibitive (this is somewhat time sensitive). 

However if I cat output into a single file and run through PROKKA, think I'll somehow save any time over doing them all individually? My guess is no, but I figure it's worth asking...

Thanks so much.

**Comment by surh** [comment]
I would also support such an option for PROKKA, though as I understand it might not be trivial.

@b-tierney as an alternative, I've moved to the eggNOG mappper

**Comment by b-tierney** [comment]
Much thanks @surh – will take a look.
