### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by Laura-Alex** [tseemann/prokka#347]
Hello,

I'm a newbie using Ubuntu in a virtual machine. I've started by installing the mandatory and recommended dependencies, then installed Prokka as per the guidelines for Ubuntu/Debian/Mint. However, when I try to run the tests, I get:
"Command 'prokka' not found, did you mean:

  command 'propka' from deb pdb2pqr

Try: sudo apt install <deb name>"

Thinking that perhaps I missed something, I tried to install Prokka again ( "git clone https://github.com/tseemann/prokka.git $HOME/prokka"). However, when I do that, it tells me: "fatal: destination path '/home/laura/prokka' already exists and is not an empty directory.")

I know it's probably a very basic issue, but I would appreciate your help!

**Comment by tseemann** [comment]
In Unix environment, you need add the folder where the `prokka` command is to your `PATH`. You can probably google how to do this. But you can still run it without doing that.

```
cd $HOME
git clone https://github.com/tseemann/prokka.git
$HOME/prokka/bin/prokka --setupdb
$HOME/prokka/bin/prokka --help
```
