### ISSUE TITLE
Can't locate XML/Simple.pm in @INC 

### ISSUE THREAD

**Issue by letunglam1991** [tseemann/prokka#349]
I run prokka and prokka notice "Can't locate XML/Simple.pm in @INC". But when i run prokka with sudo it ok? before 1 week i still run prokka without sudo ok. how can i fix it.
I reinstall cpan bioperl and prokka but still error 

```
prokka --setupdb
Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) (@INC contains: /home/hoangha/softwares/prokka/bin/../perl5 /home/hoangha/softwares/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/hoangha/softwares/miniconda3/lib/site_perl/5.26.2 /home/hoangha/softwares/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/hoangha/softwares/miniconda3/lib/5.26.2 .) at /home/hoangha/softwares/prokka/bin/prokka line 28.
BEGIN failed--compilation aborted at /home/hoangha/softwares/prokka/bin/prokka line 28.

```

**Comment by tseemann** [comment]
You need to install the Perl module `XML::Simple`.

Instructions here: https://github.com/tseemann/prokka#ubuntudebianmint

**Comment by letunglam1991** [comment]
> XML::Simple

thanks for reply soon. my XML::Simple is up to date

Reading '/home/hoangha/.cpan/Metadata'
  Database was generated on Thu, 01 Nov 2018 03:17:02 GMT
CPAN: Module::CoreList loaded ok (v5.20151213)
XML::Simple is up to date (2.25).

**Comment by Adelaam** [comment]
Hello, I have installed it for ubuntu like the instructions says, but still have the same error. Could you let me know how exactly can I install the perl module in the same place as the Perl?
Thank you!
A

**Comment by tseemann** [comment]
@Adelaam  please tell me what these commands say:
```
% which -a perl
% perl -V | tail
% prokka --version
```

**Comment by Adelaam** [comment]
Hello,
-/usr/bin/perl

-  /home/markwilks/perl5/lib/perl5
    /etc/perl
    /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
    /usr/local/share/perl/5.26.1
    /usr/lib/x86_64-linux-gnu/perl5/5.26
    /usr/share/perl5
    /usr/lib/x86_64-linux-gnu/perl/5.26
    /usr/share/perl/5.26
    /usr/local/lib/site_perl
    /usr/lib/x86_64-linux-gnu/perl-base
-When I tried to reinstall, I got this error now:
Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.

Thank you!

**Comment by Adelaam** [comment]
I downloaded makeblastdb 2.9.. from the website but still same error.
And the error I got last week: prokka --setupdb
Can't locate XML/Simple.pm in @INC, I shorted it out removing perl5 folder from my pc.

Thank you!

**Comment by tseemann** [comment]
Good news @Adelaam
