### ISSUE TITLE
Use eggnog to annotate

### ISSUE THREAD

**Issue by HENdavid** [tseemann/prokka#353]
Dear Torsten,

I been using prokka for many years as a base for annotation and comparative genomics together with roary, now I have some issues. I am using version 1.13 (brew) and I got no  CRISPR annotation for my genomes, I know it is being fixed in version 1.14, any idea when it is gonna be available the update? Also for annotation, I found I bit disappointing when annotate my genomes with the standard databases that comes ready with prokka, I would like to use EGGNOG 4.5/5 (HMM) database instead, any chance to implement this in the last update or it is possible to covert it as a custom database, if so can you guide me a little bit.

Thanks in advance, I really enjoy using prokka!

**Comment by tseemann** [comment]
@HENdavid thabk you to @harish0201 for helping here. You need to get HMMER 3.x formatted database files for the eggNOG database, and then just provide them via the `--hmms` option.
