### ISSUE TITLE
Annotate from e.g. IS before --proteins?

### ISSUE THREAD

**Issue by thsyd** [tseemann/prokka#354]
Hi Torsten,
Thank you so much for these excellent and easy to use packages! 
Other than changing the code in Prokka, is there a way to set the order of annotation so --proteins is used after Kingdom/Bacteria/IS ?
I'd like to add the IS information to PGAP annotated genomes.
The annotation of IS elements is far richer and more informative using the IS database that what is present in the PGAP annotations I already have.

Thomas

**Comment by tseemann** [comment]
You can't do it from the command line, but you might be able to tweak Prokka to do it.
(I may consider adding a "priority" rank to each database in the future)

```
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# Annotate CDS
my @database; # list of databases to use, in priority order
```
After this line, there is a series of `push @database` (put at end) and `unshift @database` (put at start).  If you re-arrange them, to put the `--proteins` section in the right place, you can achieve what you desire.
