### ISSUE TITLE
Brew Install Breaks when looking for latest blast file

### ISSUE THREAD

**Issue by nearinj** [tseemann/prokka#356]
Hello,

When installing prokka through LinuxBrew the following error occurs:

 curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "blast"
Download failed: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.7.1+-src.tar.gz

I'm guessing this is due to ncbi hosting the lastest blast as 2.8

**Comment by c4derpillar** [comment]
Installing it with conda still works :)

**Comment by tseemann** [comment]
This should be fixed by now. I wish NCBI wouldn't move original source files!
