### ISSUE TITLE
Database setup fails if the current working directory has a space in the name.

### ISSUE THREAD

**Issue by ChatBotMatt** [tseemann/prokka#357]
On Windows 10, running Prokka in an Ubuntu subsystem. I tried running "prokka --setupdb" and it failed due to the CWD having a space in the name. Fixed it by renaming the CWD folder.

All other setup worked fine out of the box.

**Comment by tseemann** [comment]
@ChatBotMatt thanks for the report! I thought I had mostly made prokka "space-in-paths" safe, as I am enclosing all files with `\Q ... \E` in Perl which quotes shell metacharacters.  I might need to look closer.

**Comment by tseemann** [comment]
TL;DR - don't use spaces in Unix paths.

**Comment by ChatBotMatt** [comment]
With all due respect, that isn't really a fix. 

Given that you previously claimed to have worked at making it "space-in-paths" safe, I'm surprised you're giving up here?
