### ISSUE TITLE
Random order in the output ".txt	Statistics relating to the annotated features found."

### ISSUE THREAD

**Issue by thsyd** [tseemann/prokka#359]
Hi,
I wanted to extract the information from the .txt output (Statistics relating to the annotated features found) for generating a table of information from meta-data about annotation results for multple genomes and came across an unexpected behaviour from Prokka:

The order of lines in the  ".txt	Statistics relating to the annotated features found." seems to be semi-random.

**Case:**
Running prokka for a number of assembled bacterial genomes (.fasta) in the same directory by
```
ref_genomic_gbff=<path to reference genbank file>
NPROCS=<code for getting number of threads (running on a HPC)>

allfasta=$(ls *.fasta)
mkdir prokka
for F in $allfasta; do
	N=$(basename $F .fasta | sed s/\[.]/_/g)
	prokprefix=$(basename $F .fasta)
	prokka --outdir prokka/$N --force \
		--prefix $prokprefix \
		--proteins $ref_genomic_gbff \
		--cpus $NPROCS \
		$F
done
```
the .txt files in the output directories for the respetive annotations vary in the order of the lines eg:

**assemblyone.txt:**
> organism: Genus species strain 
contigs: 28
bases: 5207717
tmRNA: 1
CRISPR: 2
tRNA: 61
CDS: 4334
rRNA: 3

**assemblytwo.txt**
> organism: Genus species strain 
contigs: 212
bases: 5255467
CRISPR: 2
rRNA: 4
CDS: 4343
tRNA: 62
tmRNA: 1

**assemblythree.txt**
> organism: Genus species strain 
contigs: 8
bases: 5247651
rRNA: 18
CDS: 12150
tmRNA: 1
tRNA: 66
CRISPR: 2

** My solution**
I ended up sorting the lines alphabetically, transposing to columns and reordering them.
If anyone can use the code below they are very welcome. I'm sure it can be done much more elegantly. 

```
#!/bin/sh

# Converts the Prokka summary txt to usefull tsv
# Scenario: You have annotated several genomes 
# and the Prokka output directories are all in the same "root" directory.
# eg:	../
#	        ../prokkaoutone/
#	        ../prokkaouttwo/
#	        ..[...]

# Usage: Run this script in the "root" directory. It will search upper level directories for *.txt
#	 and concatenate the output statistics generated by prokka in this txt file.

# Prepare column headers for prokkaresults.tsv
printf "Prokka bases\tProkka CDS\tProkka contigs\tProkka CRISPR\tProkka isolate\tProkka rRNA\tProkka tmRNA\tProkka tRNA\n" > prokkaresults.tsv

echo "Tabulating and concatenating the following:"
ls */*.txt

for F in */*.txt; do
	#get the basename of the .txt file
	F_base=$(basename $F .txt)
	#printf "isolate" and the basename to first line in tempfile.tsv
	printf "isolate\t$F_base\n" > tempfile.tsv
	#remove the first line of the prokka result.txt, convert space to tab, remove the colon
	tail -n +2 $F | tr ' ' \\t | tr -d : >> tempfile.tsv
	# we have to sort alfabetically as prokka does not output results to the txt in the same order for 
	# each annotation run!
	#sort the tempfile cut the second column and paste as a row (transpose), and add this to prokkaresults.tsv
	sort tempfile.tsv | cut -f2 | paste -s >> prokkaresults.tsv
done

#Reorder columns for more logical output.
awk 'BEGIN {FS="\t"}{OFS="\t"}{print $5,$1,$3,$2,$6,$7,$8,$4}' prokkaresults.tsv > prokkaresults.tsv

# remove the temporary file.
rm tempfile.tsv

echo "done"
```

**Comment by tseemann** [comment]
The order of keys in a hash is non-deterministic. 
I have fixed it by always sorting the keys now.

OLD:
```
for my $ft (keys %count) {
  printf "%s: %d\n", $ft, $count{$ft};
}
```

NEW:
```
for my $ft (sort keys %count) {
  printf "%s: %d\n", $ft, $count{$ft};
}
```

**Comment by tseemann** [comment]
@thsyd Thank you for submitting a thorough and clear bug report!
