### ISSUE TITLE
Prokka loads but doesn't appear functional

### ISSUE THREAD

**Issue by ctparson** [tseemann/prokka#363]
I am running Ubuntu 18.04, the Prokka install seems to run correctly but when I type in the prokka command after install I get the following message:

Command 'prokka' not found

Any suggestions would be greatly appreciated

**Comment by laxeye** [comment]
Hi @ctparson! 
Try to run it by specifying the full path. If You installed prokka to e.g. /home/ctparson/prokka then type in terminal: 
/home/ctparson/prokka/bin/prokka
Or if you are in the directory where prokka main executable is located then type:
./prokka

**Comment by ctparson** [comment]
That did the trick, everything runs great from there, thank you.

**Comment by tseemann** [comment]
Thank you @laxeye - it's wonderful when fellow Prokka users help each other out.
