### ISSUE TITLE
Not predicting rRNAs witn Barrnap installed

### ISSUE THREAD

**Issue by raw937** [tseemann/prokka#366]
Hello, 

I have barrnap installed. 

It's states
[11:54:53] Predicting Ribosomal RNAs
[11:54:53] You need either Barrnap or RNAmmer installed to predict rRNAs!

Help? It's not writing the rRNAs to files for some reason.

**Comment by tseemann** [comment]
What does `which barrnap` say?

**Comment by raw937** [comment]
It was a barrnap install issue. I installed it and added it to my .bashrc. But, It was unable to find it. 
Ubuntu 18.04 has a sudo apt-get option for barrnap. Which got it to work. You can close this. Sorry.

**Comment by tseemann** [comment]
@raw937 glad you got up and running in the end!
