### ISSUE TITLE
Prokka not deleting some tmp files

### ISSUE THREAD

**Issue by asetGem** [tseemann/prokka#368]
Hello,

I've been using prokka for annotating many genomes. However, today, I have an unexpected behaviour : prokka runs without error, and gives the files back, BUT it does not remove the tmp files HAMAP.hmm.faa, and/or sprot.faa. 
Those 2 files are empty, but they are still present in the prokka output directory. This happens with some genomes, but not others, and I cannot determine when it appears. With some genomes I only have the sprot, with others I have the HAMAP, and with others both files.

I attach here 3 examples : 
- genome-ok : everything is as expected
- genome-HAMAP : HAMAP.hmm.faa not deleted
- genome-HAMAP-sprot : both files not deleted

Do you have any idea why those files are sometimes not deleted?

Thanks,

Amandine

[genome-HAMAP-sprot.txt](https://github.com/tseemann/prokka/files/2889121/genome-HAMAP-sprot.txt)
[genome-HAMAP.txt](https://github.com/tseemann/prokka/files/2889122/genome-HAMAP.txt)
[genome-ok.txt](https://github.com/tseemann/prokka/files/2889123/genome-ok.txt)

**Comment by ealdraed** [comment]
Hello @asetGem !

Even if I tried my best to guess, I cannot see what the commands were you used, nor what the OS or Env was that you used to execute your commands. Please be a bit more specific.

**Comment by tseemann** [comment]
A file would usually not be deleted if Prokka failed partway through. I'm guessing `tbl2asn` might be the culprit.
