### ISSUE TITLE
Problem with SignalP 5.0

### ISSUE THREAD

**Issue by MaggieLoT** [tseemann/prokka#370]
Hello, I found that Prokka (1.13) quits, since it can't define the SignalP version. I've installed the newest version of SignalP (5.0) on Darwin x86_64. Even if I omit 'gram' definition, it still quits with the same error.
With kind regards,
Maggie

**Comment by chuseq** [comment]
Maybe this will help. We modified the prokka script, line 121, used -V instead of -v to get signalp version number. 

`GETVER  => "signalp -V | sed 's/^signalp //'",`

Still doing test runs.

**Comment by carissableker** [comment]
The above modification did not work for me, but the following did: 
  
    GETVER  => "signalp --version < /dev/null 2>&1 | cut -d' ' -f 3",

**Comment by Arkadiy-Garber** [comment]
Carissa's version seems to work for me. Thanks!

**Comment by tseemann** [comment]
@carissableker is this patch backward compatible with SignalP 3 and 4 ?

**Comment by carissableker** [comment]
@tseemann Unfortunately I do not know anything about SignalP, so I am not sure.

**Comment by MaggieLoT** [comment]
The modification proposed by Carissa works (Prokka is locating correctly SignalP) however, I see no predictions included in the output files for signal peptides.

**Comment by tseemann** [comment]
I suspect it outputs in a different format.  That's unfortunate.
