### ISSUE TITLE
The same gene name but different gene product

### ISSUE THREAD

**Issue by huizhen2014** [tseemann/prokka#371]
Hello, I used the prokka to annotate my NGS data, but I surprisingly found the different gene product appeared for the same gene name from two samples. The different content and my scripts are demonstrated below:

prokka --kingdom Bacteria --outdir 42395_pan  --locustag 42395_pan
prokka --kingdom Bacteria --outdir 38588_pan  --locustag 38588_pan
42395_pan_05126 CDS     300     bla_2   3.5.2.6         Beta-lactamase CTX-M-1
38588_pan_05134 CDS     861     bla_2   3.5.2.6         Beta-lactamase TEM

Could you tell me what the problem with my scripts or results? Thank you.

**Comment by tseemann** [comment]
Is the gene the same length and exact same DNA sequence?

**Comment by huizhen2014** [comment]
No, neither the length nor the DNA sequence was the same, and what they were outputed here:
>42395_pan_05126 Beta-lactamase CTX-M-1
MMFAAAACIPLLLGSAPLYAQTSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDER
FPMCSTSKVMAVAAVLKQSETQKQLLNQPVEIKPADLVN

>38588_pan_05134 Beta-lactamase TEM
MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRP
EERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVREL
CSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTM
PAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGS
RGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW

**Comment by ealdraed** [comment]
Hello @huizhen2014 ,

what did you expect?

You have two different DNA sequences and want Prokka to give you the same resistance gene?

Can you elaborate a bit more?

**Comment by huizhen2014** [comment]
Yes, the two different amino acid sequences produce the different gene produce. But, they two share the same resistantce gene name, bla_2.



Hui Zhen
138 2882 7480
Shenzhen Second People's Hospital, Futian District, Shenzhen City, Guangdong Province
 
From: ealdraed
Date: 2019-03-26 06:34
To: tseemann/prokka
CC: Carlos Hui; Mention
Subject: Re: [tseemann/prokka] The same gene name but different gene product (#371)
Hello @huizhen2014 ,
what did you expect?
You have two different DNA sequences and want Prokka to give you the same resistance gene?
Can you elaborate a bit more?

**Comment by ealdraed** [comment]
I think what you see there just happens by chance. Your two ESBL genes, though different, both have the `bla` mnemonic for beta-lactamase (and the same EC number). When prokka encounters duplicate gene names it adds numbers since names have to be unique throughout a genome.

Actually, the reverse case could also happen: paralogs (probably same gene product) would have different gene names within an annotation. It could also happen that one gene product would be named bla_1 in one annotation and bla_2 in another.

All in all nothing I would be worried about.

**Comment by tseemann** [comment]
@ealdraed thank you for helping @huizhen2014 , your explanations were excellent.
