### ISSUE TITLE
Cannot install prokka

### ISSUE THREAD

**Issue by lingbingzeng1985** [tseemann/prokka#373]
I cannot install prokka like this: Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module)

**Comment by nsarode-joyn** [comment]
Are you installing it via conda ? In that case, the following installation order should get rid of this error
```
conda install -c conda-forge -c bioconda prokka
conda install -y -q perl=5.22
```

**Comment by tseemann** [comment]
@lingbingzeng1985 did you follow the instructions?
https://github.com/tseemann/prokka#ubuntudebianmint
