### ISSUE TITLE
Error: File format problem in trying to open HMM file

### ISSUE THREAD

**Issue by drambrina** [tseemann/prokka#374]

**Comment by drambrina** [comment]
Hi, I am running prokka  but this time it is giving error in installation.
Error: File format problem in trying to open HMM file /home/hpcc/prokka/db/hmm/HAMAP.hmm.
File exists, but appears to be empty?

[02:41:13] Could not run command: hmmpress \/home\/hpcc\/prokka\/db\/hmm\/HAMAP\.hmm

I have tried to reinstall, cleandb, but the problem persist. 
following are the prokka --depends
hpcc@hpcc:~/prokka/bin$ ./prokka --depends
aragorn >= 1.2 (compulsory, bundled)
barrnap >= 0.4 (optional, not bundled)
blastp >= 2.2 (compulsory, bundled)
cmpress >= 1.1 (optional, bundled)
cmscan >= 1.1 (optional, bundled)
egrep >= 0 (compulsory, not bundled)
find >= 0 (compulsory, not bundled)
grep >= 0 (compulsory, not bundled)
hmmpress >= 3.1 (compulsory, bundled)
hmmscan >= 3.1 (compulsory, bundled)
java >= 0 (compulsory, not bundled)
less >= 0 (compulsory, not bundled)
makeblastdb >= 2.2 (optional, bundled)
minced >= 2.0 (optional, bundled)
parallel >= 20130422 (compulsory, bundled)
prodigal >= 2.6 (compulsory, bundled)
prokka-genbank_to_fasta_db >= 0 (compulsory, bundled)
rnammer >= 1.2 (optional, not bundled)
sed >= 0 (compulsory, not bundled)
signalp >= 3.0 (optional, not bundled)
tbl2asn >= 24.3 (compulsory, bundled)

**Comment by tseemann** [comment]
How did you install Prokka ?

**Comment by drambrina** [comment]
sudo apt-get install libdatetime-perl libxml-simple-perl libdigest-md5-perl git default-jre bioperl
sudo cpan Bio::Perl
git clone https://github.com/tseemann/prokka.git $HOME/prokka
$HOME/prokka/bin/prokka --setupdb

**Comment by leonardomarino** [comment]
I am having the same problem in CentOS release 6.10 (Final)

[20:04:59] Pressing HMM database: /opt/prokka/db/hmm/HAMAP.hmm
[20:04:59] Running: hmmpress \/opt\/prokka\/db\/hmm\/HAMAP\.hmm
Working...    [20:04:59] Could not run command: hmmpress \/opt\/prokka\/db\/hmm\/HAMAP\.hmm

**Comment by tseemann** [comment]
@leonardomarino do you happen to have the old HMMER 2.x package (Centos RPM) installed?

**Comment by leonardomarino** [comment]
Yes @tseemann , I ended up reinstalling HMMER and now I am running HMMER 3.2.1 and things are fine.

**Comment by tseemann** [comment]
@leonardomarino i am  glad you resolved the problem
