### ISSUE TITLE
Your HMM is not indexed, please run: hmmpress

### ISSUE THREAD

**Issue by Elenombi** [tseemann/prokka#376]
Hi there,

I would like to annotate my genomes with a custom hmm database.
I have few protein alignments and for each I have ran
$hmmbuild output.hmm input.fasta
then created a single file using $cat, I have moved the file protein_al.hmm in ~/miniconda3/envs/prokka/db/hmm/ then run hmmpress. it creates four additional files and the new database appears in --listdb.

when I run prokka with --hmms protein_al.hmm prokka fails with:
Your HMM is not indexed, please run: hmmpress protein_al.hmm

same happens with when I use the flag --hmms HAMAP.hmm

Could you please help me?

**Comment by tseemann** [comment]
> then created a single file using cat

What do you mean by this?

Did you try not putting the `.hmm` on the name?

**Comment by Elenombi** [comment]
I had multiple alignments and for each I ran hmmbuild, then I created a single file using 
cat *.hmm > protein_al.hmm
I have also tried without .hmm but I get the same error. 

prokka tells me that my HMM is not index also when I use the given HAMAP database

**Comment by dadahan** [comment]
Bumping this issue since I am receiving the same error, tried:
--hmms dbCAN.hmm
--hmms dbCAN
--hmms dbCAN*

My dbCAN hmms and binaries generated with hmmpress are in: 
```/resources/anaconda3/envs/roary/db/hmm/```

**Comment by dadahan** [comment]
Solved. You need to provide the absolute file path for your HMM and the .hmm extension. For example:
```--hmms /resources/anaconda3/envs/roary/db/hmm/dbCAN.hmm```
The program does not automatically search in the /resources/anaconda3/envs/roary/db/hmm/
for the specified hmm and trying:
```--hmms HAMAP.hmm```
or
```--hmms blah_blah_blah.hmm```
will both return:
```Your HMM is not indexed, please run:```

We should make a pull request for --hmms flag to search in your db directory.

**Comment by slvrshot** [comment]
> Solved. You need to provide the absolute file path for your HMM and the .hmm extension. For example:
> `--hmms /resources/anaconda3/envs/roary/db/hmm/dbCAN.hmm`
> The program does not automatically search in the /resources/anaconda3/envs/roary/db/hmm/
> for the specified hmm and trying:
> `--hmms HAMAP.hmm`
> or
> `--hmms this_hmm_doesn_not_exist.hmm`
> will both return:
> `Your HMM is not indexed, please run: hmmpress <hmm name>`
> 
> We should make a pull request for --hmms flag to search in your db directory.

You saved my day. I was about to go crazy trying to figure this out.

**Comment by tseemann** [comment]
The `--hmms` option is not for choosing a HMM in the `prokka/db/hmms` folder, it's for providing an external HMM to just use for this annotation run.
