### ISSUE TITLE
Python port for Prokka

### ISSUE THREAD

**Issue by vinisalazar** [tseemann/prokka#377]
Dear @tseemann ,

I love Prokka. I'm currently using it in a project and using Python scripts to run it. Myself and I'm sure many other users would greatly benefit if there was a Python version, seeing how ubiquitous the use of Python has become in bioinformatics.

So my question is, do you ever consider putting out a Python port? Does this possibility interest you? Or is it out of question at the present moment?

I'm merely probing and hope you appreciate the discussion. Thank you very much.

Best,

V

**Comment by tseemann** [comment]
If I was to re-write Prokka, I would consider Python.

But ultimately what matters is that the software is easy to install, and works properly. The implementation language is not important if those criteria are met.

**Comment by vinisalazar** [comment]
Thanks
