### ISSUE TITLE
Updating Prokka database

### ISSUE THREAD

**Issue by shimingt** [tseemann/prokka#380]
Dear All,

I am looking to update the database, and I found a thread that helps me to do that: https://github.com/tseemann/prokka/issues/103.

My question is do we just use the Swiss-Prot database? How about the TrEMBL database? How do I go about updating the HMM database too? I could not find this in the manual. 

Thank you.

**Comment by tseemann** [comment]
You can use TrEMBL if you prefer. Just make sure you download the `.dat` SWISS format:
You'll also need to install the SWISS::Knife perl package.
And make sure you change the `--evidence` tag to something far more liberal eg.  3 or 4
```
Usage: /home/tseemann/git/prokka/bin/prokka-uniprot_to_fasta_db [options] <uniprot.dat>
  --help          This help.
  --verbose!      Verbose output (default '0').
  --separator=s   Separator for gene/EC/product (default '~~~').
  --blank=s       Replace empty gene/EC/product with this (default '').
  --evidence=i    1=prot 2=mrna 3=homol 4=pred 5=unsure (default '2').
  --fragments!    Include 'DE Flags: Fragment;' entries (default '0').
  --minlen=i      Minimum peptide length (default '20').
  --maxlen=i      Maximum peptide length (default '100000').
  --term=s        Lineage must contain this term eg. 'Bacteria' (default '').
  --hypo!         Don't filter out hypothetical proteins (default '0').
```
