### ISSUE TITLE
Prokka database update quries

### ISSUE THREAD

**Issue by shimingt** [tseemann/prokka#381]
Hello there,

I am looking to update the database, and I found a thread that helps me to do that: https://github.com/tseemann/prokka/issues/103.

My question is do we just use the Swiss-Prot database? How about the TrEMBL database? How do I go about updating the HMM database too? I could not find this in the manual. 

Any help will be much appreciated.

Thank you!

**Comment by tseemann** [comment]
You can use TrEMBL if you like. Just use `prokka-uniprot_to_fasta_db` with the *full* _bacterial_ `uniprot_trembl.dat` file and use a lower `--evidence` setting.    You still have to call it `sprot` though in the `kingdoms/Bacteria` folder.
