### ISSUE TITLE
Will prokka work for transcriptome annotations?

### ISSUE THREAD

**Issue by Buuntu** [tseemann/prokka#382]
Will prokka with default parameters work for transcriptome annotations as well?

**Comment by tseemann** [comment]
If you have a good transcriptome assembly with mostly full transcripts  with UTR regions, it will probably work ok, yes!   

One way to test is to extract all CDS regions from an existing genome annotation, but add some 3' and 5' flanking region (50 bp?) and then try giving it to Prokka and see what happens.

But in theory it should work. The key is to have 5' upstream sequence of the start codon so Prodigcal will find a RBS.

**Comment by Buuntu** [comment]
Thanks @tseemann! Is something like Trinotate (Trinity) to assign annotations usually better for RNA-seq experiments?  I just want to get meaningful RNA-seq data with meaningful transcript names.

**Comment by apredeus** [comment]
You mean prokaryotic transcriptome, right? It's quite rare to study prokaryotic transcriptome without an assembled genome.

**Comment by tseemann** [comment]
@Buuntu this may be of interest: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6123526/

**Comment by Buuntu** [comment]
That looks very cool, thanks @tseemann!

**Comment by Lamm-a** [comment]
> 
> 
> You mean prokaryotic transcriptome, right? It's quite rare to study prokaryotic transcriptome without an assembled genome.

What about with meta-transcriptomes though?
