### ISSUE TITLE
Can't find required 'tbl2asn' in your $PATH

### ISSUE THREAD

**Issue by macgenomegue** [tseemann/prokka#389]
Hi there,
I have never had problems with prokka but today I had an issue with tbl2asn so I've upgraded to Prokka 1.13.
But now I have the following error:
"Can't find required 'tbl2asn' in your $PATH"
I've updated blast and I've also tried to add the executable in the path but I can't modify /usr/bin folder. 

Does anyone had this issue and found a solution?
Thanks in advance and... happy prokka annotat-ing

**Comment by macgenomegue** [comment]
I've fixed linking brew link --overwrite tbl2asn

**Comment by tseemann** [comment]
@macgenomegue great news - thanks for letting me know,
