### ISSUE TITLE
prokka cannot find blastp, even though is in $PATH

### ISSUE THREAD

**Issue by efr3m** [tseemann/prokka#391]
I used `prokka` before on a laptop it was flawless.
Now I moved to a HPC and I am having problems for weeks.
I install `prokka` using `conda`. When I run it on an interactive node, everything works fine.
However, when I run `prokka` on HPC, it does not find `blastp`. 
I read that this problem might be fixed by installing blast outside `conda`.  So I install ` BLAST 2.9.0+` from NCBI and I removed with `conda remove blast --force` the `blastp` within the `conda` environment.

Both `conda` and `blast` are in my `$PATH`:

`$ echo $PATH`
`/hpc-home/ro/ncbi-blast-2.9.0+-src/c++/ReleaseMT/bin:/hpc-home/ro/bin:/hpc-home/ro/miniconda2/bin:`

However, when I run `prokka` on the cluster i still get errors indicating that blastp was not found:

`Running: cat PROKKA_06272019\/IS\.faa | parallel --gnu --plain -j 1 --block 591273 --recstart '>' --pipe blastp -query - -db /hpc-home/ro/miniconda2/db/kingdom/Bacteria/IS -evalue 1e-30 -qcov_hsp_perc 90 -num_threads 1 -num_descriptions 1 -num_alignments 1 -seg no > PROKKA_06272019\/IS\.blast 2> /dev/null
Bio::SearchIO: blast cannot be found [...]`

Do you have any idea what I am doing wrong or where the problem might be?

**Comment by tseemann** [comment]
Did you activate the conda environment in your submission shell script?

**Comment by efr3m** [comment]
Hi @tseemann thanks for the answer, Yes I did and in fact, Prokka runs, but it simply does not find blastp I guess.
I also tried to remove everything and re-install (or re-install blastp both in and outside conda environment), but I have a similar problem as prokka cannot verify blastp version.
Not sure whether this is a Prokka problem or something with my system.

**Comment by happykhan** [comment]
I'm having a similar problem. 

Please check your system architecture - the provided blastp will not run on AMD chips.

**Comment by tseemann** [comment]
This does not sound like a prokka problem; it sounds like something to do with your cluster software (modules) being mixed up with conda things.
