### ISSUE TITLE
The usage of option --metagenome

### ISSUE THREAD

**Issue by Duannai** [tseemann/prokka#394]
After the binning of assembled contigs file, I get a bin set. I want to make gene prediction on each bin using Prokka. 

However, I'm confused by the option `--metagenome` when I add it to command, it will show `Terminator codon inside CDS`.

Should I still use `--metagenome`?

**Comment by tseemann** [comment]
Prokka is not designed to work with metagenomes, but people still use it as there is no option.  I added the `--metagenome` option to tell the Prodigal gene predictor to look harder for partial genes which are common in highly fragmented assemblies.  I think this error is from Prodigal, but I am not sure. But yes, you still should use it. I would remove all tiny contigs (<250bp) before running in prokka though.
