### ISSUE TITLE
Question:  How does Prokka handle candidate phyla radiation?

### ISSUE THREAD

**Issue by jolespin** [tseemann/prokka#395]
I am working on a pipeline for a manuscript and would like to include Prokka for the annotation tool.  Im building the pipeline in particular for ocean metagenomes but it will be useful for others as well.  I have a feeling my sample may have a good amount of candidate phyla radiation.  I had a few questions about this:

1. Can Prokka recognize candidate phyla radiation?  

2. Is Prokka able to detect non-standard genetic codes such as the Gracilibacteria where UGA is coded as glycine? 

3.  Does Prokka output the NCBI taxonomy identifier with each ORF call and annotation? 

4. Does Prokka take in bins or only full metagenome assemblies? 

5. Is there any examples of the annotation output? 

6. Can Prokka be used with existing blast databases such PhyloDB? 

Looking forward to using another one of your tools.  Snippy has really changed the game for me.  I’ve heard great things about Prokka through people at JGI and JCVI. 

Thank you!

**Comment by tseemann** [comment]
Prokka does none of the things you desire. It is designed for isolate assemblies, not metagenomics. You need to supply a single genetic table via `--gccode` which defaults to 11.

I am working on a metagenomic annotation engine called Mokka
https://github.com/tseemann/mokka but there is no code yet.

**Comment by jolespin** [comment]
Perfect, that makes it a lot more straight forward since I can add some steps that would determine taxonomy before hand.

Do you have any examples of the annotation output available?  I couldn't find it in the documentation.  Thanks again.

**Comment by tseemann** [comment]
No I don't have any test output, but they are standards compliant files.
There is a test file `test/plasmid.fna` which you can run prokka on and examine the output.
Here is the top of the .gbk file:

```
LOCUS       NC_017032.1            56520 bp    DNA     linear       15-JUL-2019
DEFINITION  Genus species strain strain.
ACCESSION
VERSION
KEYWORDS    .
SOURCE      Genus species
  ORGANISM  Genus species
            Unclassified.
COMMENT     Annotated using prokka 1.13.7 from
            https://github.com/tseemann/prokka.
FEATURES             Location/Qualifiers
     source          1..56520
                     /organism="Genus species"
                     /mol_type="genomic DNA"
                     /strain="strain"
     CDS             1..1041
                     /locus_tag="KCKEPNKI_00001"
                     /inference="ab initio prediction:Prodigal:2.6"
                     /codon_start=1
                     /transl_table=11
                     /product="hypothetical protein"
                     /translation="MNDFNYYKSKEIYREKYYQMPKVFFTNEKYMDLSNDAKIAYMLL
                     KDRFDYSVKNNWVDSDDNIFFIFTVEELMKLLQCREGKVSKIKKELEKAGLLKQKRGR
                     VNKRDGKIESMPNLLYLGKPEVTNQDVFKIMEEEDNTDSTVIAKIANTAKPRKINDST
                     VIAKIANTAKSSHIKDSTVIAKIADNLFYSNSIDTNRHIIDTETDQLQNQVLLDNFVD
                     IMQEDSINTFVPENVLNLIKTFSSSYSEAQQTVQTIHNAKKKAEKLEQTIVVYEELES
                     YGIDADKGLYMTLLKAYQKQKTEKVNNLQNLIFVYVKNWFVEKAIAAKLANEQRETFN
                     ELPTVSTENWLE"
```
And the .gff file:
```
##gff-version 3
##sequence-region NC_017032.1 1 56520
NC_017032.1     Prodigal:2.6    CDS     1       1041    .       +       0       ID=KCKEPNKI_00001;inference=ab initio prediction:Prodigal:2.6;locus_tag=KCKEPNKI_00001;product=hypothetical protein
```

I attempt to annotate `/gene` and `/EC_number` where possible too.
