### ISSUE TITLE
Mitochondrial genome annotation - strange behaviour

### ISSUE THREAD

**Issue by apredeus** [tseemann/prokka#397]
Hello, 

not sure how well supported this feature is, but I tried to look at mitochondrial genome annotation for human and mouse, and it generates strange results. 

Basically it predicts something like 20 to 30 CDS, and complains a lot about "Not using a valid terminator codon" etc - even when translation table 2 is specified with --gcode.

**Comment by tseemann** [comment]
The mitochondrian mode was never a serious solution, it was a bit of a hack I tried for @sjackman .

I have had a couple of reports recently about the invalid terminator codon error, so this could be something that has changed in one of the tools Prokka uses.

Can you send me the mtDNA FASTA file? 
Or give me an accession number of a similar one in Genbank that causes the error?

Thanks!

**Comment by apredeus** [comment]
Sure, here's human chrM: https://www.dropbox.com/s/yfj900j0thjgeph/chrM_human.fa

Here's the same for the mouse: https://www.dropbox.com/s/ts1oz5e7prae0q5/chrM_mouse.fa

Thank you!

**Comment by sjackman** [comment]
I was trying to annotate plant mitochondrial genomes, which are super weird, and was experimenting with Prokka, and Torsten helped me out with some hacking of Prokka for that purpose.
To annotate a metazoan mitochondrion, I'd suggest Mitos http://mitos.bioinf.uni-leipzig.de/index.py

**Comment by apredeus** [comment]
Thank you. I just thought I'll give it a shot with Prokka. Since it didn't work I've ran orffinder + diamond vs NR on it since then and found all the proteins.

**Comment by sjackman** [comment]
You'll usually need to annotate rRNA and tRNA as well.

**Comment by apredeus** [comment]
Yes, it was also quite strange. Prokka predicted tRNAs for human/mouse exactly, but gave double the amount (44 tRNAs) for the organism I needed. 

MITOS is a nice suggestion, thank you! Apparently it's been replaced by MITOS2 now. MITOS1 predicted 4 rRNA genes in my metazoan mtDNA. Seems like annotating mitochondria is much harder than one would expect :)

**Comment by sjackman** [comment]
> Seems like annotating mitochondria is much harder than one would expect :)

Don't get me started. I lost a year of my life trying to assemble and annotate a plant mitochondrion. I'll never get that time back. https://www.biorxiv.org/content/10.1101/601104v1

In metazoan mitochondria, it's common for tRNA to overlap the TAA stop codon of a coding gene. The transcript is cut at the TA or T, and the As are added by polyadenylation. So the result is that any Txx codon can serve as a stop codon, if it's directly adjacent to a tRNA. So annotating ORFs isn't sufficient to identify the stop codon of a gene in metazoan mitochondria. If you think that's weird, plant mitochondria are at least 5 times as weird.
