### ISSUE TITLE
No CDS

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [tseemann/prokka#400]
Hello,

I'm having an issue with running prokka on my servers. It systematically report no CDS whatever the input. Last example is from a test run of Pantagruel which is using prokka as dependency. As no CDS is found where it should, the pipeline crash. 

This is a problem I had before and i wrote an issue  : https://github.com/tseemann/prokka/issues/306. We did not find a solution and also in the current case, it does not appears to manifest in the same exact fashion. Previously the copied version of the genome fasta file was empty, currently it is not. 

Though I still get a near instantaneous execution of  aragorn/Barrnap/prodigal as it took 1 sec for the 3 of them to execute. Here are the logs : [Bradyrhizobium_sp_cf659.log](https://github.com/tseemann/prokka/files/3451534/Bradyrhizobium_sp_cf659.log)

Any idea?

Best,

Seb

**Comment by tseemann** [comment]
What is 'pantagruel` ?

**Comment by Sebastien-Raguideau** [comment]
Hello,

So pantagruel is a recent pipeline to compare gene phylogenetic tree with species phylogenetic tree and track back gene evolution and transfer in the context of species : [pantagruel](https://github.com/flass/pantagruel). I'm going through their Test, after installation.

From `brew upgrade prokka` I get
`Error: brewsci/bio/prokka 1.13 already installed`

Tried 
```
brew upgrade prokka@1.13.7
Error: No available formula with the name "prokka@1.13.7" 
```

```
>NZ_FOQJ01000025.1 Bradyrhizobium sp. cf659, whole genome shotgun sequence
CGGGCACTGACCAGCTTGATCGTGGGATAACGCGCCAGCTGCTGCCGCGCCTCGGCCAGGATGTCCAGCGGCGGCTTGTG
ATCGTGGCCGAGCAGACCATGCGAGTGGCCAGCGAAGCGGTTGCGCGGCAGGCCGATATCGAGAACGGTAACCTTGCGGC
GGGCCCGGCCGAGCTGCAGGGCGCCGGCGAGACCGGCAAAGCTGCCGCCAATGATGATAACGTCATCCATGGTGATGAGC
TCCGTGTCGTGGGTGGAGAGGGTTGGCTGGGGCCTGGCGGTGGCCTGGGCGCGGGCGAGGCTGATGGTGGAAAGCGCGGC
CAACTTCAGCAGGGTCCGTCGTTGCATGGGATCCCTCGTGCTTTAGGTCGGCGCAATATCGTCAGACGATACGCGCTCCA
GACGGGCAGCGAGCATGGCTTCGGTATCGACGAGAAAGTCGCCCATCACTGTGTTGGCCGGCCGGACAATGCCGCATTCG
AGATCGCCGGGCGCCCCGGGAAACTTGATTTGGAGGACAAGTTGAAACCTAACCATTGGCTTGCACATTTCGGATACTTC
ATAGTATCGTAATGCTGAATTAGAATACTGTCAAGTACCGGAATTGCCGTGACCGAAAACAAACAGGGCCGGCGCGGCCG
GCCCGCCAACGAGGCGCTTGGCCAAACGATCGTCGACGCCGCGCGCGAACTCTTTGTGGAATTGGGTTTTCAGGCGACGA
```

It is a normal fasta file. What I failed to precise is that running, for instance the aragorn command outside of prokka does yield some results, here is the output : [aragorn_test.txt](https://github.com/tseemann/prokka/files/3456114/aragorn_test.txt)

I've been looking at the perl code of prokka quickly, I do not code in perl at all, though I got that basically the stdout of commands is parsed directly without temporary files. My intuition is that some fuckery happens with my server setup making this step yield nothing. I mean, why would it run fine outside of prokka but not within?
I'd like to check that out : write the output of commands in temporary files and then reopen them for parsing. Do you think you could advise me on how to do that in perl? 

Best,

Seb

**Comment by tseemann** [comment]
Try `brew update` then `brew upgrade prokka`.

**Comment by Sebastien-Raguideau** [comment]
Hello

I managed to write the output of aragorn into a file and read it back. It worked. But then all other command started to work also. And then just relaunching a non modified version of prokka worked fine. 

My issue sort of disappeared on it's own? I Just spent 2 hours trying to store output of command in a file and read it back in perl, I did not install or change  anything else and the issue disappeared.... It's  unsatisfying :) 

After that I also installed prokka 1.14 and in the same fashion no issue. Which is good. 

So I suppose this is resolved?

**Comment by flass** [comment]
Hi there,

I see my pipeline [pantagruel](https://github.com/flass/pantagruel) is causing trouble... I am having the same issue:
even though this is using the script out of the `pantagruel` pipeline:
```
prokka-genbank_to_fasta_db assemblies/GCA_000017705.1_ASM1770v1/GCA_000017705.1_ASM1770v1_genomic.gbff
Will use first of (protein_id locus_tag db_xref) as FASTA ID
Parsing: CP000789
Parsing: CP000790
Parsing: CP000791
Done.
```
the source data file is available there:
```
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/017/705/GCA_000017705.1_ASM1770v1/
```

I suppose there is some sort of conflict between `pantagruel` dependencies that somehow lead to that bug...

my `prokka` install is:
```
brew info prokka
brewsci/bio/prokka: stable 1.14.0 (bottled)
Rapid annotation of prokaryotic genomes
https://github.com/tseemann/prokka
/home/ubuntu/.linuxbrew/Cellar/prokka/1.14.0 (120 files, 530.8MB) *
  Poured from bottle on 2019-09-04 at 14:26:57
From: https://github.com/brewsci/homebrew-bio/blob/master/Formula/prokka.rb
==> Dependencies
Required: aragorn ✔, barrnap ✔, bioperl ✔, blast ✔, hmmer ✔, infernal ✔, minced ✔, parallel ✔, prodigal ✔, tbl2asn ✔, less ✔, perl ✔
```
on a fresh VM with Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-60-generic x86_64)

there is no other installed BioPerl modules than the home-brew ones:
```
apt list --installed bioperl
```

I hope this may help resolving the issue

Best wishes,

Florent

**Comment by flass** [comment]
sorry for the double post, I realise my error is more clearly documented in this other issue: #393.

**Comment by tseemann** [comment]
@Sebastien-Raguideau i solved your problem!

All the genes in your genome have `/product="hypothetical protein"`. By default `prokka-genbank_to_fasta_db` ignores those, because they are not useful annotations.

THe `--help` has this option:
```
  --hypo!         Include 'hypothetical protein' genes (default '0').
```

You can use the `--hypo` option but it won't help your annotations.
You need a better reference genome.

There are many other _V.campbellii_ genomes in Refseq to choose from:
```
051011E  200612B               ATCC_BAA-1116_GCF_000464435.1  CCS02    LB102
051011F  20130629003S01        CAIM115                        DS40M4   LMB29
051011G  602L                  CAIM1500                       E1       UMTGB204
1114GL   ATCC_25920_CAIM_519T  CAIM_519                       HY01     VIB391
151112C  ATCC_BAA-1116         CAIM_519_NBRC_15631            LA16-V1
```


grep -c product GCA_000017705.1_ASM1770v1_genomic.gbff 
6225

**Comment by flass** [comment]
Hi Torsten,

thanks for solving this... that will teach me to use GenBank annotations instead of RefSeq.

That said, I don't think think this 'solution' covers the original issue reported by @Sebastien-Raguideau about the absence of annotation extraction from [NZ_FOQJ01000025.1](https://www.ncbi.nlm.nih.gov/nuccore/NZ_FOQJ01000025.1) (part of `pantagruel` test dataset), which is a RefSeq record and has all the correct product fields.

@Sebastien-Raguideau : if this is a `pantagruel`-specific issue, maybe we can bring that into a new issue for the pipeline?

Beest wishes
Florent
