### ISSUE TITLE
prokka-uniprot_to_fasta_db skips proteins

### ISSUE THREAD

**Issue by MichWeb75** [tseemann/prokka#401]
Dear developers,

I have updated **sprot** db, after I was wondering why Prokka annotated IS110 family transposases as hypothetical protein, even **Uniprot blast** knows the protein sequence.

What I found is that the function :
**prokka-uniprot_to_fasta_db** reduces the **uniprot_sprot_bacteria.dat** from more than 300,000 entries to 20,000. Is this reduction due to performance reasons ? 
Can I keep the entire database for gene annotation ? Apparently Prokka is missing some gene names and annotates them as hypothetical .

Best, Michael

**Comment by tseemann** [comment]
As stated in the paper and here
https://github.com/tseemann/prokka#the-core-blast-databases

"Prokka uses a variety of databases when trying to assign function to the predicted CDS features. It takes a hierarchial approach to make it fast.
A small, core set of well characterized proteins are first searched using BLAST+. This combination of small database and fast search typically completes about 70% of the workload. Then a series of slower but more sensitive HMM databases are searched using HMMER3.

The initial core databases are derived from UniProtKB; there is one per "kingdom" supported. To qualify for inclusion, a protein must be (1) from Bacteria (or Archaea or Viruses); (2) not be "Fragment" entries; and (3) have an evidence level ("PE") of 2 or lower, which corresponds to experimental mRNA or proteomics evidence."

Plus, it is not possible to store a big file in github.

You are welcome to replace `Bacteria/sprot` with whatever you ike.

Prokka 1.13.7 now included the ISFinder database.
