### ISSUE TITLE
gram stain

### ISSUE THREAD

**Issue by alienzj** [tseemann/prokka#408]
@tseemann Hello, Torsten
Could I get gram stain information from prokka results?
Maybe can't, because prokka have **--gram** parameters when using signalp.

**Comment by tseemann** [comment]
No you can't.  There is no "genomic" method to infer gram stain that I know of.  Prokka does not need the `--gram` option. In fact, I personally _never_ use it.

**Comment by alienzj** [comment]
Thanks for your reply :100:
