### ISSUE TITLE
update_manual.sh relies on dependency which cannot be installed

### ISSUE THREAD

**Issue by BioSina** [tseemann/prokka#413]
update_manual.sh uses the depenceny pandoc, which uses cabal, which tries to use ghc, which fails because a few of the libraries used are not compatible with the current base. 
Error shown: 

> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: asn1-encoding, base, tls,
> http-client-tls, pandoc
Search shows at least asn1-encoding is not compatible with base.

Maybe there is a possibility to do this without pandoc? Trying to run update_manual.sh before pandoc is installed successfully unfortunately erases the current manual to an empty file.

**Comment by tseemann** [comment]
I completely forgot Prokka even had that!
It is not designed for users to run.
I have updated it and will remember to do so for each new release.
Thanks for letting me know.
