### ISSUE TITLE
[enhancement] re-annotate genome with same locus tags

### ISSUE THREAD

**Issue by alexweisberg** [tseemann/prokka#415]
Hi,
Prokka is fantastic and has been really useful for my research. I have a feature request or question in case it is already implemented. I would like to re-annotate a set of genomes with the latest version of prokka, however I would like to keep the CDS calls and locus tag numbers from the original annotation so that they are consistent with previous analyses. Essentially I would just like updated product/gene names/note lines and annotations (especially IS family information) for genomes that were originally annotated years ago. Is this possible in the current version of the program? Thanks!

**Comment by tseemann** [comment]
Thank you for the kind words @alexweisberg 
It is not possible to do this with Prokka as-is
If you made a custom database from the original annotation _and_ wrote some post=processing scripts it could work
if i wrote Prokka 2.x it will be a feature, but that is a long time away

**Comment by alexweisberg** [comment]
Hi, thanks for letting me know. I will look into writing a filtering script as an option for now.
