### ISSUE TITLE
Source of IS sequences

### ISSUE THREAD

**Issue by oschwengers** [tseemann/prokka#416]
Dear Torsten,
unfortunately, I missed you to personally talk about this in Dubrovnik (btw, very nice IMMEMXII talk!). I'm keen to know how you got the IS sequences bundled within Prokka. As far as I know, they're not officially provided for download at the ISFinder web page. I'd really like to use them in some of our analyses in an offline manner. Any hint/idea/comment highly appreciated!
Best regards and cheers!

**Comment by tseemann** [comment]
I screen-scraped them from ISfinder, likely in violation of their licence. i had tried for >10 years to get access to the database in machine readable form without success.  I think it is essentially unmaintained now, so I refuse to let a good resource go wasted when prokka annotations benefit greatly from them.  In this case i tried to ask for permission patiently, but now I will ask for forgiveness instead if it comes to that.

**Comment by oschwengers** [comment]
Oh, I see and absolute agree with you! It would really be a shame if this sort of well annotated data would past away...
Thanks for the **very** fast answer :-)
