### ISSUE TITLE
Question: aerobic and anaerobic

### ISSUE THREAD

**Issue by alienzj** [tseemann/prokka#417]
Hello, @tseemann 
Give the prokka genome,
can give me the oxygen information？

Best regards ~
Jack

**Comment by tseemann** [comment]
No, i can not tell if your bacteria is anaerobic or aerobic from the annotation.

If you can guess the species/genus of the bacteria, you can google whether it is anaerobic or aerobic ?

**Comment by alienzj** [comment]
Thanks very much.
