### ISSUE TITLE
prokka getting stuck on tbl2asn

### ISSUE THREAD

**Issue by nixon444** [tseemann/prokka#420]
Hi there,

I have noticed lately that my prokka jobs are getting stuck at the tbl2asn stage of the pipeline. On previous jobs, my large datasets would assemble in a few days at most. Now I have tried to re-annotate after filtering out the majority of contigs (they were too short) and the job was aborted on the university server I use because it was running for 7 days. When I checked the log, it had been stuck at the following point in the process since 2 hours into the job (I removed file paths from the below):

Running: tbl2asn -V b -a r10k -l paired-ends -M b -N 1 -y 'Annotated using prokka 1.14.0 from https://github.com/tseemann/prokka' -Z prokka_G6\.err -i prokka_G6\.fsa 2> /dev/null

Is this a known issue? Anything suggestions? We have lots of data to analyse and not a huge amount of time...

Cheers!

**Comment by tseemann** [comment]
How many contigs and what total bases? I assume metagenome.
Filtering all small contigs < 500 is important.
Also, you can split your fasta into separate fasta and annotate with separate prokka jobs.
If you don't want a .GBK file you can comment out theh `tbl2asn` line in the prokka script.

**Comment by Allerdrengen** [comment]
@tseemann Would reducing my contig size fix this issue? I am also running metagenome samples.
I am running my jobs on a cluster-service, where all tools (including Prokka) are installed in advance. This also prevents me from altering the script and commenting out tbl2asn, as you suggest. I don't expect there to be a commandline comment that would get the job done?

**Comment by Zhaoju-Deng** [comment]
hello Allerdrengen, have you solved the problem? I am running into the same issue with metagenomic sequence analysis with prokka and stuck at tbl2asn for days.
