### ISSUE TITLE
Antimicrobial genes annotation result is different from blast's

### ISSUE THREAD

**Issue by jlli6t** [tseemann/prokka#422]
Prokka returned some result of antimicrobial resistance genes, when i blast protein sequences to card, it returns different result to me, like geneA annotated as some type of ARG in prokka and geneB returned as hypothetical protein (NOT ARG), but with blast, geneB returned a type of ARG (different from geneA), but geneA annotated as nothing, geneA was filtered due to low alignment identity.

Could you give more information about this antimicrobial resistance genes annotation part? Thanks a lot.

jlli6t

**Comment by tseemann** [comment]
Prokka uses the NCBI ARG database, not CARD.   NCBI has more entries than CARD.  I am updating the NCBI DB included in Prokka soon.

**Comment by tseemann** [comment]
I have now documented the process in the README.
