### ISSUE TITLE
User HMM database Option

### ISSUE THREAD

**Issue by Calebros** [tseemann/prokka#424]
Hello, 

I am trying to use a custom hmm database using the --hmms option and encountering an error

`prokka --compliant --outdir ./vHIT317 --prefix vHIT317 --locustag vHIT314 --increment 5 --genus Escherichia --species x --strain vHIT317 --kingdom Viruses --usegenus --proteins /mnt/c/Users/bnichol1/Downloads/NC002641\ HIT-reference.gb --hmms RVDBv15.1  --cpus 3 --force ./vHIT317_SEQconsensus.fasta`

> Your HMM is not indexed, please run: hmmpress HAMAP

I've run HMMpress on the .hmm database file and generated the .h3f .h3i .h3m and .h3p files.  I've also tried using the same command as above except with `--hmms RVDBv15-1.hmm` 

Running prokka --listdb displays:

>[13:20:18] * Genera: Brachyspira Enterococcus Escherichia Staphylococcus
>[13:20:18] * HMMs: HAMAP RVDBv15-1
>[13:20:18] * CMs: Bacteria Viruses

I've tried running the script using the commands `--hmms HAMAP` and `-hmms HAMAP.hmm` and still receive the same error message.  Is there a bug when trying to use the --hmms command or am I improperly invoking the command? 

Any help from anyone would be greatly appreciated, please let me know and I can also provide additional information!

**Comment by tseemann** [comment]
```
# secondary sources are a series of HMMs
unless ($kingdom eq 'Viruses') {
  for my $name ( hmms() ) {
    my $dbfile = "$dbdir/hmm/$name.hmm";
    if (-r $dbfile) {
      push @database, {
        DB  => $dbfile,
        SRC => "protein motif:$name:",
        FMT => 'hmmer3',
        CMD => $HMMER3CMD,
        VERSION => 3,   # without this, latest Bioperl goes into infinite loop
      }
    }
    else {
      msg("Will not use $name HMM database, $dbfile not installed.");
    }
  }
}
```

**Comment by Calebros** [comment]
Hi Torsten,

I'm not sure how I missed that section of the code!  After I modified the check for viruses, I still could not get it to work.  Full admission, I'm not a coder by trade, but I think it is related to this section:

`# if user supplies a trusted set of HMMs, we try these first!`
`if ($hmms) {`
 ` msg("Preparing user-supplied primary HMMER annotation source: $hmms");`
 ` **-r "$hmms.h3i"** or err("Your HMM is not indexed, please run: hmmpress $hmms");`
  `my $src = $hmms;`
  `$src =~ s{^.*/}{};`

the -r $hmms takes directly from the hmm option provided by the user without adding the relational link to where the databases are found.  When I added the full path to the hmm library in the --hmms variable it worked like a charm.

You've said in previous posts that there are better tools for viral annotation, do you have any recommendations?

Thanks again for your help, especially in using Prokka for something which it wasn't intended!

**Comment by tseemann** [comment]
@Calebros looks like you have found a bug - if you supply a HMM it should use the full path relative to when you invoked prokka.  I need to add `$hmm = abs_path($hmms)` at the _top_ of the script.

**Comment by tseemann** [comment]
@Calebros i think i misread your original issue (besides the Viruses issue). You seem to have installed your custom HMM into the `prokka/db/hmms` folder.  Those get run automatically, you do not specify them with `--hmms`. that option is for when you have your own HMM in your own folder somehwere. In your case thoiugh, they dont get riun automaticall becuase it is VIruses.
