### ISSUE TITLE
Could you provide an option for using prodigal training model ?

### ISSUE THREAD

**Issue by current788** [tseemann/prokka#429]
When we performed Prokka, we found the length of alleles within a locus might have large variant. Therefore, we tried several prodigal options, and  we found that the length of the predicted CDS will be influenced by the genetic code.  We have compared the predicted CDSs based on standard code 11 with those from prodigal-trained model, the lengths of predicted genes were not consistent if more than one start codons within an in-framed. However, if we use trained model, the results were much more consistent. So, could you provide an option for Prokka to use prodial training model ? Many thanks!

**Comment by tseemann** [comment]
Yeah it's a common request.
Can you describe each command/step you used to train a model?
I would want to include that in the documentation for this new feature.

**Comment by chen1i6c04** [comment]
> 是的，這是常見的要求。
> 您能否描述用於訓練模型的每個命令/步驟？
> 我想將其包含在此新功能的文檔中。

Prodigal 2.6.3
`prodigal -i sequence.fasta -t training_file.trn`

If training file exists, prodigal will use it to predict locus, otherwise write a training file.

**Comment by tseemann** [comment]
Oh, I assumed you were training it on existing gene calls.
Does prodigal support using existing gene calls? Maybe via `-i reference.gbk` format?
If not, then pre-training on sequence.fasta will help a bit (if it is a closed genome) but not as much as being able to give it true CDS starts/stops.

**Comment by chen1i6c04** [comment]
Prodigal need start codon usage (ATG vs. GTG vs. TTG), ribosomal binding site (RBS) motif usage, GC frame plot bias, hexamer coding statistics, and other information necessary to build a training model.

**Comment by tseemann** [comment]
@chen1i6c04 yes, but it must be _guessing_ what is the correct start codon, because all it has is the genome sequence with no annotated "correct" CDS regions.  it would be better if it could include "experimentally proved" start positions, say by using SwissProt evidence code <= 2 proteins.
