### ISSUE TITLE
Question about IS annotations 

### ISSUE THREAD

**Issue by avonm** [tseemann/prokka#431]
Hi, 

I have recently used Prokka 1.14.0 re-annotating a couple of E. coli chromosomes with the hope to get the IS elements annotated (from the ISFinder database). 

This works great, however I have one which and that is that the whole IS element is annotated and not only the CDS. For example, the IS element IS1X2 is 768 bp long containing a CDS (294 bp) encoding the transpose. In the end you would have a Mobile element annotation spanning the whole 768 bp as well as a CDS for the actual transpose. 

Is that something that could be possible in future versions or maybe something you are already working towards. 

Best,
Astrid

**Comment by tseemann** [comment]
I only annotated the tranposase because prokka is protein-based only.
Newer version of Prokka may one day support nucleotide databases.
This is an open issue: https://github.com/tseemann/prokka/issues/421
