### ISSUE TITLE
Prokka default DBs

### ISSUE THREAD

**Issue by YiJessePi** [tseemann/prokka#433]
Hi,
I've downloaded the latest prokka version from conda and was wondering which are the default dbs that were used for annotation?
In the tsv file I find gene names, COG id and EC number. In the GFF I also find uniprot id.
I'm asking because I recently came across a paper which stated that he used the default dbs which are uniprot, refseq, pfam and TIGRFAM but didn't find evidence for the last two.

Lastly, in the tsv file I sometimes find genes with only gene name (without and db id) can you tell their source db? and base on which db do you set an EC number?

Many thanks!

**Comment by tseemann** [comment]
TIGRFAMs and PFAM were removed long ago.
The databases depend on what options you provide.
In 1.14.x it is:
* ISfinder transposases
* NCBI AMR genes
* Swissrpot bacteria evidence code mRNA or better
* HAMAP HMMs

**Comment by YiJessePi** [comment]
Thanks! I really appreciate you quick response.
So the EC number is set based on Swissprot? and COG id based on NCBI AMR genes?

I the output tsv file I found some genes without any other db id, can you please tell how can i find their resource. I'm asking because I want to cluster them based on function, pathway etc. and its much easier with id than gene name (if possible).

Thanks again!

**Comment by tseemann** [comment]
I just checked `~/git/prokka/db/kingdom/Bacteria/{IS,AMR,sprot} ~/git/prokka/db/hmm/HAMAP.hmm`

`IS` has COG
`AMR` has neither
`sprot` has EC and COG.
`HAMP` has neither

**Comment by YiJessePi** [comment]
Thanks for your answer and recommendations.
So I dug into the source of each annotation a bit more and maybe my findings will be helpful to other prokka users:
The gff file is more informative than the tsv for the purpose-
IS- genes annotated by IS will have the ISFinder tag followed by ID something like: inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:ISfinder:IS1310, and might also have a COG id. Both the COG and the IS id are present in the tsv file.

AMR-  You will find BARRGD as the source followed by id with the following format  A7J11_*. For example: inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:BARRGD:A7J11_00955. You won't find this ID in the tsv file.

Sprot- In addition to the EC and COG (if exsits) you will find UniProtKB followed by ID. Example: UniProtKB:P45780.  The cog and the ec will apear in the tsv file (if exsits) but not uniprot ID not.

HAMAP- HAMAP followed by HAMAP id. in example: HAMAP:MF_00984. Again this information will be found only in the gff.

Hope it will help someone :)

**Comment by tseemann** [comment]
The AMR genes will change again soon to be the `NG_xxxxxxxx` accessions that NCBI have changed to.

The TSV was never meant to be used as the master annotation table. That is what the GBK is, because it supports these special annotations using a controlled vocabulary. 

But your summary is good.  I will review it and see how i could improve TSV output. Thank you for your efforts.
