### ISSUE TITLE
Issues installing prokka with brew, prokka 1.1.4.0

### ISSUE THREAD

**Issue by evanbiederstedt** [tseemann/prokka#438]
Hi @tseemann 

This issue appears to be unique. My problem is that the errors do not really make sense, so I'm not sure how to debug. The brew package may need to be tweaked somewhat. 

Here are the errors:

```
Looking for 'blastp' - found /usr/local/bin/blastp
Determined blastp version is 2.10
Prokka needs blastp 2.8 or higher. Please upgrade and try again.
```

and 

```
Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
Determined makeblastdb version is 2.10
Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.
```

Naturally, I'll try re-installing outside of brew....but this is something to investigate. 

*** 
Here are my commands and outputs:

I tried using `prokka` on my macbook with flags `--gcode`, `--kingdom Bacteria`, `--outdir`, and `--prefix`. 

I got the following error:

```
[12:42:40] This is prokka 1.14.0
[12:42:40] Written by Torsten Seemann <torsten.seemann@gmail.com>
[12:42:40] Homepage is https://github.com/tseemann/prokka
...
...
[12:42:41] Appending to PATH: /usr/local/Cellar/prokka/1.14.0/bin
[12:42:41] Looking for 'aragorn' - found /usr/local/bin/aragorn
[12:42:41] Determined aragorn version is 1.2
[12:42:41] Looking for 'barrnap' - found /usr/local/bin/barrnap
[12:42:41] Determined barrnap version is 0.9
[12:42:41] Looking for 'blastp' - found /usr/local/bin/blastp
[12:42:41] Determined blastp version is 2.10
[12:42:41] Prokka needs blastp 2.8 or higher. Please upgrade and try again.
````

Darn. 

So I tried re-installing with `brew`:

```
$ brew reinstall brewsci/bio/prokka
....
[12:43:43] Appending to PATH: /usr/local/Cellar/prokka/1.14.0/bin
[12:43:43] Cleaning databases in /usr/local/Cellar/prokka/1.14.0/db
[12:43:43] Cleaning complete.
[12:43:43] Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
[12:43:43] Determined makeblastdb version is 2.10
[12:43:43] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall brewsci/bio/prokka`
```

That was odd. So I tried:

```
$  brew postinstall brewsci/bio/prokka
==> Postinstalling prokka
==> /usr/local/Cellar/prokka/1.14.0/bin/prokka --setupdb
Last 15 lines from /Users/evan/Library/Logs/Homebrew/prokka/post_install.01.prokka:
2019-11-12 12:43:59 -0500

/usr/local/Cellar/prokka/1.14.0/bin/prokka
--setupdb

[12:44:00] Appending to PATH: /usr/local/Cellar/prokka/1.14.0/bin
[12:44:00] Cleaning databases in /usr/local/Cellar/prokka/1.14.0/db
[12:44:00] Cleaning complete.
[12:44:00] Looking for 'makeblastdb' - found /usr/local/bin/makeblastdb
[12:44:00] Determined makeblastdb version is 2.10
[12:44:00] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again.
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall brewsci/bio/prokka`
```

Thanks, Evan

**Comment by evanbiederstedt** [comment]
Apologies, I see a related issue here I missed: 
https://github.com/tseemann/prokka/issues/435

**Comment by tseemann** [comment]
Yes I am trying to get the fixed Prokka into brew, but it is failing the blast steps for some reason.

Quickest solution until then: 
```
brew switch blast 2.9.0
```
Or edit `$(which prokka)` and change `    MINVER  => "2.8",` to `    MINVER  => "2.1",`

**Comment by evanbiederstedt** [comment]
Hi @tseemann 

Ah, I see. Yes, I think I will have to manually install it, as `brew switch` seems not to access older versions. 

```
$ brew switch blast 2.9.0
Error: blast does not have a version "2.9.0" in the Cellar.
blast installed versions: 2.10.0
$
$ brew switch blast@2.9.0
Error: blast@2.9.0 not found in the Cellar.
```

Thank you for the help on this; I'll give it a shot.

**Comment by tseemann** [comment]
Yes.... you must have run `brew cleanup` unfortunately, or it ran automatically.
Installing old version in brew is not easy, requires manual digging into github... sorry
Please just edit your `prokka` script.

**Comment by evanbiederstedt** [comment]
> Please just edit your prokka script.

Yes, this seems far more sensible. Do let me know when the brew installation is stable though! It's a dream to update/install via brew (for somewhat irrational reasons, I admit).

Thank you for the help here, @tseemann

**Comment by tseemann** [comment]
@evanbiederstedt it seems NCBI has pulled/removed 2.10.0 from their web site. We found other problems with it, so NCBI must have noticed.

**Comment by evanbiederstedt** [comment]
Yes, it appears there are problems with the binaries, e.g. shared libraries not statically linked properly. I'm informally told that there will be a fix very soon for version 2.10.0

Thank you again for the help

**Comment by tseemann** [comment]
@evanbiederstedt 2.10.0 was withdrawn from brew 2 days ago.
```
brew uninstall --force blast
brew update
brew reinstall prokka
```

**Comment by evanbiederstedt** [comment]
Hi @tseemann 

Yep, I totally understand. 

To reduce any confusion, what I meant to say is: after looking into why 2.10.0 was withdrawn from brew and the NCBI website, the bug was improperly linked shared libraries. It should be a quick fix on their part, and it will be back up soon-ish (I suspect). In the meantime, your advised commands are perfect. 

Thanks!

**Comment by tseemann** [comment]
@evanbiederstedt no worries!  i will wait until i get an official email announcement from the blast mailing list before I package it this time. lesson learnt!

**Comment by evanbiederstedt** [comment]
Hi @tseemann 

It looks like the blast v2.10 is up in running, causing the brew install issues once more. Naturally, the fixes discussed in this issue should work for the time being, but I suspect there will be more 2.10 errors for brew users. 

Arguably not a massive issue---thanks!
