### ISSUE TITLE
Wrong annotation at /gene ?

### ISSUE THREAD

**Issue by ashdederich** [tseemann/prokka#442]
I am annotating bacterial genomes and was doing some spot-checking of the annotations. One genome has the /gene "aroQ", while another genome has the /gene "aroQ1". When I blast the protein sequence for "aroQ1" through blastp on NCBI, it comes up with the gene "aroQ", not "aroQ1". Is there a reason that I am getting this error from annotating my genomes through prokka?

**Comment by tseemann** [comment]
You can't expect to get the same exact answer when you use a tiny Prokka database versus a giant NCBI database.

I am using official SwissProt names:
```
prokka/db/kingdom/Bacteria $ grep aroQ sprot
>O30557 4.2.1.10~~~aroQ1~~~3-dehydroquinate dehydratase 1~~~COG0757
>A3M692 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~
>P43877 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>Q48255 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>P9WPX7 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>P15474 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>Q5SIL5 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>Q8ZAX1 4.2.1.10~~~aroQ~~~3-dehydroquinate dehydratase~~~COG0757
>P42517 5.4.99.5~~~aroQ~~~Monofunctional chorismate mutase~~~
>Q9HU05 5.4.99.5~~~aroQ~~~Monofunctional chorismate mutase~~~COG1605
>Q93LJ4 5.4.99.5~~~aroQ~~~Monofunctional chorismate mutase~~~COG1605
```
Clearly your protein was closer to the `aroQ1` sequence than the others, amongst those that Prokka has.

Prokka is not perfect. If you need NCBI quality annotations please user the slower PGAP: https://github.com/ncbi/pgap/wiki
