### ISSUE TITLE
Prokka issue :Can't locate Bio/Root/Version.pm in @INC

### ISSUE THREAD

**Issue by RamaSravanimeduri** [tseemann/prokka#446]
Hi Team,

I am trying to install  Prokka locally and i am facing the below issue.

$prokka
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) 

Thanking you,
Sincerely,
Rama.

**Comment by tseemann** [comment]
You don't have Bioperl installed.

Did you follow these instructions? https://github.com/tseemann/prokka#installation

**Comment by RamaSravanimeduri** [comment]
Yes, I have followed the instructions written for macos. I executed all the commands but still unable to get prokka up.

**Comment by RamaSravanimeduri** [comment]
I reran the commands , kindly find the summary report for the first command.
sudo cpan Time::Piece XML::Simple Digest::MD5 Bio::Perl

Test Summary Report
-------------------
t/00-compile.t         (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/Perl.t               (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=7, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.07 cusr  0.02 csys =  0.12 CPU)
Result: FAIL
Failed 2/7 test programs. 1/2 subtests failed.
make: *** [test_dynamic] Error 2
  CJFIELDS/Bio-Procedural-1.7.4.tar.gz
10 dependencies missing (Bio::DB::EMBL,Bio::DB::GenBank,Bio::DB::GenPept,Bio::DB::RefSeq,Bio::DB::SwissProt,Bio::Root::Test,Bio::Root::Version,Bio::Seq,Bio::SeqIO,Bio::Tools::Run::RemoteBlast); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports CJFIELDS/Bio-Procedural-1.7.4.tar.gz

**Comment by tseemann** [comment]
Something is wrong with your system installation, and I am unable to fix it.

Please try the `conda` method of installation.
https://github.com/tseemann/prokka#installation

**Comment by RamaSravanimeduri** [comment]
Hi  Team,

Even after following the conda instruction, I am still getting same issue.

$ prokka
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module)

**Comment by tseemann** [comment]
What do the following commands print?
1. `echo $PATH | tr ":" "\n" | nl`
2. `which conda`
3. `which perl`

**Comment by RamaSravanimeduri** [comment]
Dear Team,

Thank you, I was able to install on the cluster.

Sincerely,
Sravani

**Comment by franciscozorrilla** [comment]
Hi, just wanted to report the strange situation I ran into.
I had a perfectly working prokka environment and I was running a new batch of jobs when suddenly prokka got stuck for around 20 minutes at:
```
[17:53:50] Running: cat prokka\/ERR260189\.bin\.16\.p\/ERR260189\.bin\.16\.p\.HAMAP\.hmm\.tmp\.35846\.faa | parallel --gnu --plain -j 4 --block 63478 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-09 --cpu 1 /g/scb2/patil/zorrilla/conda/envs/prokkaroary/db/hmm/HAMAP.hmm /dev/stdin > prokka\/ERR260189\.bin\.16\.p\/ERR260189\.bin\.16\.p\.HAMAP\.hmm\.tmp\.35846\.hmmer3 2> /dev/null
```
I got impatient and killed the process with htop, and then when I tried to run prokka again I got the following error:
```
Can't locate Bio/Root/Version.pm in @INC (you may need to install the Bio::Root::Version module) (@INC contains: /g/easybuild/x86_64/CentOS/7/haswell/software/Perl/5.30.0-foss-2019b/lib/perl5/site_perl/5.30.0/x86_64-linux-thread-multi /g/easybuild/x86_64/CentOS/7/haswell/software/Perl/5.30.0-foss-2019b/lib/perl5/site_perl/5.30.0 /g/easybuild/x86_64/CentOS/7/haswell/software/Perl/5.30.0-foss-2019b/lib/perl5/5.30.0/x86_64-linux-thread-multi /g/easybuild/x86_64/CentOS/7/haswell/software/Perl/5.30.0-foss-2019b/lib/perl5/5.30.0) at /g/scb2/patil/zorrilla/conda/envs/prokkaroary/bin/prokka line 34.
BEGIN failed--compilation aborted at /g/scb2/patil/zorrilla/conda/envs/prokkaroary/bin/prokka line 34.
```
I then ran the following
```
conda update prokka
cpanm Bio::Root::Version
```
I have no idea what went wrong but now prokka seems to be working again.
Just thought this was very strange behavior.

**Comment by ramnageena11** [comment]
I am Also getting this error:
base) powersequence@CH-CB-POWERSEQ:~/prokka/Genome Data/NCBI FNA Files$ cpanm Bio::Root::Version
--> Working on Bio::Root::Version
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.7.8.tar.gz ... OK
Configuring BioPerl-1.7.8 ... OK
==> Found dependencies: XML::LibXML, Graph::Directed, DB_File, Test::Memory::Cycle, XML::LibXML::Reader
--> Working on XML::LibXML
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0206.tar.gz ... OK
Configuring XML-LibXML-2.0206 ... OK
Building and testing XML-LibXML-2.0206 ... FAIL
! Installing XML::LibXML failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
when run the cpanm Bio::Root::Version
again it got failed and not running
--> Working on Graph::Directed
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/Graph-0.9720.tar.gz ... OK
Configuring Graph-0.9720 ... OK
==> Found dependencies: Set::Object
--> Working on Set::Object
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/Set-Object-1.41.tar.gz ... OK
Configuring Set-Object-1.41 ... OK
Building and testing Set-Object-1.41 ... FAIL
! Installing Set::Object failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Set::Object' is not installed
! Bailing out the installation for Graph-0.9720.
--> Working on DB_File
Fetching http://www.cpan.org/authors/id/P/PM/PMQS/DB_File-1.855.tar.gz ... OK
Configuring DB_File-1.855 ... OK
Building and testing DB_File-1.855 ... FAIL
! Installing DB_File failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
--> Working on Test::Memory::Cycle
Fetching http://www.cpan.org/authors/id/P/PE/PETDANCE/Test-Memory-Cycle-1.06.tar.gz ... OK
Configuring Test-Memory-Cycle-1.06 ... OK
==> Found dependencies: PadWalker
--> Working on PadWalker
Fetching http://www.cpan.org/authors/id/R/RO/ROBIN/PadWalker-2.5.tar.gz ... OK
Configuring PadWalker-2.5 ... OK
Building and testing PadWalker-2.5 ... FAIL
! Installing PadWalker failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'PadWalker' is not installed
! Bailing out the installation for Test-Memory-Cycle-1.06.
! Installing the dependencies failed: Module 'Graph::Directed' is not installed, Module 'Test::Memory::Cycle' is not installed, Module 'DB_File' is not installed, Module 'XML::LibXML::Reader' is not installed, Module 'XML::LibXML' is not installed
! Bailing out the installation for BioPerl-1.7.8.

--> Working on Bio::Root::Version
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.7.8.tar.gz ... OK
Configuring BioPerl-1.7.8 ... OK
==> Found dependencies: XML::LibXML, Graph::Directed, DB_File, Test::Memory::Cycle, XML::LibXML::Reader
--> Working on XML::LibXML
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0206.tar.gz ... OK
Configuring XML-LibXML-2.0206 ... OK
Building and testing XML-LibXML-2.0206 ... FAIL
! Installing XML::LibXML failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
--> Working on Graph::Directed
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/Graph-0.9720.tar.gz ... OK
Configuring Graph-0.9720 ... OK
==> Found dependencies: Set::Object
--> Working on Set::Object
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/Set-Object-1.41.tar.gz ... OK
Configuring Set-Object-1.41 ... OK
Building and testing Set-Object-1.41 ... FAIL
! Installing Set::Object failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Set::Object' is not installed
! Bailing out the installation for Graph-0.9720.
--> Working on DB_File
Fetching http://www.cpan.org/authors/id/P/PM/PMQS/DB_File-1.855.tar.gz ... OK
Configuring DB_File-1.855 ... OK
Building and testing DB_File-1.855 ... FAIL
! Installing DB_File failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
--> Working on Test::Memory::Cycle
Fetching http://www.cpan.org/authors/id/P/PE/PETDANCE/Test-Memory-Cycle-1.06.tar.gz ... OK
Configuring Test-Memory-Cycle-1.06 ... OK
==> Found dependencies: PadWalker
--> Working on PadWalker
Fetching http://www.cpan.org/authors/id/R/RO/ROBIN/PadWalker-2.5.tar.gz ... OK
Configuring PadWalker-2.5 ... OK
Building and testing PadWalker-2.5 ... FAIL
! Installing PadWalker failed. See /home/powersequence/.cpanm/work/1618606243.15629/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'PadWalker' is not installed
! Bailing out the installation for Test-Memory-Cycle-1.06.
! Installing the dependencies failed: Module 'Graph::Directed' is not installed, Module 'Test::Memory::Cycle' is not installed, Module 'DB_File' is not installed, Module 'XML::LibXML::Reader' is not installed, Module 'XML::LibXML' is not installed
! Bailing out the installation for BioPerl-1.7.8.

**Comment by ramnageena11** [comment]
pls suggest how to rectify?

**Comment by ramnageena11** [comment]
I am waiting for suggestions. Thanks

**Comment by tomspicy0098** [comment]
I tried this and it worked.
[1]$conda create -n my_env_prokka python=3.9
[2]$conda install -c biobuilds perl=5.2.2
[3]$conda install -c bioconda prokka
I think a low version of perl(e.g. 5.2.2) should be installed firstly and then to install prokka.

**Comment by audjoselo** [comment]
#Hi, this work for me:
#Direct Installation
sudo apt update
sudo apt upgrade
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install -y libbio-searchio-hmmer-perl
sudo apt-get install libdatetime-perl libxml-simple-perl libdigest-md5-perl git default-jre bioperl
sudo cpan Bio::Perl
git clone https://github.com/tseemann/prokka.git $HOME/prokka
$HOME/prokka/bin/prokka –setupdb
sudo apt install prokka
#Finally, copying the DB files from $HOME/prokka/db folder to: /var/lib/prokka/db

**Comment by scmicrosys** [comment]
Hi all, 

this worked for me on MacStudio, M1, Ventura 13.6:

activate intel  x86_64 (using Rosetta)
conda create -n prokka python=3.9
conda activate prokka
conda install -c bioconda perl-bioperl
conda install -c conda-forge -c bioconda -c defaults prokka
prokka --help - no error
