### ISSUE TITLE
How to annotate multiple sequences at once?

### ISSUE THREAD

**Issue by adc123456** [tseemann/prokka#450]
I am new to prokka and I am just starting out so please bear with me. I have several genomes that have been previously assembled (roughly 150) and I would like to get them annotated. I can do each one individually but this will take along time and was wondering how I could automate the process. I am doing this on Linux and to get my desired results for a single genome I use the line:

prokka filename -prefix filename -o prokka 

is there a way to automate the process if all the assemblies are in one directory so that each assembly is annotated and the results are in a folder with the same name as the assembly?

Thank you

**Comment by mmaesaar** [comment]
Please check issue #237
