### ISSUE TITLE
Use prokka to reannotate genome with existing locus tags

### ISSUE THREAD

**Issue by thorellk** [tseemann/prokka#452]
Hi!

I have a bunch of genomes that I would like to reannotate since I have enhanced my curated annotation database. However, I would like to keep the locus tags intact, i.e. not redo the prodigal predictions to keep them consistent with work that I have already done with the genomes. Would that be possible? Eg. to start with a gff file?

**Comment by tseemann** [comment]
Sorry - not possible, and won't be added to this series of Prokka. But "re-annotation" is on the list for v2.
