### ISSUE TITLE
using --proteins with two reference files (for metagenome assembly)

### ISSUE THREAD

**Issue by DariiaVyshenska** [tseemann/prokka#454]
Hello!
I'm wondering if I can use prokka on a metagenome assembly but provide it with two or more reference genomes (.gb files). If the answer is yes, how exactly should I specify these .gb files (separated with commas or spaces) and how can I check if prokka used both files?
Thank you!

**Comment by tseemann** [comment]
Just concatenate your references and provide them via `--proteins all_refs.gb`
eg. `cat ref1.gb ref2.gb ref3.gb > all_refs.gb`
