### ISSUE TITLE
no output with prokka 1.14.5

### ISSUE THREAD

**Issue by ziejan** [tseemann/prokka#458]
Hi,
I use prokka 1.14.5 but I don't get any useful output. Only a .fna and a -log file besides an empty proteins.pdb-lock file. I don't know what I'm doing wrong.
Here is my logfile:
[prokka.log](https://github.com/tseemann/prokka/files/4108815/prokka.log)

What am I doing wrong? I do recognize that the makeblastdb fails but I don't know why this happens because executing the command manually works.

**Comment by ealdraed** [comment]
Hello @ziejan !

Please make sure your Genbank file contains the actual sequence at the end. Otherwise `prokka-genbank_to_fasta_db` will fail!

**Comment by tseemann** [comment]
The `tbl2asn` tool expired in December. You need to update it to 25.8 somehow.

**Comment by ziejan** [comment]
Thank you guys. I updated to tbl2asn 25.8 by downloading and extracting the executable file from here [ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/](url) and replacing the one in /usr/bin/tbl2asn with this new one. I still had the same problem but I used the .faa file from ncbi instead of the .gbff file as reference and now its working.
Thanks again.
