### ISSUE TITLE
Does prokka autodetect archaea genomes?

### ISSUE THREAD

**Issue by Lamm-a** [tseemann/prokka#466]
If I understand correcntly, Prokka calls prodigal for its annotation, prodagal autodetects archaeal genomes, is this functionalist carried over to prokka? If I am mistaken the same question but ignoring the prodigal bit.

**Comment by tseemann** [comment]
I am unaware of Prodigal being able to detect the genome is archaeal. 
Do you have a link to the documentation for this feature?

**Comment by Lamm-a** [comment]
Apologies it does not, a colleague though it did and I foolishly didn't check. Would there even be a way to check?

**Comment by tseemann** [comment]
Read the prodigal documention and/or ask the author on the prodigal github site. He will answer. Report back here if you find out!
