### ISSUE TITLE
Custom database - "cleaned product"

### ISSUE THREAD

**Issue by jellila** [tseemann/prokka#471]
Hello,

I have a problem with Prokka, specifically with custom database annotations using the --protein flag. I hope you can help me :)

I have two strain of the same bacterial subspecies, 505 and 506. I have annotated 505 using Prokka, then manually curated the annotations and created a .gb file of the whole genome (two chromosomes and five plasmids - yes, they have two chromosomes). Now, I would like to use my curated annotations to annotate 506 genome. I am using miniconda. This is what I did (from the log file)

/Users/Laura/opt/miniconda3/envs/tseemann/bin/prokka /Users/Laura/Desktop/Photobacterium/QMA0506-Pl5.fasta --outdir /Users/Laura/Desktop/506Annotations --prefix QMA0506 --locustag QMA0506 --proteins /Users/Laura/Desktop/QMA0505Annotations.gb

In plasmid5 of 505 there is my protein of interest, called AIP56, that I manually annotated, since it had initially come up as hypothetical protein. When I use my database though it still comes up as hypothetical protein. I had a look at the log file and apparently prokka recognises it, but then "cleans" the annotation and it reverts it back to hypothetical protein:

Modify product: AIP56 => hypothetical protein
Cleaned 1 /product names

I checked only this plasmid so far because it is small and it is easy to spot any "mistakes", but I suppose that something similar has happened also in other parts of the genome. Have you got any idea of what I am doing wrong? Just to double check, I also tried to re-annotate 505 with my curated database (coming from 505 itself), but the same happens and AIP56 gets "cleaned" out. Is there anything I am missing? If you need more details, just let me know :)

Thank you for your help!

Best regards,

Laura

**Comment by tseemann** [comment]
To prokka, a product name `AIP56` looks a lot like an errant locus_tag, not a functional gene description, so it removes it "for your own safety" :-)

Use this option to prevent the cleaning:
```
  --rawproduct       Do not clean up /product annotation (default OFF)
```

**Comment by jellila** [comment]
Thank you very much!
