### ISSUE TITLE
use locus_tag from reference genome when annotating with the --proteins option

### ISSUE THREAD

**Issue by ramiroricardo** [tseemann/prokka#472]
Hi,

I want to annotate a bacterial genome for which I have a very closely related reference. Thus I am using the --proteins option (and also tried with --rawproduct & --proteins). However, prokka will not add the locus_tag from my reference.gbk to the new annotation. Is there a way to do this? 

I would like to avoid annotation transfer, partially because part of my new genome has been HGT from a different species. 

Thanks for any help,

Ricardo

**Comment by tseemann** [comment]
This currently can not be done. It needs new logic to be written. Others have asked for it too. I usually suggest adding the locus_tag to the /product of your genbank, so that at least it will end up in the /product of your new genome.

**Comment by ramiroricardo** [comment]
Thank you for your reply. I had thought of doing that on the /gene of the genbank, but that is also a possibility, as I am then using this assembly as reference for breseq and both fields would be available

**Comment by tseemann** [comment]
Breseq is good, but have you tried Snippy ? :-)

**Comment by ramiroricardo** [comment]
it's on my to-do list ;)
