### ISSUE TITLE
can I use prokka to annotate genomes other than the ones included in the default databases?

### ISSUE THREAD

**Issue by fedeserral** [tseemann/prokka#473]
Hi, I wanted to know if prokka works well to annotate assemblies of genomes that are not included in your own databases such as staphylococcus, E.coli, etc.
I am new using prokka

Thanks a lot

**Comment by tseemann** [comment]
Yes definitely.

But if you have a good reference genome in genbank for your species, you will get an even better annotation if you download the `.gbk` file and pass it to the `--proteins` option.
