### ISSUE TITLE
Prokka or biological meaning?

### ISSUE THREAD

**Issue by jellila** [tseemann/prokka#476]
Hi all.

I have used Prokka to annotate two strain of the same subspecies. When I load the gff files on Geneious Prime I have several regions that look like this:
<img width="638" alt="Screenshot 2020-03-27 16 27 49" src="https://user-images.githubusercontent.com/62048347/77728293-ef6b5880-7047-11ea-95ff-628861162ec6.png">
but, having a closer look, there is nothing different at the end of CDS_1 compared to the one above. 
<img width="631" alt="Screenshot 2020-03-27 16 29 04" src="https://user-images.githubusercontent.com/62048347/77728449-43763d00-7048-11ea-9ad5-ea8fab1839a8.png">
Is it a Prokka-related problem or is there any biological meaning behind it? I cannot see any stop codon being introduced by the mutation?

Thanks :) 

Laura

**Comment by tseemann** [comment]
You have a deletion of a T in the CDS_1 that is not in CDS_3 ?
This is a frame-shift and it has moved into a stop codon in a different frame?
That deletion could be real, or a homopolymer error from seqencing.
