### ISSUE TITLE
Rfam Update

### ISSUE THREAD

**Issue by Phbe3211** [tseemann/prokka#48]
I am a Prokka user, thanks for providing, maintaining and updating the Prokka regularly. Could you guys please update the RFAM database to RFAM 12 in the next version of the Prokka  release. Seems much changes have been there compared to the earlier version of Rfam. 

I suggest that Prokka should provide Rfam.cm or Rfam.fasta what ever file using for the ncRNA "Rfam analysis" should be visible so that people can easily change/update the Rfam database and then no longer need to wait an update from the Prokka authors (wait for the next version, especially Rfam). Thank you and have a nice day.

**Comment by tseemann** [comment]
@Phbe3211  In the previous 11.0 release I found a "genome.gff3" file which had the taxonomy lineage of each RNA. I then filtered out CM models which did not have any Bacteria/Archaea members. But I'm having trouble doing the same for 12.0

**Comment by tseemann** [comment]
This has been done now!
