### ISSUE TITLE
Error message when opening .gff files in Artemis/ACT

### ISSUE THREAD

**Issue by sarah27m** [tseemann/prokka#480]
Error messages (below) when trying to open .gff files in Artemis

while reading from 30244_CbPhase1.gff: tRNA can't have inference as a qualifier
while reading from 30244_CbPhase1.gff: tmRNA can't have gene as a qualifier

Similar to this question although I can't see how this was resolved
https://github.com/tseemann/prokka/issues/341

**Comment by tseemann** [comment]
There is nothing to resolve.
Artemis is very old and has not kept up with the latest valid Genbank tags.
There is  a config file in `artemis/etc/` i think which you can added them.
You can safely ignore them!
