### ISSUE TITLE
Number of ORFs

### ISSUE THREAD

**Issue by EugeneKim76** [tseemann/prokka#495]
Hi,
To my knowledge Prokka uses Prodigal to detect ORFs.
Is there any way to know the number of ORFs found by prokka?
Best,

**Comment by tseemann** [comment]
Yes, each ORF becomes a gene (CDS) in the output files.

The prokka.txt tells you:

```
prokka.txt
organism: Escherichia coli strain 
contigs: 11
bases: 385319
CDS: 180
gene: 180
```

**Comment by EugeneKim76** [comment]
Thanks for quick answer.
You mean the number of genes in prokka.txt?
For example below, number of ORF is 5100?

tmRNA: 1
tRNA: 54
gene: 5100
CDS: 5045

**Comment by tseemann** [comment]
No, the number of ORF is 5045.
Not all genes code for protein. Some are RNA genes.
