### ISSUE TITLE
Prokka GFF files incompatible

### ISSUE THREAD

**Issue by mabouelk** [tseemann/prokka#498]
Hi Prof. Seemann, 

I am trying to run AMRFinderPlus (NCBI) on multiple samples but they said prokka .gff file are not compatible. I tried that and it did work 
perl -pe '/^##FASTA/ && exit; s/(\W)Name=/$1OldName=/i; s/ID=([^;]+)/ID=$1;Name=$1/' <prokka_output.gff>  > <amrfinder.gff>

but I do not how to do it on all files at once (batch run).

**Comment by tseemann** [comment]
Can you provide a specification or example of what the AMRFinder plus expects?
I thought AMRfinderPlus took the .fna file not the .gff file?

**Comment by mabouelk** [comment]
amrfinder -p test_prot.fa -g test_prot.gff -n test_dna.fa -O Campylobacter
yes, it can run using .fna file only but to automatically combine overlapping results from protein and nucleotide searches the coordinates of the protein in the assembly contigs must be indicated by the GFF file. This requires a GFF file where the value of the 'Name=' variable of the 9th field in the GFF must match the identifier in the protein FASTA file (everything between the '>' and the first whitespace character on the defline). See the section on GFF file format for details of how AMRFinderPlus associates FASTA file entries with GFF file entries.

they mentioned on their page 

Prokka GFF files incompatible
Using GFF files included with Prokka does not work because the format is different from what AMRFinderPlus expects. Running the following perl one liner will convert the Prokka output into a GFF file that AMRFinderPlus can read (replace <prokka_output.gff> with the GFF file you wish to use and <amrfinder.gff> with the name you wish to use for the AMRFinderPlus-compatible GFF file):
perl -pe '/^##FASTA/ && exit; s/(\W)Name=/$1OldName=/i; s/ID=([^;]+)/ID=$1;Name=$1/' <prokka_output.gff>  > <amrfinder.gff>

**Comment by tseemann** [comment]
```
perl -pi.bak '...............' *.gff
```

will copy all the gff to .gff.bak and replace .gff with the fixed one
