### ISSUE TITLE
--proteins option

### ISSUE THREAD

**Issue by Vers4L** [tseemann/prokka#500]
Hi, 
I am relatively new to the usage of prokka and I have a question regarding the --proteins option. I have two reference genomes of good quality which I would like to use for annotation. When I refer to both Genbank files using the --proteins option, I think prokka only uses the first Genbank file to annotate genes. Do the Genbank files need to be merged in order to use both genomes? Or is there another way to use multiple genomes with the --proteins option? 
A part of my code I am using now is: 
prokka --proteins NC_08463.gb NC_002516.gb

The option --usegenus could also be used for this, but it is not recommended anymore.

**Comment by tseemann** [comment]
Prokka can only take one genbank FILE.
However multiple genbank entries can be in the one file.

```
cat NC_08463.gb NC_002516.gb > prokka-refs.gbk
prokka --proteins prokka-refs.gbk
```

**Comment by marco315176** [comment]
Prokka solo acepta archivos .gbk o también fasta?
