### ISSUE TITLE
Script for running Prokka

### ISSUE THREAD

**Issue by Natashia695** [tseemann/prokka#503]
Hi ,

Can somebody point out where I am wrong in the following script for running prokka on 10 genome . A genome file which running on is named in the following manner e.g.   GCA_003612255.1_ASM361225v1_AB004_genomic.fna
```
#specify the shell type
#$ -S /bin/sh
#run in the current working directory
#$ -cwd
#specify which queue you wish to use
#$ -q amd.q
#Number of threads
#$ -pe multithread 2
#Limit memory
#$ -l h_vmem=16G
#How long it will run for (HH:MM:ss) (20 hours)
#$ -l h_rt=02:00:00
#Set stack memory
#$ -l h_stack=10M
#Output logfile
#$ -o output.log
#Error logfile
# -e error.log
#Make it an array
#$ -t 1-10
#Run program
NAME=$(head -n $SGE_TASK_ID species.txt | tail -n 1)
source $HOME/.bashrc
module load prokka
module load barrnap
prokka --outdir Myxococcus_Prokka_${NAME} --prefix ${NAME} $HOME/Myxococcus/${NAME} --cpus 2
```

I am assuming the nomenclature in the last line of the script is what I can't modify correctly. 
What would the changes be for an output of all the 10 genomes ?

**Comment by tseemann** [comment]
I am not familiar with cluster submission scripts, sorry.

But it looks like you didn't give prokka the actual contigs file?
