### ISSUE TITLE
[Question] Only saving .faa file

### ISSUE THREAD

**Issue by tivdnbos** [tseemann/prokka#510]
Hi,

I was wondering if it was possible to only generate and save the .faa file?
I use prokka on megahit output as follows: prokka --metagenome --cpus 30 --outdir /my_project/prokka/COM_06/ --prefix COM_06 /my_project/megahit-output/COM_06/final.contigs.fa

Bst wishes,
Tim

**Comment by tseemann** [comment]
Tim
Tjhere is no way to omly generate just the .faa file.
But you should just run prokka, copy the .faa file ro wjjhere you want it, then delete the original folder?
A wrapper bash script could be used?
```
# use a temp dir
prokka --outdir deleteme --prefix foo contigs.fa
cp deleteme/foo.fa realdir/
rm -fr deleteme
````
