### ISSUE TITLE
Can I turn off CRISPR prediction?

### ISSUE THREAD

**Issue by ilnamkang** [tseemann/prokka#518]
Hi,

Sometimes I'd like to use Prokka without CRISPR prediction.

Are there any command line options to turn off CRISPR prediction?

Thanks.

**Comment by tseemann** [comment]
There is currently no way to disable CRISPR detection.

Perhaps just filter out the CRISPR lines from the .gff output using `grep -v` ?

**Comment by ilnamkang** [comment]
Thank you for a reply.
