### ISSUE TITLE
blastp version number comparison error

### ISSUE THREAD

**Issue by CuriousTim** [tseemann/prokka#532]
I installed prokka with conda to use as a dependency of [MARVEL](https://github.com/LaboratorioBioinformatica/MARVEL).
`conda install -c conda-forge -c bioconda -c defaults prokka`

While MARVEL is running, prokka gives an error with the following messages in the log:

> Determined blastp version is 2.10
Prokka needs blastp 2.2 or higher. Please upgrade and try again.

I am guessing that the version numbers are converted to strings prior to comparison and 2.2 is greater than 2.10 so prokka incorrectly thinks that the blastp version is out of date. Is this already fixed?

**Comment by jvolkening** [comment]
I just ran into this as well. It looks like it was fixed in 1cc182a254a85f7cda722234dabfbdb03b786502, which was included in v1.14.4. My conda environment installed 1.13 without specifying, so you may need to pin it to a more recent release.

**Comment by CuriousTim** [comment]
Awesome! Thanks for letting me know.

**Comment by miraSantos** [comment]
I'm running into this error again in the latest version of prokka
