### ISSUE TITLE
Prokka error message

### ISSUE THREAD

**Issue by FCPLab007** [tseemann/prokka#534]
Hi everybody, I am trying to run Prokka but the following error message appears(Could not run command: makeblastdb -hash_index -dbtype prot -in \/cluster\/software\/prokka\/1.13.7-gompi-2019a\/db\/kingdom\/Archaea\/sprot -logfile /dev/null)

Here is my SLURM script:
 module load prokka/1.13.7-gompi-2019a 

prokka --setupdb -i /cluster/work/users/ahmedbar/191129_M01132.Project_Petersen-DNAlibs2-2019-11-06/Contigs_and_scafolds_2/contigs_F-1year-Amox_S15.fasta -o /cluster/work/users/ahmedbar/191129_M01132.Project_Petersen-DNAlibs2-2019-11-06/CD_HIT_output

**Comment by schultzm** [comment]
hi @FCPLab007 , have you tried also adding the command `module load blast`?
