### ISSUE TITLE
date format in gbk file

### ISSUE THREAD

**Issue by fetyj** [tseemann/prokka#542]
Hi,
i have installed prokka with conda few days ago ```prokka 1.14.6```. after annotating some fasta file I noticed that the date format was weird (```15-DéC.-2020```). When I use the files I got this error ```LOCUS line does not contain - at position 75 in date```
Can someone help me with this issue?
Thanks for your help

Regards 
Fety

**Comment by rpetit3** [comment]
Hi @fetyj 

I realize I'm a bit late, but Prokka uses tbl2asn to generate the Genbank.  I maintain [tbl2asn-forever](https://github.com/rpetit3/tbl2asn-forever/blob/master/tbl2asn-forever) which Prokka from conda uses. 

I wonder what you get from the following command `env | grep LANG`. I might need to force tbl2asn-forever to use `LANG=en_US.UTF-8`.

Cheers,
Robert

**Comment by fetyj** [comment]
Hi @rpetit3 
Here is the output from the command ``LANG=en_US.UTF-8 GDM_LANG=en_US LANGUAGE=en_US``
I tried a new analysis and the result is the same with date format ``11-JANV.-2021``
Regards,

Fety

**Comment by rpetit3** [comment]
That's weird, what do you get for `date`?

**Comment by fetyj** [comment]
for ``date`` I get ``lundi 11 janvier 2021, 16:21:32 (UTC+0100)``

**Comment by rpetit3** [comment]
Safe to say OS is using French? 

I wonder if running prokka like this: `LC_ALL=en_US.UTF-8 prokka ARGS` would fix your problem?

**Comment by fetyj** [comment]
Yes, you are right about OS. Indeed, your work-around works  like a charm :-) 
 Any idea to fix this in my conda environment for prokka?
thanks for your help

**Comment by rpetit3** [comment]
It might be worth trying an alias for prokka, before messing with conda.

In your `.bashrc` (or `.bash_profile`) add this:
```
alias prokka="LC_ALL=en_US.UTF-8 prokka"
```

**Comment by fetyj** [comment]
Thanks

Cheers,
Fety

**Comment by JipengLuo** [comment]
Hi Fety,
I have encountered the same problem with you, see it in the attachment.  The error shows that 'ERROR    06/07 09:45:03   LOCUS line does not contain - at position 75 in date:'. I just find this problem reporting page, I wonder did you resolve this problem? 

Looking forward to hearing from you.
Thank you. 
Jipeng
