### ISSUE TITLE
how to update blastp?

### ISSUE THREAD

**Issue by zhuanghemu** [tseemann/prokka#547]
Hi how can i update blastp?
[14:48:02] Looking for 'blastp' - found /root/miniconda3/envs/snippy/bin/blastp
[14:48:03] Determined blastp version is 002007 from 'blastp: 2.7.1+'
[14:48:03] Prokka needs blastp 2.8 or higher. Please upgrade and try again.

**Comment by drelo** [comment]
I left a possible workaround here. I hope it helps https://github.com/tseemann/prokka/issues/549#issuecomment-764611154

**Comment by rpetit3** [comment]
@zhuanghemu 

Bit late, I might be wrong but it looks like you have Prokka in a Snippy environment.

You can try 
```
conda activate snippy
conda update -c conda-frorge -c bioconda blast prokka
```

Or easier, would be to create a Prokka environment.

```
conda ccreate -n prokka -c conda-forge -c bioconda prokka
```

**Comment by zhuanghemu** [comment]
> @zhuanghemu
> 
> Bit late, I might be wrong but it looks like you have Prokka in a Snippy environment.
> 
> You can try
> 
> ```
> conda activate snippy
> conda update -c conda-frorge -c bioconda blast prokka
> ```
> 
> Or easier, would be to create a Prokka environment.
> 
> ```
> conda ccreate -n prokka -c conda-forge -c bioconda prokka
> ```

Thanks, it works.

**Comment by andersgs** [comment]
Thank you @rpetit3
