### ISSUE TITLE
blastp version issue

### ISSUE THREAD

**Issue by Ankita-1211** [tseemann/prokka#549]
Please Help !

Looking for 'blastp' - found /home/anaconda3/bin/blastp
Determined blastp version is 2.10
Prokka needs blastp 2.2 or higher. Please upgrade and try again.

**Comment by drelo** [comment]
https://github.com/tseemann/prokka/issues/544

**Comment by drelo** [comment]
Assuming you are using _`conda`_ I just managed to fix this error with this workaround. I just installed another version of blast and re installed prokka and other missing packages
I hope it helps
```
conda remove blast 
conda install -c bioconda blast=2.9.0
conda install -c conda-forge -c bioconda -c defaults prokka
conda install -c bioconda hmmer
sudo cpanm Bio::SearchIO::hmmer3 # normally this would work OUTSIDE conda
which perl # locate where is perl inside your environment
~/anaconda3/envs/myenv/bin/cpanm Bio::SearchIO::hmmer3 # use this cpanm
```

**Comment by Ankita-1211** [comment]
Thank you @drelo . It worked

Ran into another problem Could not run command: tbl2asn. But will resolve, saw some closed issues related to it.

**Comment by chenyibee233** [comment]
Hi @Ankita-1211 did you solve the tbl2asn problem? I met the same problem, and also need help
