### ISSUE TITLE
Is there a script to convert a gbk back to gff ?

### ISSUE THREAD

**Issue by avilaHugo** [tseemann/prokka#575]
Dear developers, I was wondering if there is a way to convert a gbk file into the default gff3 file generated by prokka. After a prokka  run a colleague of mine did a manual curation of several genes and I would like to get the gff3 file from this corrected annotation. First I thought about running the prokka a second time passing the gbk file as a reference (--proteins), but maybe this process would generate differences in the position of the features. What do you think ?

I tried converting with some tools like emboss seqret but when i imput the generated gff3 to tools like panaroo they return fomat errors.

**Comment by tseemann** [comment]
I have some internal scripts which I sometimes use, but they are not in the Prokka codebase.

Until then I have asked Panaroo author to maybe support GBK:

**Comment by avilaHugo** [comment]
I think that was the fastest response i ever had on github 

Thanks !
