### ISSUE TITLE
Is there a way to modify prokka to use Phanotate instead of Prodigal for ORF predictions?

### ISSUE THREAD

**Issue by jamesck2** [tseemann/prokka#636]
Hello, not really an issue, more of a request. I really like how Prokka integrates multiple annotation tools and wraps them together to produce an output with all the different types of annotations. I am working with Phage genomes, and I prefer Phanotate over Prodigal for ORF predictions. Is there a way I can mod Prokka to use Phanotate instead of Prodigal, if so, how would I go about that. Thanks in advance for any advice!

If this is not the appropriate place to ask this question, I'd be happy to remove and repost this somewhere else as suggested.

**Comment by gbouras13** [comment]
Hi James,

I have cobbled together phrokka (and is named in honour of and as a pun on Prokka, but for phages)  which seems like what you are looking for. It uses Phanotate for ORF predictions and Phrogs as the database for functional annotation.

It's a work in progress for now, but should hopefully work.

https://github.com/gbouras13/phrokka

George

**Comment by jamesck2** [comment]
This is exactly what I was looking for, thank you for doing this!

**Comment by jamesck2** [comment]
FYI, I had to download the PHROGs mmseqs, hmms, and annotations manually before I could run install_databases.py. Wasn't a pain at all, just a heads up that bit didn't work.

**Comment by gbouras13** [comment]
Hi James,

Can you open an issue on the repo if possible describing the error - I will look inot it.

george
