### ISSUE TITLE
Issue with installing conda environment in docker container

### ISSUE THREAD

**Issue by colin-heberling** [tseemann/prokka#654]
I am trying to create a docker container that pipelines several different tools, hence why I am not using the stand-alone prokka docker container.  

First, I installed prokka via conda using the installation guide on github:
`conda install -c conda-forge -c bioconda -c defaults prokka`

I exported the environment to a .yml file.  In my dockerfile, I copy the .yml file into the container directory structure, then install while building the container.  The installation fails with the following errors (see attached):

[prokka_MGE_conda_docker_errors.txt](https://github.com/tseemann/prokka/files/10739352/prokka_MGE_conda_docker_errors.txt)

**Comment by rpetit3** [comment]
Hi @colin-heberling ,

Check these out to see if they'll work for you: https://quay.io/repository/biocontainers/prokka?tab=tags

**Comment by colin-heberling** [comment]
Like I said, I'd like to get prokka working within my own docker container because it's pipelined with other tools as well, all of which are working fine.

**Comment by rpetit3** [comment]
Ah apologies for misreading. Maybe best to share the conda yaml and dockerfile

**Comment by colin-heberling** [comment]
So I removed the conda environment and recreated it the same way as before (using the installation instructions on the main github page for prokka), and recreated the .yml file.  The yml file is an exact duplicate as the previous one, but now for whatever reason everything works fine.  Nothing should have changed, so I don't understand why it's working now.
