### ISSUE TITLE
Specify GitHub release does not include big databases

### ISSUE THREAD

**Issue by aleimba** [tseemann/prokka#73]
since this has come up several times in the issues (e.g. #49 and #61), I think it would be good to specify more clearly in the README that only the *.tar.gz on the VBC website includes all databases (alternatively in the FAQs) and not the GitHub release.

Another possibility, or perhaps in addition to the ones above, is to give a warning message with **--setupdb** that not all databases are present that a _normal_ user would expect.

**Comment by tseemann** [comment]
Yes I need to do this... GitHub will soon have "LFS" large file support which I will try and use. Until then I need to write a helper script to download the data from bintray.com or similar.

**Comment by aleimba** [comment]
oh, looking forward to GitHub's LFS ;-).

Never heard of bintray.com, but looks good. I you can pull them down during **--setupdb** would be great.

Optimal would be if you could download the big database files directly from the suppliers and format them during Prokka's **--setupdb**.

That has the **advantage** that you'll always get the newest versions and they rest outside of the Prokka distribution.

I can think of two **disadvantages**. Installation would take a lot longer. And I don't know how much work you have with all the formatting.

Let me know if I can help you.
