### ISSUE TITLE
change protein name initials to lowercase

### ISSUE THREAD

**Issue by aleimba** [tseemann/prokka#75]
it might be useful to lower the case for initials in _/product_ descriptions (as needed for NCBI). For this purpose add the following lines in sub _cleanup_product_ (https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L1259):

``` Perl
$p =~ s/\b([A-Z][a-z]{3,})/\l$1/g; # lower the case for protein desc initials
$p =~ s/(rossman|willebrand)/\u$1/; # exception to the rule
```

Actually, I have this integrated in [`tbl2tab`](https://github.com/aleimba/bac-genomics-scripts/blob/master/tbl2tab/tbl2tab.pl#L628-629), so far it works ...

**Comment by tseemann** [comment]
@aleimba Your first rule allows 3 *or more* characters. It would be unlikely for a protein/gene code to be 7 long, so what do you think if we make it {3,5} and then we don't have to fix up rossman or willebrand?

**Comment by aleimba** [comment]
@tseemann Sounds good to me!

**Comment by tseemann** [comment]
Actually I mis-understood your query. I got very confused sorry!

You mean the first letter of a /product.  
I made mistake and thought you meant the "Gene" code at end of a /product!

So what I said does not make sense. I think I need to scan Uniprot to see what other exceptions to the Rule exist before I make this change.

**Comment by aleimba** [comment]
apparently I got confused as well after my vacation ... And yes, you're right this is meant for "description-words" in /product.
Let me know if you need anything else, thanks.

**Comment by tseemann** [comment]
I don't plan to do any more on this feature.
