### ISSUE TITLE
Prokka annotating tranposon as DnaA in Bacillus

### ISSUE THREAD

**Issue by tseemann** [tseemann/prokka#94]
Recently I found some weird results when annotating Bacillus cereus genome.
I used prokka version 1.10. And now I'm downloading v1.11 now.
Anyway, the Prokka predicted 9 CDS as DnaA.
Only one of them is a real DnaA. The others are all transposases.
Below is the transpose sequence.
MKNSYQQLTTNLEYLKLKQMAQHLGDVVDFSINNELSFVETLVKLTNYEIDVREQNMIHS
MVKMGAFPHRKEVDEFDFEFQPSINKQQILDFISLRFLEQQENIVFLGPSGVGKTHLATS
IGIAAAKKRTSTYFIKCHDLLQNLKRAKIENRLESRLKHYTKYKLLIIDEIGYLPIDPED
AKLFFQLIDMRYEKRSTILTTNINFKSWDEVFQDPKLANAILDRVLHHATVVSIVGQSYR
IKDHFSKEND

It appears this IS has a domain nearly identical to DnaA. It doesn't hit sprot so it moves along to the HMM databases. CLUSTERS gets it right order, but HAMAP doesn't.

**Comment by amvarani** [comment]
Hi there,

In fact this is not a transposase. This is indeed the istB gene, helper of transposition commonly found in IS21 family.
This helper of transpostion share some binding domain with the dnaA genes. There is no much information about the istB gene function during the transposition, but certainlly is related with binding activity. 

Take a look in the ISfinder webpage for more information (https://www-is.biotoul.fr/) or in the new Mobile DNA (volume III) book which is about to be released.
We are also going to release a new version of the ISfinder website soon.

**Comment by tseemann** [comment]
@amvarani Thanks for replying to this. The above statement is not my words, but from an email I got from someone.

ISFinder is still not publicly available which is very frustrating. I was able to get a HMM library for it, but that it not what the community needs. If I the database was available it could be incorporated into Prokka properly.

Are you able to help with this problem?

**Comment by amvarani** [comment]
Maybe a set of curated HMMs models for each IS family. This could be implemented on prokka and helps to correct annotate transposases.

**Comment by amvarani** [comment]
Hi there
I have a HMM file with curated annotation of IS transposases which can be used in prokka. Let me known if you have interest to include it in prokka

**Comment by amvarani** [comment]
@tseemann , I have done the hmm file of ISfinder proteins which could be used in prokka. Please contact me to in order to arrange how can we deal with that

**Comment by tseemann** [comment]
@amvarani Thanks for providing the HMMs but I really need the alignment files to be able to ensure I can build compatible HMMs.

**Comment by tseemann** [comment]
UPDATE: prokka inlcudes an IS transposase database now, and it is used with high priority.
