### ISSUE TITLE
Custom database directory

### ISSUE THREAD

**Issue by shaman-narayanasamy** [tseemann/prokka#95]
Dear authors,

We would like to specify the directory which the databases are to be indexed/built. Is it possible to include an option, say `--dbdir` for this purpose? In my case, I want `prokka` binaries to be located in a separate directory (`/usr/bin/prokka`) and the databases located in a separate directory (`/archive/data/db`).

Perhaps there is already a way to do this that I am not aware of...

Looking forward to hear from you. Thanks in advance.

-Shaman-

**Comment by aleimba** [comment]
Hi,

in Unix flavors the easiest way is to softlink your binaries (see e.g. https://kb.iu.edu/d/abbe for an explanation). You don't have to move any files for that. Issue #49 might help as well.

**Comment by tseemann** [comment]
@shaman-narayanasamy Do you mean ALL the prokka databases, or your custom databases?

1. You can use the --proteins or --hmms option to use a custom database for a prokka run.

2. You can change this line in the main prokka script:
````my $DBDIR = "$FindBin::RealBin/../db";```` 
to point to wherever you wish.
